% Task 14 probes: strict-path headline numbers, the new error paths, the PM domain halt's
% field-set completeness, and a strict Tier-2 smoke run.
ROOT = ['/Users/yikaiyang/Library/CloudStorage/OneDrive-Nexus365/' ...
        'Programming scripts/Matlab/Simulation/invZ expansion'];
cd(ROOT);
addpath(ROOT); addpath(fullfile(ROOT, 'invz_common'));
addpath(genpath(fullfile(ROOT, 'invz_projected')));

ion = invz_ion();
Jnu = linspace(-2e-3, 6.0e-3, 24).';
o   = struct('J0eff', 6.42e-3, 'Jxx0', ion.Jxx0, 'hyp', true);

% ---- P1: strict jensen headline numbers (cross-check vs the ledger's own measurements) -----
oj = o;  oj.ordered_mode = 'jensen';  oj.static_medium = 'strict_1z_dyson_ref';
ps = invz_solve_point_ordered(ion, 0.31, [2.85 0 0], Jnu, oj);
fprintf('P1 STRICT JENSEN: converged=%d is_ordered=%d stable_1z=%d\n', ...
    ps.converged, ps.is_ordered, ps.stable_1z);
fprintf('P1 hmf=%.17g crit_1z=%.17g D_uni=%.17g Dq_min=%.17g\n', ...
    ps.hmf, ps.crit_1z, ps.D_uni, ps.Dq_min);
fprintf('P1 omit_mu3=%.17g omit_cubic=%.17g omit_max=%.17g path_omit_max=%.17g\n', ...
    ps.omit_mu3, ps.omit_cubic, ps.omit_max, ps.path_omit_max);
fprintf('P1 static_medium=%s medium_status=%s denom=%.17g margin=%.17g\n', ...
    ps.static_medium, ps.medium_status, ps.medium_denom, ps.medium_margin);
fprintf('P1 hprof.omit_max range=[%.6g %.6g] n=%d nnan=%d\n', ...
    min(ps.hmf_prof.omit_max), max(ps.hmf_prof.omit_max), ...
    numel(ps.hmf_prof.omit_max), nnz(isnan(ps.hmf_prof.omit_max)));
fprintf('P1 Jmom.mu2=%.17g (direct=%.17g)\n', ps.Jmom.mu2, ...
    getfield(invz_coupling_moments(Jnu), 'mu2'));  %#ok<GFLD>

% ---- P2: PM strict domain halt (ref_margin above denom = 1 + Sigma0) -----------------------
ok_pm  = invz_solve_point(ion, 0.31, [2.85 0 0], Jnu, setfield(o, ...
             'static_medium', 'strict_1z_dyson_ref'));  %#ok<SFLD>
oh = o;  oh.static_medium = 'strict_1z_dyson_ref';  oh.ref_margin = 2;
halt = invz_solve_point(ion, 0.31, [2.85 0 0], Jnu, oh);
fprintf('P2 HALT: medium_status=%s converged=%d outer_iters=%d crit=%.6g alpha=%.6g\n', ...
    halt.medium_status, halt.converged, halt.outer_iters, halt.crit, halt.alpha);
fprintf('P2 K(1)=%.6g G(1)=%.6g lambda=[%s] sumrule_rel=%.6g denom=%.6g margin=%.6g\n', ...
    halt.K(1), halt.G(1), num2str(halt.lambda(:).'), halt.sumrule_rel, ...
    halt.medium_denom, halt.medium_margin);
fa = fieldnames(ok_pm);  fb = fieldnames(halt);
fprintf('P2 FIELDSET identical=%d  (only_in_ok={%s} only_in_halt={%s})\n', ...
    isempty(setdiff(fa,fb)) && isempty(setdiff(fb,fa)), ...
    strjoin(setdiff(fa,fb)', ','), strjoin(setdiff(fb,fa)', ','));
fprintf('P2 ok_pm: medium_status=%s converged=%d crit=%.17g denom=%.17g margin=%.17g\n', ...
    ok_pm.medium_status, ok_pm.converged, ok_pm.crit, ok_pm.medium_denom, ok_pm.medium_margin);

% ---- P3: the new rejections --------------------------------------------------------------
probes = { ...
  'ordered strict + odd_retarded',        @() invz_solve_point_ordered(ion, 0.31, [2.85 0 0], ...
      Jnu, mergeo(oj, struct('odd_retarded', true))); ...
  'ordered strict + odd_retarded_exact',  @() invz_solve_point_ordered(ion, 0.31, [2.85 0 0], ...
      Jnu, mergeo(oj, struct('odd_retarded_exact', true))); ...
  'ordered strict + [nJ,nw] Jnu matrix',  @() invz_solve_point_ordered(ion, 0.31, [2.85 0 0], ...
      [Jnu Jnu], oj); ...
  'ordered per-leg emt override',         @() invz_solve_point_ordered(ion, 0.31, [2.85 0 0], ...
      Jnu, mergeo(o, struct('emt', struct('static_medium', 'strict_1z_dyson_ref')))); ...
  'ordered per-leg emt_static override',  @() invz_solve_point_ordered(ion, 0.31, [2.85 0 0], ...
      Jnu, mergeo(o, struct('emt_static', struct('static_medium', 'strict_1z_bare_ref')))); ...
  'PM strict + [nJ,nw] Jnu matrix (ALLOWED)', @() invz_solve_point(ion, 0.31, [2.85 0 0], ...
      [Jnu Jnu], setfield(o, 'static_medium', 'strict_1z_dyson_ref')) };  %#ok<SFLD>
for i = 1:size(probes, 1)
    try
        probes{i,2}();
        fprintf('P3 %-42s -> NO ERROR\n', probes{i,1});
    catch err
        fprintf('P3 %-42s -> %s\n', probes{i,1}, err.identifier);
    end
end

% ---- P4: early returns under strict carry the full member set ------------------------------
e1 = invz_solve_point_ordered(ion, 2.0, [2.85 0 0], Jnu, setfield(o, ...
         'static_medium', 'strict_1z_dyson_ref'));  %#ok<SFLD>
fprintf('P4 bare early: is_ordered=%d static_medium=%s medium_status=%s Jmom.mu2=%.6g\n', ...
    e1.is_ordered, e1.static_medium, e1.medium_status, e1.Jmom.mu2);
oj2 = oj;  % jensen at a PM point -> the hstar-nonfinite early return
e2 = invz_solve_point_ordered(ion, 2.0, [2.85 0 0], Jnu, oj2);
fprintf('P4 jensen early: is_ordered=%d hmf_status=%s stable_1z=%d crit_1z=%g D_uni=%g\n', ...
    e2.is_ordered, e2.hmf_status, e2.stable_1z, e2.crit_1z, e2.D_uni);
fprintf('P4 jensen early fields: %s\n', strjoin(fieldnames(e2)', ', '));
need = {'static_medium','Jmom','medium_status','medium_denom','medium_margin', ...
        'stable_1z','crit_1z','Dq_min','omit_mu3','omit_cubic','omit_max','path_omit_max'};
fprintf('P4 jensen early has ALL new members = %d\n', all(isfield(e2, need)));

% ---- P5: strict + Tier-2 smoke (local_sigma_loop under a strict scheme) --------------------
n = 6;  [h, k, l] = ndgrid((0:n-1)/n);  qvec = [h(:) k(:) l(:)];  qvec(1,:) = [];
[Vca, Vcb, Vcc, infoB] = invz_odd_blocks(ion, qvec, struct('dpRng', 10, 'cache', true));
S = struct('Vca', Vca, 'Vcb', Vcb, 'Vcc', Vcc, 'Jcc0', infoB.Jcc0);
ot = struct('J0eff', infoB.Jcc0, 'Jxx0', infoB.Jaa0, 'odd', true, 'odd_blocks', S, ...
            'static_medium', 'strict_1z_dyson_ref');
t1 = invz_solve_point(ion, 1.80, 0.05, [], ot);
ot.odd_tier2 = true;
t2 = invz_solve_point(ion, 1.80, 0.05, [], ot);
fprintf('P5 tier1 strict: converged=%d crit=%.6g Sigma0=%.6g denom=%.6g status=%s\n', ...
    t1.converged, t1.crit, t1.Sigma0, t1.medium_denom, t1.medium_status);
fprintf('P5 tier2 strict: converged=%d crit=%.6g iters=%d denom=%.6g status=%s resid=%.3g\n', ...
    t2.converged, t2.crit, t2.tier2_iters, t2.medium_denom, t2.medium_status, t2.tier2_resid);
% Can a Tier-2-only domain event exist? denom = 1 + Sigma0 in both tiers; report both.
fprintf('P5 denom tier1=%.17g tier2=%.17g (dyson ref denom = 1 + Sigma0)\n', ...
    t1.medium_denom, t2.medium_denom);

function s = mergeo(s, add)
f = fieldnames(add);
for i = 1:numel(f), s.(f{i}) = add.(f{i}); end
end
