% Task-12 fix-round-1 re-review probe (read-only). F9 identity, F10 field order/count,
% F2 reachable term_reason set, F12 wrapper decoupling.
ROOT = '/Users/yikaiyang/Library/CloudStorage/OneDrive-Nexus365/Programming scripts/Matlab/Simulation/invZ expansion';
addpath(genpath(fullfile(ROOT,'invz_projected'))); addpath(fullfile(ROOT,'invz_common'));
addpath(ROOT);
ion = invz_ion();  T = 0.31;  Bx = [2.85 0 0];
Jnu = linspace(-2e-3, 6.0e-3, 24).';
o = struct('J0eff', 6.42e-3, 'Jxx0', ion.Jxx0, 'hyp', true, ...
           'static_medium', 'strict_1z_dyson_ref');
ALLOWED = {'converged','max_iter','refresh_failed','bare_shortcut','medium_out_of_domain'};

% --- strict normal path, traced ------------------------------------------------------------
ot = o;  ot.trace = true;
[h1, p1, t1] = invz_hmf_ordered(ion, T, Bx, Jnu, ot);
f1 = fieldnames(t1.nodes);
fprintf('STRICT ok : h=%.17g status=%s trcNodes=%d nFields=%d schema_version=%d\n', ...
    h1, p1.status, numel(t1.nodes), numel(f1), t1.schema_version);
fprintf('  term_reason field index = %d ; ok_final index = %d\n', ...
    find(strcmp(f1,'term_reason')), find(strcmp(f1,'ok_final')));
fprintf('  field order: %s\n', strjoin(f1.', ','));
fprintf('  F9: slope0=%.17g  r_pm0+J0eff*G0bare_pm0=%.17g  bitwise=%d\n', ...
    p1.slope0, p1.r_pm0 + o.J0eff*p1.G0bare_pm0, ...
    isequaln(p1.slope0, p1.r_pm0 + o.J0eff*p1.G0bare_pm0));
fprintf('  trc term_reason set = {%s} ; all in ALLOWED = %d\n', ...
    strjoin(unique({t1.nodes.term_reason}),','), ...
    all(ismember({t1.nodes.term_reason}, ALLOWED)));
fprintf('  prof.node_term_reason set = {%s} ; all in ALLOWED = %d\n', ...
    strjoin(unique(p1.node_term_reason),','), all(ismember(p1.node_term_reason, ALLOWED)));

% --- strict DOMAIN path, traced -------------------------------------------------------------
od = o;  od.trace = true;  od.ref_margin = 1e9;
[hd, pd, td] = invz_hmf_ordered(ion, T, Bx, Jnu, od);
fd = fieldnames(td.nodes);
fprintf('DOMAIN    : h=%g status=%s trcNodes=%d nFields=%d schema_version=%d\n', ...
    hd, pd.status, numel(td.nodes), numel(fd), td.schema_version);
fprintf('  field order identical to normal path = %d\n', isequal(fd, f1));
fprintf('  trc term_reason set = {%s} ; all in ALLOWED = %d ; all in OLD4 = %d\n', ...
    strjoin(unique({td.nodes.term_reason}),','), ...
    all(ismember({td.nodes.term_reason}, ALLOWED)), ...
    all(ismember({td.nodes.term_reason}, ALLOWED(1:4))));
fprintf('  ref_margin == ref_denom - 1e9 bitwise = %d (ref_denom(1)=%.17g ref_margin(1)=%.17g)\n', ...
    isequaln(pd.ref_margin, pd.ref_denom - 1e9), pd.ref_denom(1), pd.ref_margin(1));

% --- force_bare, traced ---------------------------------------------------------------------
ob = o;  ob.trace = true;  ob.force_bare = true;
[hb, pb, tb] = invz_hmf_ordered(ion, T, Bx, Jnu, ob);
fb = fieldnames(tb.nodes);
fprintf('FBARE     : h=%.6g status=%s trcNodes=%d nFields=%d\n', hb, pb.status, ...
    numel(tb.nodes), numel(fb));
fprintf('  field order identical = %d ; trc term_reason = {%s} ; all in ALLOWED = %d\n', ...
    isequal(fb, f1), strjoin(unique({tb.nodes.term_reason}),','), ...
    all(ismember({tb.nodes.term_reason}, ALLOWED)));
fprintf('  F11 discriminators on bare nodes: K0 set=%s  D_uni allNaN=%d  outer_iters set=%s  resid_static allNaN=%d\n', ...
    mat2str(unique([tb.nodes.K0])), all(isnan([tb.nodes.D_uni])), ...
    mat2str(unique([tb.nodes.outer_iters])), all(isnan([tb.nodes.resid_static])));

% --- F12: wrapper decoupling ------------------------------------------------------------------
w = invz_ordered_trace(ion, T, Bx, Jnu, struct('solve', ...
    struct('J0eff', 6.42e-3, 'Jxx0', ion.Jxx0, 'hyp', true)));
fprintf('WRAPPER   : invz_ordered_trace schema_version=%d (raw trc is now %d)\n', ...
    w.schema_version, t1.schema_version);
fprintf('  wrapper .nodes nFields=%d (payload carries the bumped shape under version %d)\n', ...
    numel(fieldnames(w.nodes)), w.schema_version);
fprintf('\nPROBE3 DONE\n');
