ROOT = ['/Users/yikaiyang/Library/CloudStorage/OneDrive-Nexus365/' ...
        'Programming scripts/Matlab/Simulation/invZ expansion'];
cd(ROOT);
SP = ['/private/tmp/claude-503/-Users-yikaiyang-Library-CloudStorage-OneDrive-Nexus365-' ...
      'Programming-scripts-Matlab-Simulation-invZ-expansion/' ...
      'e72c63b7-dc11-4663-9d4b-867feace2d26/scratchpad/lintbase'];
files = {'invz_projected/invz_spectra_map.m', ...
         'invz_projected/tests/test_invz_spectra_map_phase_reasons.m', ...
         fullfile(SP, 'base_map.m'), fullfile(SP, 'base_test.m')};
for k = 1:numel(files)
    m = checkcode(files{k}, '-struct');
    fprintf('=== %s : %d messages ===\n', files{k}, numel(m));
    for j = 1:numel(m), fprintf('  L %d: %s\n', m(j).line, m(j).message); end
end
fprintf('LINTDONE\n');
