ROOT = ['/Users/yikaiyang/Library/CloudStorage/OneDrive-Nexus365/' ...
        'Programming scripts/Matlab/Simulation/invZ expansion'];
cd(ROOT);
addpath(genpath(fullfile(ROOT, 'invz_projected')));
addpath(fullfile(ROOT, 'invz_common'));

files = {'invz_projected/tests/test_invz_matsubara_twolevel.m', ...
         'invz_projected/tests/test_invz_gstat_ordered.m', ...
         'invz_projected/tests/test_invz_hmf_ordered.m', ...
         'invz_projected/tests/test_invz_deltaF.m', ...
         'invz_projected/tests/test_invz_single_ion.m', ...
         'invz_projected/tests/test_invz_transverse_mf_threading.m', ...
         'invz_projected/tests/test_invz_field_angle.m', ...
         'invz_projected/tests/test_invz_emt_static_ordered.m', ...
         'invz_projected/tests/test_invz_ordered_residual_strict.m', ...
         'invz_projected/tests/test_invz_ordered_node_solve_strict.m'};

r = runtests(files);
disp(table(r));
fprintf('CONSUMERS P=%d F=%d I=%d T=%d\n', nnz([r.Passed]), nnz([r.Failed]), ...
        nnz([r.Incomplete]), numel(r));
f = find(~[r.Passed]);
for k = 1:numel(f)
    fprintf('NOTPASSED %s Failed=%d Incomplete=%d\n', r(f(k)).Name, r(f(k)).Failed, r(f(k)).Incomplete);
end
if isempty(f), fprintf('ALL CONSUMER TESTS PASSED\n'); end
