function out = invzf_bilocal_quadratic_medium(kernel,Jmodes,modeWeights,opts)
%INVZF_BILOCAL_QUADRATIC_MEDIUM C3-zero fixed-source bilocal pilot.
%
%   OUT=INVZF_BILOCAL_QUADRATIC_MEDIUM(KERNEL,JMODES,MODEWEIGHTS,OPTS)
%   stationarizes the Gaussian lattice trace plus the exact local quadratic
%   fixed-source correction supplied by
%   invzf_local_bilocal_hessian_modes.  It requires every supplied C3 entry
%   to equal zero, so the leading nonlocal C3-C3 skeleton vanishes in the
%   supplied finite model.  This algebraic check is not by itself a
%   physical Z2-symmetry certificate.
%
%   On nonnegative Matsubara representatives, let
%
%     R_n = <D_qn>_q-C2_n,
%     Hcorr = Hlocal_fixed_source-Hlocal_gaussian.
%
%   The trial energy is the Gaussian trace plus R'*Hcorr*R/2.  Its
%   stationary covariance is
%
%     D_qn^-1 = C2_n^-1-J_q+Sigma_n,
%     Sigma = diag(2*beta./w_n)*Hcorr*R.
%
%   Positive denominators are enforced by an exact exponential coordinate,
%   not a floor.  Several declared scale starts are retained and every
%   distinct converged stationary point is compared by the same trial
%   energy.
%
%   This is a quadratic-bilocal skeleton discriminator, not the exact
%   nonlinear partial Legendre functional.  The start family is not a
%   complete root enumeration, the Matsubara tail is not completed, and
%   functional_use_authorized is always false.

if nargin < 3 || isempty(modeWeights)
    modeWeights = ones(size(Jmodes));
end
if nargin < 4 || isempty(opts), opts = struct(); end
if ~(isstruct(opts) && isscalar(opts))
    error('invzf:bilocalMediumOpts','opts must be a scalar struct.');
end
if ~(isstruct(kernel) && isscalar(kernel) && ...
        isfield(kernel,'schema') && ...
        startsWith(kernel.schema,'invzf_local_bilocal_hessian_modes/') && ...
        isfield(kernel,'status') && strcmp(kernel.status,'ok'))
    error('invzf:bilocalMediumKernel', ...
        'kernel must be an ok invzf_local_bilocal_hessian_modes result.');
end
required = {'C2','C3','beta','frequency_weights', ...
    'energy_bilocal_hessian_fixed_source', ...
    'energy_bilocal_hessian_gaussian'};
for k = 1:numel(required)
    if ~isfield(kernel,required{k})
        error('invzf:bilocalMediumKernel', ...
            'kernel.%s is required.',required{k});
    end
end
if any(kernel.C3 ~= 0)
    error('invzf:bilocalMediumSymmetry', ...
        ['This first pilot requires exact C3=0.  Nonzero source needs the ' ...
         'same-order nonlocal C3-C3 skeleton.']);
end

validateattributes(Jmodes,{'numeric'}, ...
    {'real','vector','finite','nonempty'},mfilename,'Jmodes');
validateattributes(modeWeights,{'numeric'}, ...
    {'real','vector','finite','nonnegative','numel',numel(Jmodes)}, ...
    mfilename,'modeWeights');
Jmodes = Jmodes(:);
modeWeights = modeWeights(:);
if sum(modeWeights) <= 0
    error('invzf:bilocalMediumWeights', ...
        'modeWeights must have positive total weight.');
end
modeWeights = modeWeights/sum(modeWeights);

C2 = kernel.C2(:);
beta = kernel.beta;
frequencyWeights = kernel.frequency_weights(:);
nmodes = numel(C2);
if numel(frequencyWeights) ~= nmodes
    error('invzf:bilocalMediumKernel', ...
        'kernel frequency weights do not match kernel.C2.');
end
Hsource = kernel.energy_bilocal_hessian_fixed_source;
Hgaussian = kernel.energy_bilocal_hessian_gaussian;
if ~isequal(size(Hsource),[nmodes,nmodes]) || ...
        ~isequal(size(Hgaussian),[nmodes,nmodes])
    error('invzf:bilocalMediumKernel', ...
        'kernel bilocal Hessian shapes do not match kernel.C2.');
end
Hcorrection = (Hsource-Hgaussian);
Hcorrection = (Hcorrection+Hcorrection.')/2;
selfEnergyMap = diag(2*beta./frequencyWeights)*Hcorrection;

startFactors = get_opt(opts,'start_factors',[0.01 0.1 1 10]);
validateattributes(startFactors,{'numeric'}, ...
    {'real','vector','finite','positive','nonempty'}, ...
    mfilename,'opts.start_factors');
residualTolerance = get_opt(opts,'residual_tolerance',1e-9);
rootTolerance = get_opt(opts,'root_tolerance',1e-8);
energyAbsoluteTolerance = get_opt(opts,'energy_absolute_tolerance',1e-10);
energyRelativeTolerance = get_opt(opts,'energy_relative_tolerance',1e-8);
validateattributes([residualTolerance,rootTolerance, ...
    energyAbsoluteTolerance,energyRelativeTolerance], ...
    {'numeric'},{'real','vector','finite','positive'});
maxIterations = get_opt(opts,'max_iterations',500);
maxEvaluations = get_opt(opts,'max_evaluations',5000);
validateattributes([maxIterations,maxEvaluations],{'numeric'}, ...
    {'real','vector','finite','integer','positive'});

Jmax = max(Jmodes);
energyScale = max([max(abs(Jmodes)),max(1./C2),eps]);
lowerBound = Jmax-1./C2;
solverOptions = optimoptions('fsolve', ...
    'Display','off', ...
    'FunctionTolerance',min(1e-12,residualTolerance/10), ...
    'StepTolerance',min(1e-12,residualTolerance/10), ...
    'OptimalityTolerance',min(1e-12,residualTolerance/10), ...
    'MaxIterations',maxIterations, ...
    'MaxFunctionEvaluations',maxEvaluations);

roots = repmat(empty_root(nmodes),0,1);
attempts = repmat(empty_attempt(nmodes),numel(startFactors),1);
for k = 1:numel(startFactors)
    initialSigma = max(0,lowerBound)+startFactors(k)*energyScale;
    initialY = log(initialSigma-lowerBound);
    residualFunction = @(y) scaled_residual(y,lowerBound,C2, ...
        Jmodes,modeWeights,selfEnergyMap,energyScale);
    [y,residual,exitflag,output] = ...
        fsolve(residualFunction,initialY,solverOptions);
    sigma = lowerBound+exp(y);
    [scaledResidual,R,Dq,denominator] = evaluate_residual( ...
        sigma,C2,Jmodes,modeWeights,selfEnergyMap,energyScale);
    residualNorm = norm(scaledResidual,inf);
    domainMargin = min(denominator,[],'all');
    finite = all(isfinite([sigma;R;Dq(:);denominator(:); ...
        scaledResidual;residual(:)]));
    accepted = exitflag > 0 && finite && ...
        residualNorm <= residualTolerance && domainMargin > 0;
    energy = NaN;
    if accepted
        energy = trial_energy(C2,Jmodes,modeWeights, ...
            frequencyWeights,beta,Dq,R,Hcorrection);
    end
    attempts(k) = struct( ...
        'start_factor',startFactors(k), ...
        'initial_sigma',initialSigma, ...
        'exitflag',exitflag, ...
        'iterations',output.iterations, ...
        'function_count',output.funcCount, ...
        'residual_norm',residualNorm, ...
        'domain_margin',domainMargin, ...
        'accepted',accepted, ...
        'sigma',sigma, ...
        'R',R, ...
        'energy',energy);
    if ~accepted
        continue
    end
    duplicate = false;
    for j = 1:numel(roots)
        distance = norm((sigma-roots(j).sigma)/energyScale,inf);
        if distance <= rootTolerance
            duplicate = true;
            roots(j).start_factors(end+1) = startFactors(k);
            roots(j).max_cluster_distance = ...
                max(roots(j).max_cluster_distance,distance);
            break
        end
    end
    if ~duplicate
        root = empty_root(nmodes);
        root.sigma = sigma;
        root.R = R;
        root.Dq = Dq;
        root.residual_norm = residualNorm;
        root.domain_margin = domainMargin;
        root.energy = energy;
        root.start_factors = startFactors(k);
        root.max_cluster_distance = 0;
        roots(end+1,1) = root; %#ok<AGROW>
    end
end

selected = [];
selectionStatus = 'no_stationary_root';
if ~isempty(roots)
    energies = [roots.energy];
    minimumEnergy = min(energies);
    energyTieTolerance = energyAbsoluteTolerance+ ...
        energyRelativeTolerance*max(1,abs(minimumEnergy));
    tied = find(abs(energies-minimumEnergy) <= energyTieTolerance);
    if isscalar(tied)
        selected = roots(tied);
        selectionStatus = 'selected_among_discovered_roots';
    else
        selectionStatus = 'degenerate_discovered_minima';
        selected = roots(tied);
    end
end

out = struct( ...
    'schema','invzf_bilocal_quadratic_medium/v1', ...
    'status',selectionStatus, ...
    'kernel_schema',kernel.schema, ...
    'C2',C2, ...
    'beta',beta, ...
    'Jmin',min(Jmodes), ...
    'Jmax',max(Jmodes), ...
    'mode_weights',modeWeights, ...
    'frequency_weights',frequencyWeights, ...
    'energy_scale',energyScale, ...
    'positive_domain_lower_bound',lowerBound, ...
    'H_correction',Hcorrection, ...
    'self_energy_map',selfEnergyMap, ...
    'effective_config',struct( ...
        'start_factors',startFactors, ...
        'residual_tolerance',residualTolerance, ...
        'root_tolerance',rootTolerance, ...
        'energy_absolute_tolerance',energyAbsoluteTolerance, ...
        'energy_relative_tolerance',energyRelativeTolerance, ...
        'max_iterations',maxIterations, ...
        'max_evaluations',maxEvaluations, ...
        'domain_coordinate','Sigma_n=Jmax-1/C2_n+exp(y_n)'), ...
    'attempts',attempts, ...
    'roots',roots, ...
    'selected',selected, ...
    'root_count',numel(roots), ...
    'c3_zero_input_only',true, ...
    'symmetry_provenance_certified',false, ...
    'enumeration_complete',false, ...
    'matsubara_tail_complete',false, ...
    'nonlinear_local_legendre_complete',false, ...
    'functional_use_authorized',false);
end

function residual = scaled_residual(y,lowerBound,C2,Jmodes, ...
        modeWeights,selfEnergyMap,energyScale)
sigma = lowerBound+exp(y);
[residual,~,~,~] = evaluate_residual( ...
    sigma,C2,Jmodes,modeWeights,selfEnergyMap,energyScale);
end

function [residual,R,Dq,denominator] = evaluate_residual( ...
        sigma,C2,Jmodes,modeWeights,selfEnergyMap,energyScale)
denominator = 1./C2.'-Jmodes+sigma.';
Dq = 1./denominator;
Dlocal = (modeWeights.'*Dq).';
R = Dlocal-C2;
residual = (sigma-selfEnergyMap*R)/energyScale;
end

function energy = trial_energy(C2,Jmodes,modeWeights, ...
        frequencyWeights,beta,Dq,R,Hcorrection)
denominatorBare = 1./C2.'-Jmodes;
traceIntegrand = log(C2.'./Dq)+denominatorBare.*Dq-1 ...
    +Jmodes.*C2.';
weightedQ = modeWeights.'*traceIntegrand;
traceEnergy = sum(frequencyWeights.'.*weightedQ)/(2*beta);
localCorrection = (R.'*Hcorrection*R)/2;
energy = real(traceEnergy+localCorrection);
end

function root = empty_root(nmodes)
root = struct( ...
    'sigma',nan(nmodes,1), ...
    'R',nan(nmodes,1), ...
    'Dq',nan(0,nmodes), ...
    'residual_norm',NaN, ...
    'domain_margin',NaN, ...
    'energy',NaN, ...
    'start_factors',nan(1,0), ...
    'max_cluster_distance',NaN);
end

function attempt = empty_attempt(nmodes)
attempt = struct( ...
    'start_factor',NaN, ...
    'initial_sigma',nan(nmodes,1), ...
    'exitflag',NaN, ...
    'iterations',NaN, ...
    'function_count',NaN, ...
    'residual_norm',NaN, ...
    'domain_margin',NaN, ...
    'accepted',false, ...
    'sigma',nan(nmodes,1), ...
    'R',nan(nmodes,1), ...
    'energy',NaN);
end

function value = get_opt(opts,name,default)
if isfield(opts,name) && ~isempty(opts.(name))
    value = opts.(name);
else
    value = default;
end
end
