function result = invzp_hybrid_functional_consistency_audit()
%INVZP_HYBRID_FUNCTIONAL_CONSISTENCY_AUDIT Audit Jensen's same-ion premise.
% Diagnostic only.  Jensen 2.24--2.34 derives the tadpole cancellation,
% response ratio, and field/free-energy test from one two-level single-ion
% Hamiltonian.  Production combines a 136-state electronuclear moment/G0
% with an electronic two-level ordered vertex and elastic factor.  Measure
% that producer mismatch on exact roots; do not infer a functional merely
% from small residuals of the hybrid closure itself.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));

F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
S = load(fullfile(here,'wp2_multifield_sheet_section_audit.mat'));
C = load(fullfile(here,'wp2_multifield_crossfield_continuation.mat'));
T = S.result.T;
Jsup = F.info.Jcc0;
Bx_values = [0.5,0.8,0.9,1.1,1.2,2.5,2.9];
records = repmat(empty_record(),0,1);

for ib = 1:numel(Bx_values)
    Bx = Bx_values(ib);
    isource = find(abs([S.result.sections.Bx]-Bx) <= 1e-12,1);
    source = S.result.sections(isource);
    [~,ilow] = min([source.roots.s]);
    states = struct('sheet',"low",'y',source.roots(ilow).y(:));
    icross = find(abs([C.result.anchor_summary.Bx]-Bx) <= 1e-12,1);
    if ~isempty(icross) && C.result.anchor_summary(icross).reached
        states(2) = struct('sheet',"high", ... %#ok<AGROW>
            'y',C.result.anchor_summary(icross).high.y(:));
    end
    bare = bare_audit(Bx,source.h,T,F);
    ctx = make_context(Bx,source.h,T,F);
    for is = 1:numel(states)
        q = invz_ordered_reduced_residual(states(is).y,ctx, ...
            struct('Jsup',Jsup,'dynamic',struct('resid_tol',1e-12)));
        tl = ctx.tl;
        G0i_two = -tl.M2*tl.g0;
        G0e_two = -tl.m^2*tl.h0;
        [Gstat_two,go_two] = invz_gstat_ordered(tl,q.lambda,q.K(1), ...
            q.Sigma(1),ctx.beta,G0i_two,G0e_two, ...
            struct('stable_form',true));
        closed_static_residual = q.Phi-Gstat_two;
        closed_x_residual = q.x-go_two.Gtil0;
        rec = struct('Bx',Bx,'h',source.h,'sheet',states(is).sheet, ...
            's',-Jsup*q.x,'hybrid_residual_norm',q.residual_norm, ...
            'full_moment',bare.full_moment, ...
            'twolevel_moment',bare.twolevel_moment, ...
            'moment_difference',bare.moment_difference, ...
            'full_G0bare',bare.full_G0bare, ...
            'electronic_G0bare',bare.electronic_G0bare, ...
            'twolevel_G0bare',bare.twolevel_G0bare, ...
            'full_to_twolevel_G0_ratio',bare.full_to_twolevel_G0_ratio, ...
            'full_derivative_relative_error', ...
            bare.full_derivative_relative_error, ...
            'electronic_derivative_relative_error', ...
            bare.electronic_derivative_relative_error, ...
            'hybrid_Gstat',q.Gstat,'twolevel_Gstat',Gstat_two, ...
            'Gstat_relative_difference', ...
            abs(q.Gstat-Gstat_two)/max(abs(q.Gstat),eps), ...
            'hybrid_r',q.r,'twolevel_r_same_vertex',go_two.r, ...
            'r_difference',q.r-go_two.r, ...
            'closed_static_residual',closed_static_residual, ...
            'closed_x_residual',closed_x_residual, ...
            'closed_static_scaled_by_full', ...
            abs(closed_static_residual)/max(abs(q.Phi),eps), ...
            'closed_x_scaled_by_full', ...
            abs(closed_x_residual)/max(abs(q.x),eps));
        records(end+1,1) = rec; %#ok<AGROW>
        fprintf(['hybrid consistency Bx %.3g %s: s %.9g, ' ...
            'G0full/G0two %.6g, dm err %.3g, ' ...
            'dGstat %.3g, closed R/Phi %.3g\n'], ...
            Bx,states(is).sheet,-Jsup*q.x,bare.full_to_twolevel_G0_ratio, ...
            bare.full_derivative_relative_error, ...
            rec.Gstat_relative_difference, ...
            rec.closed_static_scaled_by_full);
    end
end

result = struct('T',T,'Jsup',Jsup,'Bx_values',Bx_values, ...
    'records',records, ...
    'max_full_derivative_relative_error', ...
    max([records.full_derivative_relative_error]), ...
    'max_electronic_derivative_relative_error', ...
    max([records.electronic_derivative_relative_error]), ...
    'G0_ratio_range', ...
    [min([records.full_to_twolevel_G0_ratio]), ...
     max([records.full_to_twolevel_G0_ratio])], ...
    'moment_difference_range', ...
    [min([records.moment_difference]),max([records.moment_difference])], ...
    'Gstat_relative_difference_range', ...
    [min([records.Gstat_relative_difference]), ...
     max([records.Gstat_relative_difference])], ...
    'closed_static_scaled_range', ...
    [min([records.closed_static_scaled_by_full]), ...
     max([records.closed_static_scaled_by_full])], ...
    'interpretation',['The small full-ion derivative error verifies the ' ...
    'bare response producer. Nonzero moment/G0/static-closure differences ' ...
    'show that the electronic two-level vertex is not the cumulant vertex ' ...
    'of that same producer. Therefore Jensen 2.24--2.34 cannot be transferred ' ...
    'as an exact thermodynamic identity without a derived multilevel or ' ...
    'mixed functional. This audit does not prove that no alternative ' ...
    'functional can be constructed.']);
save(fullfile(here,'wp2_hybrid_functional_consistency_audit.mat'), ...
    'result','-v7');
fprintf(['hybrid consistency summary: dm errors full/electronic %.3g %.3g, ' ...
    'G0 ratio [%.6g %.6g], dGstat [%.3g %.3g], closed R/Phi [%.3g %.3g]\n'], ...
    result.max_full_derivative_relative_error, ...
    result.max_electronic_derivative_relative_error, ...
    result.G0_ratio_range,result.Gstat_relative_difference_range, ...
    result.closed_static_scaled_range);
end

function out = bare_audit(Bx,h,T,F)
ion = invz_ion();
dh = max(2e-7,2e-4*h);
full = single_state(ion,T,Bx,h,true,F.info.Jaa0);
electronic = single_state(ion,T,Bx,h,false,F.info.Jaa0);
full_plus = single_state(ion,T,Bx,h+dh,true,F.info.Jaa0);
full_minus = single_state(ion,T,Bx,h-dh,true,F.info.Jaa0);
electronic_plus = single_state(ion,T,Bx,h+dh,false,F.info.Jaa0);
electronic_minus = single_state(ion,T,Bx,h-dh,false,F.info.Jaa0);
full_derivative = (full_plus.moment-full_minus.moment)/(2*dh);
electronic_derivative = ...
    (electronic_plus.moment-electronic_minus.moment)/(2*dh);
tl = invz_twolevel_ordered(ion,T,Bx,h,struct('Jxx0',F.info.Jaa0));
twolevel_moment = tl.m*tl.n01;
twolevel_G0bare = -tl.M2*tl.g0-tl.m^2*tl.h0;
out = struct('dh',dh,'full_moment',full.moment, ...
    'electronic_moment',electronic.moment, ...
    'twolevel_moment',twolevel_moment, ...
    'moment_difference',full.moment-twolevel_moment, ...
    'full_G0bare',full.G0bare, ...
    'electronic_G0bare',electronic.G0bare, ...
    'twolevel_G0bare',twolevel_G0bare, ...
    'full_to_twolevel_G0_ratio',full.G0bare/twolevel_G0bare, ...
    'full_derivative',full_derivative, ...
    'electronic_derivative',electronic_derivative, ...
    'full_derivative_relative_error', ...
    abs(full_derivative+full.G0bare)/max(abs(full.G0bare),eps), ...
    'electronic_derivative_relative_error', ...
    abs(electronic_derivative+electronic.G0bare)/ ...
        max(abs(electronic.G0bare),eps));
end

function out = single_state(ion,T,Bx,h,hyp,Jaa0)
si = invz_single_ion(ion,T,[Bx 0 0], ...
    struct('hyp',hyp,'Jxx0',Jaa0,'hz_fixed',h));
c0 = invz_chi0z(si,T,0,struct('elastic',true));
X = real(c0(:,:,1));
feedback = X(3,1)*(Jaa0/(1-Jaa0*X(1,1)))*X(1,3);
out = struct('moment',si.Jexp(3), ...
    'G0bare',-(X(3,3)+feedback));
end

function ctx = make_context(Bx,h,T,F)
ion = invz_ion();
[wn,wts,beta] = invz_matsubara(T,40);
si = invz_single_ion(ion,T,[Bx 0 0], ...
    struct('hyp',true,'Jxx0',F.info.Jaa0,'hz_fixed',h));
tl = invz_twolevel_ordered(ion,T,Bx,h,struct('Jxx0',F.info.Jaa0));
c0 = invz_chi0z(si,T,1i*wn,struct('elastic',true));
G0 = -real(squeeze(c0(3,3,:)));
c0i = invz_chi0z(si,T,1i*wn(1),struct('elastic',false));
G0i = -real(c0i(3,3,1));
X = real(c0(:,:,1));
feedback = X(3,1)*(F.info.Jaa0/(1-F.info.Jaa0*X(1,1)))*X(1,3);
G0e = -(X(3,3)+feedback)-G0i;
g = real(invz_g(tl,1i*wn));
ctx = struct('G0',G0,'g',g,'tl',tl,'wts',wts,'beta',beta, ...
    'Jnu_flat',F.J,'J0eff',F.info.Jcc0, ...
    'G0inel0',G0i,'G0el0',G0e);
end

function r = empty_record()
r = struct('Bx',NaN,'h',NaN,'sheet',"",'s',NaN, ...
    'hybrid_residual_norm',NaN,'full_moment',NaN, ...
    'twolevel_moment',NaN,'moment_difference',NaN, ...
    'full_G0bare',NaN,'electronic_G0bare',NaN, ...
    'twolevel_G0bare',NaN,'full_to_twolevel_G0_ratio',NaN, ...
    'full_derivative_relative_error',NaN, ...
    'electronic_derivative_relative_error',NaN, ...
    'hybrid_Gstat',NaN,'twolevel_Gstat',NaN, ...
    'Gstat_relative_difference',NaN,'hybrid_r',NaN, ...
    'twolevel_r_same_vertex',NaN,'r_difference',NaN, ...
    'closed_static_residual',NaN,'closed_x_residual',NaN, ...
    'closed_static_scaled_by_full',NaN,'closed_x_scaled_by_full',NaN);
end
