function result = invzp_local_field_potential_extension()
%INVZP_LOCAL_FIELD_POTENTIAL_EXTENSION Extend the fold-anchored comparison.
% Diagnostic only.  Reuse the fixed-h paired audit through h=0.006, then use
% the independently pseudo-arclength-corrected return-sheet states above
% h=0.006 and solve only their low-sheet counterparts.  This supplies an
% alternative state-construction route and tests whether the local potential
% ordering reverses before the return sheet reaches s=1.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));

F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
L = load(fullfile(here,'wp2_local_field_potential_audit.mat'));
P = load(fullfile(here,'wp2_reduced_pseudoarclength_1t.mat'));
T = L.result.T;
Bx = L.result.Bx;
Jsup = L.result.Jsup;
pa = P.result.points;
ipa = find([pa.h].' > L.result.hmax & (1:numel(pa)).' >= 17);
assert(~isempty(ipa) && all(diff([pa(ipa).h]) > 0));
lsopts = optimoptions('lsqnonlin','Display','off', ...
    'FunctionTolerance',1e-18,'StepTolerance',2e-13, ...
    'OptimalityTolerance',2e-11,'MaxIterations',24, ...
    'MaxFunctionEvaluations',150,'FiniteDifferenceType','forward', ...
    'FiniteDifferenceStepSize',3e-6);

yprev = L.result.branches(1).records(end).y;
extension = repmat(empty_record(),numel(ipa),1);
for k = 1:numel(ipa)
    pp = pa(ipa(k));
    ctx = make_context(Bx,pp.h,T,F);
    [low,yroot] = solve_low_fixed_h(yprev,ctx,Jsup,lsopts);
    qhigh = invz_ordered_reduced_residual(pp.y,ctx, ...
        struct('Jsup',Jsup,'dynamic',struct('resid_tol',1e-12)));
    high_ok = qhigh.defined && qhigh.trial_admissible && ...
        qhigh.residual_norm <= 2e-8;
    extension(k) = struct('h',pp.h,'moment',ctx.moment, ...
        'G0bare',qhigh.static.G0bare,'low',low, ...
        'high_y',pp.y,'high_s',pp.s,'high_r',qhigh.r, ...
        'high_residual_norm',qhigh.residual_norm, ...
        'high_accepted',high_ok,'high_supremum_mass', ...
        qhigh.supremum_mass,'high_uniform_mass',qhigh.D_uni, ...
        'high_static_mesh_mass',qhigh.static_mesh_min_mass, ...
        'high_dynamic_lattice_mass', ...
        qhigh.dynamic.dynamic_min_lattice_mass, ...
        'high_dynamic_medium_mass', ...
        qhigh.dynamic.dynamic_min_medium_mass);
    fprintf(['local extension h %.12g: slow %.9g shigh %.9g, ' ...
        'r %.9g/%.9g, R %.3g/%.3g, ok %d/%d\n'],pp.h, ...
        low.z(4),pp.s,low.r,qhigh.r,low.physical_residual_norm, ...
        qhigh.residual_norm,low.accepted,high_ok);
    assert(low.accepted && high_ok);
    yprev = yroot;
end

hgrid = [L.result.hgrid;[extension.h].'];
low_records = [extension.low];
rlo = [L.result.r_low;[low_records.r].'];
rhi = [L.result.r_high;[extension.high_r].'];
moment = [L.result.moment;[extension.moment].'];
G0bare = [L.result.G0bare;[extension.G0bare].'];
delta_r = rhi-rlo;
delta_h_relative = cumtrapz(hgrid,delta_r);
mprime = -G0bare;
phi_nested = cumtrapz(hgrid,mprime.*delta_h_relative);
phi_single = zeros(size(hgrid));
for k = 2:numel(hgrid)
    phi_single(k) = trapz(hgrid(1:k), ...
        delta_r(1:k).*(moment(k)-moment(1:k)));
end
identity_error = max(abs(phi_nested-phi_single));

% Deliberately drop alternate extension nodes but retain the dense fold
% segment and exact terminal point.
nbase = numel(L.result.hgrid);
coarse_ix = unique([1:nbase,(nbase+2):2:numel(hgrid),numel(hgrid)]);
phi_terminal_coarse = trapz(hgrid(coarse_ix), ...
    delta_r(coarse_ix).*(moment(end)-moment(coarse_ix)));
quadrature_change = abs(phi_single(end)-phi_terminal_coarse);
cross = find(phi_single(2:end-1).*phi_single(3:end) < 0,1,'first')+1;
if isempty(cross)
    crossing_bracket = [NaN NaN];
else
    crossing_bracket = hgrid([cross,cross+1]).';
end
dm_numeric = gradient(moment,hgrid);
dm_relerr = max(abs(dm_numeric(2:end-1)-mprime(2:end-1))./ ...
    max(abs(mprime(2:end-1)),1e-12));

result = struct('T',T,'Bx',Bx,'Jsup',Jsup,'pa_indices',ipa, ...
    'extension',extension,'hgrid',hgrid,'r_low',rlo,'r_high',rhi, ...
    'delta_r',delta_r,'moment',moment,'G0bare',G0bare, ...
    'delta_h_high_minus_low',delta_h_relative, ...
    'delta_phi_high_minus_low_nested',phi_nested, ...
    'delta_phi_high_minus_low_single',phi_single, ...
    'terminal_delta_phi',phi_single(end), ...
    'nested_single_max_difference',identity_error, ...
    'terminal_delta_phi_coarse',phi_terminal_coarse, ...
    'quadrature_coarsening_change',quadrature_change, ...
    'crossing_bracket',crossing_bracket, ...
    'moment_derivative_relative_error',dm_relerr, ...
    'minimum_high_masses',[min([extension.high_supremum_mass]), ...
        min([extension.high_uniform_mass]), ...
        min([extension.high_static_mesh_mass]), ...
        min([extension.high_dynamic_lattice_mass]), ...
        min([extension.high_dynamic_medium_mass])], ...
    'source_local',fullfile(here,'wp2_local_field_potential_audit.mat'), ...
    'source_arclength',fullfile(here, ...
        'wp2_reduced_pseudoarclength_1t.mat'), ...
    'interpretation',['No finite-h crossing means the return sheet stays ' ...
        'below the low sheet in the fold-anchored Jensen constrained ' ...
        'potential until its uniform stability boundary. This remains ' ...
        'conditional on the field/free-energy differential identities for ' ...
        'the hybrid closure.']);
save(fullfile(here,'wp2_local_field_potential_extension.mat'), ...
    'result','-v7');
fprintf(['local extension terminal h %.12g: Phi_high-Phi_low %.12g ' ...
    'meV, crossing [%.9g %.9g], identity %.3g, coarse %.3g, ' ...
    'min high masses [%.3g %.3g %.3g %.3g %.3g]\n'],hgrid(end), ...
    phi_single(end),crossing_bracket,identity_error,quadrature_change, ...
    result.minimum_high_masses);
end

function [rec,yroot] = solve_low_fixed_h(yprev,ctx,Jsup,lsopts)
[lo,hi] = lambda_bounds(ctx);
mid = (lo+hi)/2;
half = (hi-lo)/2;
zstart = [(yprev(1:3)-mid)./half;-Jsup*yprev(4)];
lb = [-ones(3,1)+1e-9;1e-8];
ub = [ ones(3,1)-1e-9;1-1e-8];
[z,resnorm,rscaled,exitflag,output] = lsqnonlin( ...
    @scaled_vector,zstart,lb,ub,lsopts);
yroot = [mid+half.*z(1:3);-z(4)/Jsup];
qroot = invz_ordered_reduced_residual(yroot,ctx, ...
    struct('Jsup',Jsup,'dynamic',struct('resid_tol',1e-12)));
accepted = exitflag > 0 && qroot.defined && qroot.trial_admissible && ...
    qroot.residual_norm <= 2e-8 && max(abs(rscaled)) <= 2e-8;
rec = struct('z',z,'y',yroot,'r',qroot.r,'resnorm',resnorm, ...
    'scaled_residual_norm',max(abs(rscaled)), ...
    'physical_residual_norm',qroot.residual_norm,'exitflag',exitflag, ...
    'output',output,'accepted',accepted, ...
    'supremum_mass',qroot.supremum_mass,'uniform_mass',qroot.D_uni, ...
    'static_mesh_mass',qroot.static_mesh_min_mass, ...
    'dynamic_lattice_mass',qroot.dynamic.dynamic_min_lattice_mass, ...
    'dynamic_medium_mass',qroot.dynamic.dynamic_min_medium_mass);

    function rr = scaled_vector(zz)
        ytrial = [mid+half.*zz(1:3);-zz(4)/Jsup];
        qtrial = invz_ordered_reduced_residual(ytrial,ctx, ...
            struct('Jsup',Jsup, ...
            'dynamic',struct('resid_tol',1e-12)));
        if qtrial.defined && all(isfinite(qtrial.residual))
            rr = [qtrial.lambda_residual./half; ...
                Jsup*qtrial.static_residual];
        else
            rr = 1e3*(1+abs(zz));
        end
    end
end

function [lo,hi] = lambda_bounds(ctx)
nw = numel(ctx.g);
if isvector(ctx.Jnu_flat)
    jlo = repmat(min(ctx.Jnu_flat),nw,1);
    jhi = repmat(max(ctx.Jnu_flat),nw,1);
else
    jlo = min(ctx.Jnu_flat,[],1).';
    jhi = max(ctx.Jnu_flat,[],1).';
end
lo = nan(3,1);
hi = nan(3,1);
for p = 1:3
    a = ctx.wts(:).*ctx.g(:).^p/ctx.beta;
    lo(p) = sum(min(a.*jlo,a.*jhi));
    hi(p) = sum(max(a.*jlo,a.*jhi));
end
end

function ctx = make_context(Bx,h,T,F)
ion = invz_ion();
[wn,wts,beta] = invz_matsubara(T,40);
si = invz_single_ion(ion,T,[Bx 0 0], ...
    struct('hyp',true,'Jxx0',F.info.Jaa0,'hz_fixed',h));
tl = invz_twolevel_ordered(ion,T,Bx,h,struct('Jxx0',F.info.Jaa0));
c0 = invz_chi0z(si,T,1i*wn,struct('elastic',true));
G0 = -real(squeeze(c0(3,3,:)));
c0i = invz_chi0z(si,T,1i*wn(1),struct('elastic',false));
G0i = -real(c0i(3,3,1));
X = real(c0(:,:,1));
feedback = X(3,1)*(F.info.Jaa0/(1-F.info.Jaa0*X(1,1)))*X(1,3);
G0e = -(X(3,3)+feedback)-G0i;
g = real(invz_g(tl,1i*wn));
ctx = struct('G0',G0,'g',g,'tl',tl,'wts',wts,'beta',beta, ...
    'Jnu_flat',F.J,'J0eff',F.info.Jcc0, ...
    'G0inel0',G0i,'G0el0',G0e,'moment',si.Jexp(3));
end

function r = empty_record()
r = struct('h',NaN,'moment',NaN,'G0bare',NaN,'low',struct(), ...
    'high_y',nan(4,1),'high_s',NaN,'high_r',NaN, ...
    'high_residual_norm',NaN,'high_accepted',false, ...
    'high_supremum_mass',NaN,'high_uniform_mass',NaN, ...
    'high_static_mesh_mass',NaN,'high_dynamic_lattice_mass',NaN, ...
    'high_dynamic_medium_mass',NaN);
end
