function result = invzp_highfield_exact_section_audit()
%INVZP_HIGHFIELD_EXACT_SECTION_AUDIT Strengthen the 2.5--2.9 T check.
% Diagnostic only.  Re-evaluate the converged full-Sigma section states
% with the exact reduced equations, extend the fixed-s moment solution to
% s=1-1e-6, and launch constrained full-residual correctors above the known
% root.  Failure of these finite searches is evidence, not an interval proof.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));

F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
S = load(fullfile(here,'wp2_multifield_sheet_section_audit.mat'));
T = S.result.T;
Jsup = F.info.Jcc0;
target_fields = [2.5,2.7,2.9];
ls3 = optimoptions('lsqnonlin','Display','off', ...
    'FunctionTolerance',1e-20,'StepTolerance',2e-13, ...
    'OptimalityTolerance',2e-11,'MaxIterations',35, ...
    'MaxFunctionEvaluations',260,'FiniteDifferenceType','forward', ...
    'FiniteDifferenceStepSize',3e-6);
ls4 = ls3;
audits = repmat(empty_audit(),numel(target_fields),1);

for ib = 1:numel(target_fields)
    Bx = target_fields(ib);
    source_index = find(abs([S.result.sections.Bx]-Bx) <= 1e-12,1);
    assert(~isempty(source_index));
    source = S.result.sections(source_index);
    ctx = make_context(Bx,source.h,T,F);
    [lo,hi] = lambda_bounds(ctx);
    mid = (lo+hi)/2;
    half = (hi-lo)/2;
    ropts = struct('Jsup',Jsup,'dynamic',struct('resid_tol',1e-12));

    profile = repmat(empty_profile(),numel(source.profile),1);
    for k = 1:numel(source.profile)
        p = source.profile(k);
        q = invz_ordered_reduced_residual( ...
            [p.lambda(:);-p.s/Jsup],ctx,ropts);
        profile(k) = struct('s',p.s,'source_converged',p.converged, ...
            'defined',q.defined,'lambda_residual_norm', ...
            max(abs(q.lambda_residual)),'static_residual', ...
            q.static_residual,'r',q.r,'admissible',q.trial_admissible);
    end

    endpoint_s = [0.9999,0.99999,0.999999].';
    endpoint = repmat(empty_profile(),numel(endpoint_s),1);
    zseed = (source.profile(end).lambda(:)-mid)./half;
    for k = 1:numel(endpoint_s)
        s = endpoint_s(k);
        [z,~,rscaled,exitflag] = lsqnonlin( ...
            @(zz) moment_vector(zz,s,ctx,mid,half,Jsup,ropts), ...
            zseed,-ones(3,1)+1e-9,ones(3,1)-1e-9,ls3);
        q = invz_ordered_reduced_residual( ...
            [mid+half.*z;-s/Jsup],ctx,ropts);
        accepted = exitflag > 0 && q.defined && q.trial_admissible && ...
            max(abs(rscaled)) <= 1e-8 && ...
            max(abs(q.lambda_residual)) <= 1e-8;
        endpoint(k) = struct('s',s,'source_converged',false, ...
            'defined',q.defined,'lambda_residual_norm', ...
            max(abs(q.lambda_residual)),'static_residual', ...
            q.static_residual,'r',q.r,'admissible',accepted);
        if accepted, zseed = z; end
    end

    known_s = source.roots(1).s;
    search_floor = known_s+0.015;
    seed_s = [0.85,0.9,0.95,0.99,0.999];
    trials = repmat(empty_trial(),numel(seed_s),1);
    for k = 1:numel(seed_s)
        [~,ip] = min(abs([source.profile.s]-seed_s(k)));
        p = source.profile(ip);
        zseed4 = [(p.lambda(:)-mid)./half;p.s];
        lb = [-ones(3,1)+1e-9;search_floor];
        ub = [ ones(3,1)-1e-9;1-1e-8];
        zseed4 = min(max(zseed4,lb),ub);
        [z,~,rscaled,exitflag] = lsqnonlin( ...
            @(zz) full_vector(zz,ctx,mid,half,Jsup,ropts), ...
            zseed4,lb,ub,ls4);
        y = [mid+half.*z(1:3);-z(4)/Jsup];
        q = invz_ordered_reduced_residual(y,ctx,ropts);
        if q.defined
            outer = invz_ordered_outer_map(q.Sigma,ctx, ...
                struct('emt_static', ...
                struct('Jsup',Jsup,'warn',false)));
            outer_norm = outer.residual_norm;
        else
            outer_norm = Inf;
        end
        accepted = exitflag > 0 && q.defined && ...
            q.trial_admissible && q.residual_norm <= 1e-8 && ...
            max(abs(rscaled)) <= 1e-8 && outer_norm <= 1e-8;
        trials(k) = struct('seed_s',seed_s(k),'solution_s',z(4), ...
            'residual_norm',q.residual_norm,'scaled_residual_norm', ...
            max(abs(rscaled)),'outer_residual_norm',outer_norm, ...
            'accepted',accepted,'exitflag',exitflag, ...
            'status',string(q.status));
    end

    accepted_trial_count = sum([trials.accepted]);
    audits(ib) = struct('Bx',Bx,'h',source.h,'known_root_s',known_s, ...
        'profile',profile,'endpoint',endpoint,'trials',trials, ...
        'search_floor',search_floor, ...
        'max_profile_lambda_residual', ...
        max([profile.lambda_residual_norm]), ...
        'postroot_static_max', ...
        max([profile([profile.s] > known_s).static_residual]), ...
        'endpoint_static_max',max([endpoint.static_residual]), ...
        'endpoint_all_accepted',all([endpoint.admissible]), ...
        'accepted_high_root_trials',accepted_trial_count, ...
        'best_constrained_residual',min([trials.residual_norm]));
    fprintf(['highfield Bx %.3g: endpoint Rstatic max %.9g, ' ...
        'high-root trials %d, best R %.3g\n'],Bx, ...
        audits(ib).endpoint_static_max,accepted_trial_count, ...
        audits(ib).best_constrained_residual);
end

result = struct('T',T,'Jsup',Jsup,'target_fields',target_fields, ...
    'audits',audits, ...
    'all_endpoint_states_accepted',all([audits.endpoint_all_accepted]), ...
    'any_constrained_high_root', ...
    any([audits.accepted_high_root_trials] > 0), ...
    'source',fullfile(here,'wp2_multifield_sheet_section_audit.mat'), ...
    'interpretation',['At 2.5--2.9 T the exact moment branch remains ' ...
    'defined to s=1-1e-6 with negative post-root static residual. ' ...
    'Constrained full-residual multistart searches for another high-s ' ...
    'root. A null search is strong finite evidence, not a uniqueness proof ' ...
    'over every possible disconnected moment branch.']);
save(fullfile(here,'wp2_highfield_exact_section_audit.mat'), ...
    'result','-v7');
end

function rr = moment_vector(z,s,ctx,mid,half,Jsup,ropts)
q = invz_ordered_reduced_residual( ...
    [mid+half.*z;-s/Jsup],ctx,ropts);
if q.defined && all(isfinite(q.lambda_residual))
    rr = q.lambda_residual./half;
else
    rr = 1e3*(1+abs(z));
end
end

function rr = full_vector(z,ctx,mid,half,Jsup,ropts)
q = invz_ordered_reduced_residual( ...
    [mid+half.*z(1:3);-z(4)/Jsup],ctx,ropts);
if q.defined && all(isfinite(q.residual))
    rr = [q.lambda_residual./half;Jsup*q.static_residual];
else
    rr = 1e3*(1+abs(z));
end
end

function [lo,hi] = lambda_bounds(ctx)
nw = numel(ctx.g);
if isvector(ctx.Jnu_flat)
    jlo = repmat(min(ctx.Jnu_flat),nw,1);
    jhi = repmat(max(ctx.Jnu_flat),nw,1);
else
    jlo = min(ctx.Jnu_flat,[],1).';
    jhi = max(ctx.Jnu_flat,[],1).';
end
lo = nan(3,1);
hi = nan(3,1);
for p = 1:3
    a = ctx.wts(:).*ctx.g(:).^p/ctx.beta;
    lo(p) = sum(min(a.*jlo,a.*jhi));
    hi(p) = sum(max(a.*jlo,a.*jhi));
end
end

function ctx = make_context(Bx,h,T,F)
ion = invz_ion();
[wn,wts,beta] = invz_matsubara(T,40);
si = invz_single_ion(ion,T,[Bx 0 0], ...
    struct('hyp',true,'Jxx0',F.info.Jaa0,'hz_fixed',h));
tl = invz_twolevel_ordered(ion,T,Bx,h,struct('Jxx0',F.info.Jaa0));
c0 = invz_chi0z(si,T,1i*wn,struct('elastic',true));
G0 = -real(squeeze(c0(3,3,:)));
c0i = invz_chi0z(si,T,1i*wn(1),struct('elastic',false));
G0i = -real(c0i(3,3,1));
X = real(c0(:,:,1));
feedback = X(3,1)*(F.info.Jaa0/(1-F.info.Jaa0*X(1,1)))*X(1,3);
G0e = -(X(3,3)+feedback)-G0i;
g = real(invz_g(tl,1i*wn));
ctx = struct('G0',G0,'g',g,'tl',tl,'wts',wts,'beta',beta, ...
    'Jnu_flat',F.J,'J0eff',F.info.Jcc0, ...
    'G0inel0',G0i,'G0el0',G0e);
end

function p = empty_profile()
p = struct('s',NaN,'source_converged',false,'defined',false, ...
    'lambda_residual_norm',NaN,'static_residual',NaN,'r',NaN, ...
    'admissible',false);
end

function t = empty_trial()
t = struct('seed_s',NaN,'solution_s',NaN,'residual_norm',Inf, ...
    'scaled_residual_norm',Inf,'outer_residual_norm',Inf, ...
    'accepted',false,'exitflag',NaN,'status',"");
end

function a = empty_audit()
a = struct('Bx',NaN,'h',NaN,'known_root_s',NaN, ...
    'profile',repmat(empty_profile(),0,1), ...
    'endpoint',repmat(empty_profile(),0,1), ...
    'trials',repmat(empty_trial(),0,1),'search_floor',NaN, ...
    'max_profile_lambda_residual',NaN,'postroot_static_max',NaN, ...
    'endpoint_static_max',NaN,'endpoint_all_accepted',false, ...
    'accepted_high_root_trials',0,'best_constrained_residual',Inf);
end
