function result = invzp_local_field_potential_audit()
%INVZP_LOCAL_FIELD_POTENTIAL_AUDIT Relative potential of the two 1 T sheets.
% Diagnostic only.  The two roots at h=0.006 merge at the verified regular
% fold.  Jensen 2.33-2.34 imply, in energy-field units,
%
%   d(delta h)/dh = r-1,       d(delta Phi/N) = delta h dm.
%
% The unknown field-integration constant at the fold cancels between sheets
% because they share the same fold state and the same final single-ion moment.
% Therefore
%
%   Phi_H-Phi_L = integral_hf^h dm/dt *
%                   integral_hf^t (r_H-r_L) du dt
%               = integral_hf^h (r_H-r_L)[m(h)-m(u)] du.
%
% This is a local, common-fold comparison; it neither fills the missing
% h=0 area nor assumes a zero-coupling anchor for the return sheet.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));

F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
A = load(fullfile(here,'wp2_pseudoarclength_original_equations_audit.mat'));
R = load(fullfile(here,'wp2_reduced_fold_refinement.mat'));
T = A.result.T;
Bx = A.result.Bx;
hmax = A.result.hsection;
hfold = R.result.h;
Jsup = A.result.Jsup;
nt = 25;
t_desc = linspace(1,0.05,nt);
h_desc = hfold+(hmax-hfold)*t_desc.^2;
lsopts = optimoptions('lsqnonlin','Display','off', ...
    'FunctionTolerance',1e-18,'StepTolerance',2e-13, ...
    'OptimalityTolerance',2e-11,'MaxIterations',24, ...
    'MaxFunctionEvaluations',150,'FiniteDifferenceType','forward', ...
    'FiniteDifferenceStepSize',3e-6);
branches = repmat(struct('records',[]),2,1);

for ib = 1:2
    yprev = [A.result.roots(ib).lambda(:);A.result.roots(ib).x];
    recs_desc = repmat(empty_record(),numel(h_desc),1);
    for k = 1:numel(h_desc)
        h = h_desc(k);
        ctx = make_context(Bx,h,T,F);
        [recs_desc(k),yroot] = solve_fixed_h( ...
            yprev,ctx,Jsup,R.result.s,ib,lsopts);
        fprintf(['local field branch %d h %.12g: s %.9g r %.9g ' ...
            'R %.3g ok %d\n'],ib,h,recs_desc(k).z(4), ...
            recs_desc(k).r,recs_desc(k).physical_residual_norm, ...
            recs_desc(k).accepted);
        assert(recs_desc(k).accepted, ...
            'Branch %d failed at h %.15g.',ib,h);
        yprev = yroot;
    end

    ctxfold = make_context(Bx,hfold,T,F);
    qfold = invz_ordered_reduced_residual(R.result.fold.y,ctxfold, ...
        struct('Jsup',Jsup,'dynamic',struct('resid_tol',1e-12)));
    foldrec = struct('h',hfold,'z', ...
        [(R.result.fold.y(1:3)-mean_bounds(ctxfold))./ ...
        half_bounds(ctxfold);R.result.s], ...
        'y',R.result.fold.y,'r',qfold.r,'moment',ctxfold.moment, ...
        'G0bare',qfold.static.G0bare,'resnorm',0, ...
        'scaled_residual_norm',qfold.residual_norm, ...
        'physical_residual_norm',qfold.residual_norm,'exitflag',1, ...
        'output',struct('message','Independent refined fold.'), ...
        'accepted',qfold.defined && qfold.trial_admissible && ...
            qfold.residual_norm <= 2e-8, ...
        'supremum_mass',qfold.supremum_mass, ...
        'uniform_mass',qfold.D_uni,'static_mesh_mass', ...
        qfold.static_mesh_min_mass,'dynamic_lattice_mass', ...
        qfold.dynamic.dynamic_min_lattice_mass,'dynamic_medium_mass', ...
        qfold.dynamic.dynamic_min_medium_mass);
    assert(foldrec.accepted);
    branches(ib).records = [foldrec;flipud(recs_desc)];
end

hgrid = [branches(1).records.h].';
rlo = [branches(1).records.r].';
rhi = [branches(2).records.r].';
moment = [branches(1).records.moment].';
G0bare = [branches(1).records.G0bare].';
assert(max(abs(hgrid-[branches(2).records.h].')) < 1e-15);
assert(max(abs(moment-[branches(2).records.moment].')) < 1e-12);
delta_r = rhi-rlo;
delta_h_relative = cumtrapz(hgrid,delta_r);
mprime_exact = -G0bare;
delta_phi_nested = trapz(hgrid,mprime_exact.*delta_h_relative);
delta_phi_single = trapz(hgrid,delta_r.*(moment(end)-moment));

dm_numeric = gradient(moment,hgrid);
moment_derivative_relerr = max(abs(dm_numeric(2:end-1)- ...
    mprime_exact(2:end-1))./max(abs(mprime_exact(2:end-1)),1e-12));
delta_phi_numeric_dm = trapz(hgrid,dm_numeric.*delta_h_relative);
coarse_ix = unique([1:2:numel(hgrid),numel(hgrid)]);
delta_phi_coarse = trapz(hgrid(coarse_ix), ...
    delta_r(coarse_ix).*(moment(end)-moment(coarse_ix)));

result = struct('T',T,'Bx',Bx,'hfold',hfold,'hmax',hmax, ...
    'Jsup',Jsup,'branches',branches,'hgrid',hgrid,'r_low',rlo, ...
    'r_high',rhi,'delta_r',delta_r,'moment',moment, ...
    'G0bare',G0bare,'delta_h_high_minus_low',delta_h_relative, ...
    'delta_phi_high_minus_low_nested',delta_phi_nested, ...
    'delta_phi_high_minus_low_single',delta_phi_single, ...
    'delta_phi_numeric_dm',delta_phi_numeric_dm, ...
    'nested_single_difference',abs(delta_phi_nested-delta_phi_single), ...
    'moment_derivative_relative_error',moment_derivative_relerr, ...
    'delta_phi_coarse',delta_phi_coarse, ...
    'quadrature_coarsening_change', ...
    abs(delta_phi_single-delta_phi_coarse), ...
    'source_fold',fullfile(here,'wp2_reduced_fold_refinement.mat'), ...
    'source_roots',fullfile(here, ...
        'wp2_pseudoarclength_original_equations_audit.mat'), ...
    'interpretation',['Under Jensen 2.33-2.34, a negative value means ' ...
        'the return/high-s sheet has the lower local constrained potential ' ...
        'at hmax. The comparison cancels the unknown field-integration ' ...
        'constant but still assumes those thermodynamic differential ' ...
        'identities remain valid for the hybrid closure.']);
save(fullfile(here,'wp2_local_field_potential_audit.mat'),'result','-v7');
fprintf(['local field potential: Phi_high-Phi_low %.12g meV ' ...
    '(single %.12g, numeric-dm %.12g), identity %.3g, coarse %.3g, ' ...
    'dm/dh rel %.3g\n'],delta_phi_nested,delta_phi_single, ...
    delta_phi_numeric_dm,result.nested_single_difference, ...
    result.quadrature_coarsening_change,moment_derivative_relerr);
end

function [rec,yroot] = solve_fixed_h(yprev,ctx,Jsup,sfold,ib,lsopts)
[lo,hi] = lambda_bounds(ctx);
mid = (lo+hi)/2;
half = (hi-lo)/2;
zstart = [(yprev(1:3)-mid)./half;-Jsup*yprev(4)];
lb = [-ones(3,1)+1e-9;1e-8];
ub = [ ones(3,1)-1e-9;1-1e-8];
rstart = scaled_vector(zstart);
if max(abs(rstart)) <= 2e-8
    z = zstart;
    rscaled = rstart;
    resnorm = sum(rscaled.^2);
    exitflag = 1;
    output = struct('message','Accepted supplied exact root.');
else
    [z,resnorm,rscaled,exitflag,output] = lsqnonlin( ...
        @scaled_vector,zstart,lb,ub,lsopts);
end
yroot = [mid+half.*z(1:3);-z(4)/Jsup];
qroot = invz_ordered_reduced_residual(yroot,ctx, ...
    struct('Jsup',Jsup,'dynamic',struct('resid_tol',1e-12)));
side_ok = (ib == 1 && z(4) < sfold) || ...
    (ib == 2 && z(4) > sfold);
accepted = exitflag > 0 && qroot.defined && ...
    qroot.trial_admissible && qroot.residual_norm <= 2e-8 && ...
    max(abs(rscaled)) <= 2e-8 && side_ok;
rec = struct('h',ctx.tl.hz,'z',z,'y',yroot,'r',qroot.r, ...
    'moment',ctx.moment,'G0bare',qroot.static.G0bare, ...
    'resnorm',resnorm,'scaled_residual_norm',max(abs(rscaled)), ...
    'physical_residual_norm',qroot.residual_norm,'exitflag',exitflag, ...
    'output',output,'accepted',accepted, ...
    'supremum_mass',qroot.supremum_mass,'uniform_mass',qroot.D_uni, ...
    'static_mesh_mass',qroot.static_mesh_min_mass, ...
    'dynamic_lattice_mass',qroot.dynamic.dynamic_min_lattice_mass, ...
    'dynamic_medium_mass',qroot.dynamic.dynamic_min_medium_mass);

    function rr = scaled_vector(zz)
        ytrial = [mid+half.*zz(1:3);-zz(4)/Jsup];
        qtrial = invz_ordered_reduced_residual(ytrial,ctx, ...
            struct('Jsup',Jsup, ...
            'dynamic',struct('resid_tol',1e-12)));
        if qtrial.defined && all(isfinite(qtrial.residual))
            rr = [qtrial.lambda_residual./half; ...
                Jsup*qtrial.static_residual];
        else
            rr = 1e3*(1+abs(zz));
        end
    end
end

function mid = mean_bounds(ctx)
[lo,hi] = lambda_bounds(ctx);
mid = (lo+hi)/2;
end

function half = half_bounds(ctx)
[lo,hi] = lambda_bounds(ctx);
half = (hi-lo)/2;
end

function [lo,hi] = lambda_bounds(ctx)
nw = numel(ctx.g);
if isvector(ctx.Jnu_flat)
    jlo = repmat(min(ctx.Jnu_flat),nw,1);
    jhi = repmat(max(ctx.Jnu_flat),nw,1);
else
    jlo = min(ctx.Jnu_flat,[],1).';
    jhi = max(ctx.Jnu_flat,[],1).';
end
lo = nan(3,1);
hi = nan(3,1);
for p = 1:3
    a = ctx.wts(:).*ctx.g(:).^p/ctx.beta;
    lo(p) = sum(min(a.*jlo,a.*jhi));
    hi(p) = sum(max(a.*jlo,a.*jhi));
end
end

function ctx = make_context(Bx,h,T,F)
ion = invz_ion();
[wn,wts,beta] = invz_matsubara(T,40);
si = invz_single_ion(ion,T,[Bx 0 0], ...
    struct('hyp',true,'Jxx0',F.info.Jaa0,'hz_fixed',h));
tl = invz_twolevel_ordered(ion,T,Bx,h,struct('Jxx0',F.info.Jaa0));
c0 = invz_chi0z(si,T,1i*wn,struct('elastic',true));
G0 = -real(squeeze(c0(3,3,:)));
c0i = invz_chi0z(si,T,1i*wn(1),struct('elastic',false));
G0i = -real(c0i(3,3,1));
X = real(c0(:,:,1));
feedback = X(3,1)*(F.info.Jaa0/(1-F.info.Jaa0*X(1,1)))*X(1,3);
G0e = -(X(3,3)+feedback)-G0i;
g = real(invz_g(tl,1i*wn));
ctx = struct('G0',G0,'g',g,'tl',tl,'wts',wts,'beta',beta, ...
    'Jnu_flat',F.J,'J0eff',F.info.Jcc0, ...
    'G0inel0',G0i,'G0el0',G0e,'moment',si.Jexp(3));
end

function r = empty_record()
r = struct('h',NaN,'z',nan(4,1),'y',nan(4,1),'r',NaN, ...
    'moment',NaN,'G0bare',NaN,'resnorm',NaN, ...
    'scaled_residual_norm',NaN,'physical_residual_norm',NaN, ...
    'exitflag',NaN,'output',struct(),'accepted',false, ...
    'supremum_mass',NaN,'uniform_mass',NaN,'static_mesh_mass',NaN, ...
    'dynamic_lattice_mass',NaN,'dynamic_medium_mass',NaN);
end
