function invz_check_solve_opts(sxtra)
%INVZ_CHECK_SOLVE_OPTS Error if solve_opts sets a driver-owned field.
% Shared by invz_spectra_map/invz_spectra_qpath: J0eff/Jxx0/hyp are computed by
% the driver from the BZ coupling sum and must not be overridden via solve_opts.
if any(isfield(sxtra, {'J0eff', 'Jxx0', 'hyp', 'ordered_mode', ...
        'ordered_1z', 'forced_moment', 'transverse_mf', 'bz_tol', ...
        'odd_tier2', 'tier2', 'tol_tier2', 'max_tier2'}))
    error('invz:solveOpts', ...
          ['J0eff/Jxx0/hyp are driver-owned; ordered-mode and field-orientation ' ...
           'and removed Tier-2 options are not supported by the reduced projected solver.']);
end
end
