function [evidence,report] = invzp_fixed_w_event_evidence( ...
        Jq,fixedH,fixedW,endpointAnchor,spec)
%INVZP_FIXED_W_EVENT_EVIDENCE Diagnose scalar events on sampled fixed-w data.
%
%   This diagnostic independently matches a positive fixed-w trace to the
%   accepted prefix of a fixed-h trace and binds an explicit zero-field
%   endpoint anchor to the final record. The interval between sampled target
%   values is useful for conditional scalar bounds.
%
%   Discrete accepted targets do NOT prove a connected root section,
%   nonsingularity throughout the interval, or a full-edge enclosure in w.
%   Therefore every returned graph event has event_bracket_ok=false. The
%   scalar bounds are conditioning diagnostics only until a validated
%   continuation enclosure and a validated normalization bound are supplied
%   by a different proof-producing routine.

invalidId = 'invzp:FixedWEventEvidence:InvalidInput';
[Jq,fixedH,fixedW,endpointAnchor,cfg] = validateInputs( ...
    Jq,fixedH,fixedW,endpointAnchor,spec,invalidId);
nedge = numel(fixedH.records)-1;
wFixedH = arrayfun(@fixedHW,fixedH.records);

matchDistance = zeros(1,nedge);
hError = zeros(1,nedge);
wError = zeros(1,nedge);
for k = 1:nedge
    source = fixedH.records(k);
    target = fixedW.records(k);
    matchDistance(k) = stateDistance( ...
        source.returned_state,target.state, ...
        cfg.sigma_scale,cfg.k0_scale);
    hError(k) = abs(source.h-target.h);
    wError(k) = abs(wFixedH(k)-target.w);
    if target.target_w ~= wFixedH(k)
        fail(invalidId, ...
            'fixedW target %d is not exactly bound to fixedH record %d.',k,k);
    elseif matchDistance(k) > cfg.state_match_rms_max
        fail(invalidId, ...
            'fixedW target %d exceeds the state-match gate.',k);
    elseif hError(k) > cfg.h_match_abs_max
        fail(invalidId, ...
            'fixedW target %d exceeds the field-match gate.',k);
    elseif wError(k) > cfg.w_target_abs_max
        fail(invalidId, ...
            'fixedW target %d exceeds the w-match gate.',k);
    elseif ~finiteRealScalar(target.corrector.residual_inf) || ...
            ~finiteRealScalar(target.corrector.bordered_rcond) || ...
            target.corrector.residual_inf >= cfg.residual_tolerance || ...
            target.corrector.bordered_rcond <= cfg.rcond_min || ...
            ~target.corrector.accepted || ~target.path_accepted || ...
            ~acceptedNestedAudit(target.corrector.audit)
        fail(invalidId, ...
            'fixedW target %d fails a corrector acceptance gate.',k);
    end
end

endpointStateDistance = stateDistance( ...
    fixedH.records(end).returned_state,endpointAnchor.state, ...
    cfg.sigma_scale,cfg.k0_scale);
endpointHError = abs(fixedH.records(end).h-endpointAnchor.h);
endpointWError = abs(wFixedH(end)-endpointAnchor.w);
if endpointAnchor.source_record_index ~= numel(fixedH.records) || ...
        endpointAnchor.h ~= 0 || fixedH.records(end).h ~= 0
    fail(invalidId,'endpointAnchor must bind the final zero-field record.');
elseif endpointStateDistance > cfg.state_match_rms_max || ...
        endpointHError > cfg.h_match_abs_max || ...
        endpointWError > cfg.w_target_abs_max
    fail(invalidId,'endpointAnchor fails its state, h, or w match gate.');
elseif ~finiteRealScalar(endpointAnchor.residual_inf) || ...
        ~finiteRealScalar(endpointAnchor.w) || ...
        endpointAnchor.residual_inf >= cfg.residual_tolerance || ...
        ~endpointAnchor.event_clear || ...
        ~acceptedNestedAudit(endpointAnchor.audit)
    fail(invalidId,'endpointAnchor fails residual, event, or A-D audit.');
end

direction = sign(wFixedH(end)-wFixedH(1));
if direction == 0 || any(sign(diff(wFixedH)) ~= direction)
    fail(invalidId,'fixedH w coordinates must be strictly monotone.');
end

oracleSpec = struct( ...
    'version',cfg.version, ...
    'certificate_schema',cfg.certificate_schema, ...
    'pole_margin_min',cfg.pole_margin_min, ...
    'mean_margin_min',cfg.mean_margin_min, ...
    'allowed_enclosure_methods', ...
    ["fixed_w_sampled_targets"; ...
    "fixed_w_sampled_endpoint_anchor"]);
evidence = repmat(blankEvidence(),1,nedge);
oracleResultCells = cell(1,nedge);
for k = 1:nedge
    method = "fixed_w_sampled_targets";
    endpointKind = "fixed_w_to_fixed_w";
    if k == nedge
        method = "fixed_w_sampled_endpoint_anchor";
        endpointKind = "fixed_w_to_zero_field_anchor";
    end
    lower = min(wFixedH(k),wFixedH(k+1));
    upper = max(wFixedH(k),wFixedH(k+1));
    interval = [ ...
        nextDownScalar(lower-cfg.w_target_abs_max), ...
        nextUpScalar(upper+cfg.w_target_abs_max)];
    enclosure = struct( ...
        'schema','invzp_scalar_w_enclosure/v1', ...
        'source_id',cfg.source_id, ...
        'from_record_index',k, ...
        'to_record_index',k+1, ...
        'method',method, ...
        'validated',false, ...
        'w_interval',interval, ...
        'proof',struct( ...
            'schema','invzp_fixed_w_sampled_interval_diagnostic/v1', ...
            'fixed_h_schema',string(fixedH.schema), ...
            'fixed_w_schema',string(fixedW.schema), ...
            'fixed_w_spec_version',fixedW.spec.version, ...
            'from_record_index',k, ...
            'to_record_index',k+1, ...
            'endpoint_kind',endpointKind, ...
            'natural_coordinate','w=z-K0', ...
            'target_interval',[lower upper], ...
            'target_abs_tolerance',cfg.w_target_abs_max, ...
            'state_match_rms_from',matchDistance(k), ...
            'state_match_rms_to',toMatchDistance(k), ...
            'h_match_abs_from',hError(k), ...
            'h_match_abs_to',toHError(k), ...
            'discrete_samples_only',true, ...
            'connected_branch_enclosure_proved',false, ...
            'nonsingularity_over_interval_proved',false, ...
            'complete_graph_edge_claim',false), ...
        'normalization',struct( ...
            'schema','invzp_scalar_normalization_enclosure/v1', ...
            'validated',false, ...
            'static_closure_abs_bound',NaN, ...
            'proof',struct( ...
                'reason','no residual-derived full-edge z bound')));
    oracleResultCells{k} = invzp_scalar_event_interval_oracle( ...
        Jq,enclosure,oracleSpec);
    evidence(k) = oracleResultCells{k}.event_evidence;
end

oracleResults = [oracleResultCells{:}];
passing = arrayfun(@(item)item.event_bracket_ok,evidence);
conditionalClear = arrayfun( ...
    @(item)item.conditional_bounds_clear,oracleResults);
lowerBounds = vertcat(oracleResults.event_margin_lower_bounds);
report = struct( ...
    'schema','invzp_fixed_w_event_evidence/v1', ...
    'status','conditional_diagnostic', ...
    'status_detail',sprintf( ...
        '%d sampled adjacencies checked; no continuous edge certified',nedge), ...
    'spec_version',cfg.version, ...
    'source_id',cfg.source_id, ...
    'edge_count',nedge, ...
    'passing_edge_count',nnz(passing), ...
    'all_edges_pass',all(passing), ...
    'conditional_clear_count',nnz(conditionalClear), ...
    'all_conditional_bounds_clear',all(conditionalClear), ...
    'max_state_match_rms',max([matchDistance endpointStateDistance]), ...
    'max_h_match_abs',max([hError endpointHError]), ...
    'max_w_match_abs',max([wError endpointWError]), ...
    'minimum_conditional_event_lower_bounds',min(lowerBounds,[],1), ...
    'oracle_results',oracleResults, ...
    'complete_graph_edge_claim',false);
if ~all(conditionalClear)
    report.status = 'conditional_event_warning';
    report.status_detail = sprintf( ...
        '%d of %d sampled intervals have inconclusive scalar bounds; no edge certified', ...
        nedge-nnz(conditionalClear),nedge);
end

    function value = toMatchDistance(k)
        if k < nedge
            value = matchDistance(k+1);
        else
            value = endpointStateDistance;
        end
    end

    function value = toHError(k)
        if k < nedge
            value = hError(k+1);
        else
            value = endpointHError;
        end
    end
end

function [Jq,fixedH,fixedW,anchor,cfg] = validateInputs( ...
        Jq,fixedH,fixedW,anchor,spec,invalidId)
if ~isa(Jq,'double') || ~isreal(Jq) || ~isvector(Jq) || ...
        isempty(Jq) || any(~isfinite(Jq),'all')
    fail(invalidId,'Jq must be a nonempty finite real double vector.');
end
Jq = Jq(:);
if ~isstruct(fixedH) || ~isscalar(fixedH) || ...
        ~isfield(fixedH,'schema') || ...
        string(fixedH.schema) ~= "invzp_fixed_h_sequence/v1" || ...
        ~isfield(fixedH,'status') || string(fixedH.status) ~= "ok" || ...
        ~isfield(fixedH,'records') || numel(fixedH.records) < 2
    fail(invalidId,'fixedH must be a complete fixed-h sequence.');
end
for k = 1:numel(fixedH.records)
    record = fixedH.records(k);
    required = {'index','h','returned_state','info','path_accepted'};
    requireFields(record,required,sprintf('fixedH.records(%d)',k),invalidId);
    if record.index ~= k || ~isequal(record.path_accepted,true) || ...
            ~finiteRealScalar(record.h) || ...
            ~validState(record.returned_state) || ...
            ~isstruct(record.info) || ~isscalar(record.info) || ...
            ~all(isfield(record.info, ...
            {'accepted','residual_inf','z','audit'})) || ...
            ~isequal(record.info.accepted,true) || ...
            ~finiteRealScalar(record.info.residual_inf) || ...
            ~finiteRealScalar(record.info.z) || ...
            ~isstruct(record.info.audit) || ...
            ~isscalar(record.info.audit) || ...
            ~isfield(record.info.audit,'accepted') || ...
            ~isequal(record.info.audit.accepted,true)
        fail(invalidId,'fixedH record %d is not accepted and audited.',k);
    end
end
if ~isstruct(fixedW) || ~isscalar(fixedW) || ...
        ~isfield(fixedW,'schema') || ...
        string(fixedW.schema) ~= "invzp_fixed_w_sequence/v1" || ...
        ~isfield(fixedW,'status') || string(fixedW.status) ~= "ok" || ...
        ~isfield(fixedW,'records') || ...
        numel(fixedW.records) ~= numel(fixedH.records)-1 || ...
        ~isfield(fixedW,'spec')
    fail(invalidId, ...
        'fixedW must contain one accepted positive target per nonfinal fixedH record.');
end
for k = 1:numel(fixedW.records)
    required = {'index','target_w','status','path_accepted','h','w', ...
        'state','corrector'};
    requireFields(fixedW.records(k),required, ...
        sprintf('fixedW.records(%d)',k),invalidId);
    target = fixedW.records(k);
    if target.index ~= k || string(target.status) ~= "accepted" || ...
            ~isequal(target.path_accepted,true) || ...
            ~finiteRealScalar(target.target_w) || ...
            ~finiteRealScalar(target.h) || ...
            ~finiteRealScalar(target.w) || ...
            ~validState(target.state) || ...
            ~isstruct(target.corrector) || ...
            ~isscalar(target.corrector) || ...
            ~all(isfield(target.corrector, ...
            {'accepted','residual_inf','bordered_rcond','audit'})) || ...
            ~isequal(target.corrector.accepted,true) || ...
            ~finiteRealScalar(target.corrector.residual_inf) || ...
            ~finiteRealScalar(target.corrector.bordered_rcond) || ...
            ~acceptedNestedAudit(target.corrector.audit)
        fail(invalidId,'fixedW record %d is not an accepted record.',k);
    end
end
if ~isstruct(anchor) || ~isscalar(anchor)
    fail(invalidId,'endpointAnchor must be a scalar struct.');
end
requiredAnchor = {'schema','source_record_index','h','w','state', ...
    'residual_inf','audit','event_clear'};
requireFields(anchor,requiredAnchor,'endpointAnchor',invalidId);
if string(anchor.schema) ~= "invzp_fixed_w_endpoint_anchor/v1"
    fail(invalidId,'endpointAnchor uses the wrong schema.');
end
anchor.event_clear = logicalScalar( ...
    anchor.event_clear,'endpointAnchor.event_clear',invalidId);
if positiveInteger(anchor.source_record_index, ...
        'endpointAnchor.source_record_index',invalidId) ~= ...
        numel(fixedH.records) || ...
        ~finiteRealScalar(anchor.h) || ~finiteRealScalar(anchor.w) || ...
        ~finiteRealScalar(anchor.residual_inf) || ~validState(anchor.state)
    fail(invalidId,'endpointAnchor contains invalid scalar or state data.');
end

if ~isstruct(spec) || ~isscalar(spec)
    fail(invalidId,'spec must be a scalar struct.');
end
requiredSpec = {'schema','version','certificate_schema','source_id', ...
    'fixed_h_initial_state_id','fixed_w_initial_point_id', ...
    'sigma_scale','k0_scale','state_match_rms_max','h_match_abs_max', ...
    'w_target_abs_max','residual_tolerance','rcond_min', ...
    'pole_margin_min','mean_margin_min'};
requireFields(spec,requiredSpec,'spec',invalidId);
if textScalar(spec.schema,'spec.schema',invalidId) ~= ...
        "invzp_fixed_w_event_evidence_spec/v1"
    fail(invalidId, ...
        'spec.schema must be invzp_fixed_w_event_evidence_spec/v1.');
end
nw = numel(fixedH.records(1).returned_state.Sigma);
sigmaScale = spec.sigma_scale;
if isscalar(sigmaScale), sigmaScale = repmat(sigmaScale,nw,1); end
if ~isnumeric(sigmaScale) || ~isreal(sigmaScale) || ...
        ~isvector(sigmaScale) || numel(sigmaScale) ~= nw || ...
        any(~isfinite(sigmaScale),'all') || any(sigmaScale <= 0)
    fail(invalidId,'spec.sigma_scale must be a positive scalar or nw-vector.');
end
cfg = struct( ...
    'version',textScalar(spec.version,'spec.version',invalidId), ...
    'certificate_schema',textScalar( ...
        spec.certificate_schema,'spec.certificate_schema',invalidId), ...
    'source_id',textScalar(spec.source_id,'spec.source_id',invalidId), ...
    'fixed_h_initial_state_id',textScalar( ...
        spec.fixed_h_initial_state_id, ...
        'spec.fixed_h_initial_state_id',invalidId), ...
    'fixed_w_initial_point_id',textScalar( ...
        spec.fixed_w_initial_point_id, ...
        'spec.fixed_w_initial_point_id',invalidId), ...
    'sigma_scale',sigmaScale(:), ...
    'k0_scale',positive(spec.k0_scale,'spec.k0_scale',invalidId), ...
    'state_match_rms_max',positive( ...
        spec.state_match_rms_max,'spec.state_match_rms_max',invalidId), ...
    'h_match_abs_max',positive( ...
        spec.h_match_abs_max,'spec.h_match_abs_max',invalidId), ...
    'w_target_abs_max',positive( ...
        spec.w_target_abs_max,'spec.w_target_abs_max',invalidId), ...
    'residual_tolerance',positive( ...
        spec.residual_tolerance,'spec.residual_tolerance',invalidId), ...
    'rcond_min',positive(spec.rcond_min,'spec.rcond_min',invalidId), ...
    'pole_margin_min',positive( ...
        spec.pole_margin_min,'spec.pole_margin_min',invalidId), ...
    'mean_margin_min',positive( ...
        spec.mean_margin_min,'spec.mean_margin_min',invalidId));
if ~isfield(fixedH,'initial_state_id') || ...
        textScalar(fixedH.initial_state_id, ...
        'fixedH.initial_state_id',invalidId) ~= ...
        cfg.fixed_h_initial_state_id
    fail(invalidId, ...
        'spec.fixed_h_initial_state_id does not bind the fixed-h trace.');
end
if ~isfield(fixedW,'initial_point_id') || ...
        textScalar(fixedW.initial_point_id, ...
        'fixedW.initial_point_id',invalidId) ~= ...
        cfg.fixed_w_initial_point_id || ...
        ~isstruct(fixedW.spec) || ~isscalar(fixedW.spec) || ...
        ~isfield(fixedW.spec,'initial_point_id') || ...
        textScalar(fixedW.spec.initial_point_id, ...
        'fixedW.spec.initial_point_id',invalidId) ~= ...
        cfg.fixed_w_initial_point_id
    fail(invalidId, ...
        'spec.fixed_w_initial_point_id does not bind the fixed-w trace.');
end
end

function value = fixedHW(record)
value = record.info.z-record.returned_state.K0s;
end

function value = stateDistance(first,second,sigmaScale,k0Scale)
required = {'Sigma','K0s'};
if ~isstruct(first) || ~isscalar(first) || ...
        ~all(isfield(first,required)) || ...
        ~isstruct(second) || ~isscalar(second) || ...
        ~all(isfield(second,required)) || ...
        numel(first.Sigma) ~= numel(sigmaScale) || ...
        numel(second.Sigma) ~= numel(sigmaScale)
    value = Inf;
    return
end
dsigma = (first.Sigma(:)-second.Sigma(:))./sigmaScale;
dk0 = (first.K0s-second.K0s)/k0Scale;
value = sqrt(mean(abs(dsigma).^2)+abs(dk0).^2);
if ~isfinite(value)
    value = Inf;
end
end

function value = positive(value,name,invalidId)
if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ...
        ~isfinite(value) || value <= 0
    fail(invalidId,'%s must be a finite positive scalar.',name);
end
end

function value = positiveInteger(value,name,invalidId)
value = positive(value,name,invalidId);
if value ~= floor(value)
    fail(invalidId,'%s must be a positive integer.',name);
end
end

function tf = finiteRealScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
end

function tf = validState(value)
tf = isstruct(value) && isscalar(value) && ...
    all(isfield(value,{'Sigma','K0s'})) && ...
    isnumeric(value.Sigma) && isreal(value.Sigma) && ...
    isvector(value.Sigma) && ~isempty(value.Sigma) && ...
    all(isfinite(value.Sigma),'all') && ...
    finiteRealScalar(value.K0s);
end

function tf = acceptedNestedAudit(value)
tf = isstruct(value) && isscalar(value) && ...
    isfield(value,'audit') && isstruct(value.audit) && ...
    isscalar(value.audit) && isfield(value.audit,'accepted') && ...
    isequal(value.audit.accepted,true);
end

function value = logicalScalar(value,name,invalidId)
if ~islogical(value) || ~isscalar(value)
    fail(invalidId,'%s must be a scalar logical.',name);
end
end

function value = textScalar(value,name,invalidId)
if ischar(value) && isrow(value)
    value = string(value);
elseif isstring(value) && isscalar(value) && ~ismissing(value)
    value = string(value);
else
    fail(invalidId,'%s must be a nonmissing text scalar.',name);
end
if strlength(value) == 0
    fail(invalidId,'%s must not be empty.',name);
end
end

function requireFields(value,names,label,invalidId)
for k = 1:numel(names)
    if ~isfield(value,names{k})
        fail(invalidId,'%s.%s is required.',label,names{k});
    end
end
end

function y = nextUpScalar(x)
if x == Inf
    y = x;
elseif x == -Inf
    y = -realmax('double');
elseif x == 0
    y = typecast(uint64(1),'double');
else
    bits = typecast(x,'uint64');
    if x > 0, bits = bits+uint64(1); else, bits = bits-uint64(1); end
    y = typecast(bits,'double');
end
end

function y = nextDownScalar(x)
if x == -Inf
    y = x;
elseif x == Inf
    y = realmax('double');
elseif x == 0
    y = -typecast(uint64(1),'double');
else
    bits = typecast(x,'uint64');
    if x > 0, bits = bits-uint64(1); else, bits = bits+uint64(1); end
    y = typecast(bits,'double');
end
end

function item = blankEvidence()
item = struct('schema',"",'from_record_index',0, ...
    'to_record_index',0,'event_bracket_ok',false, ...
    'source_record_id',"",'payload',struct());
end

function fail(identifier,message,varargin)
error(identifier,message,varargin{:});
end
