function [vertices,segment,report] = ...
        invzp_fixed_h_trace_graph_inputs(trace,spec,eventEvidence)
%INVZP_FIXED_H_TRACE_GRAPH_INPUTS Translate certified fixed-h trace records.
%
%   [VERTICES,SEGMENT,REPORT] =
%   INVZP_FIXED_H_TRACE_GRAPH_INPUTS(TRACE,SPEC,EVENTEVIDENCE) prepares
%   inputs for INVZP_ASSEMBLE_AUDITED_GRAPH. It does not assemble, solve,
%   cluster, match endpoints, infer an event certificate, or select a
%   branch.
%
%   TRACE must use schema invzp_fixed_h_sequence/v1. Every emitted vertex
%   is rechecked against SPEC and carries the exact stored A-D payload.
%   EVENTEVIDENCE is optional explicit evidence for adjacent record pairs.
%   A missing certificate produces event_bracket_ok=false, so the graph
%   assembler retains that adjacency as a blocker. This adapter never
%   converts pointwise-positive event margins into a continuous edge
%   certificate.

invalidId = 'invzp:FixedHGraphInputs:InvalidInput';
if nargin < 3 || isempty(eventEvidence)
    eventEvidence = repmat(blankEventEvidence(),1,0);
end
[trace,cfg] = validateInputs(trace,spec,invalidId);
eventEvidence = normalizeEventEvidence( ...
    eventEvidence,cfg,numel(trace.records),invalidId);

records = trace.records;
nrecord = numel(records);
acceptedCount = numel(trace.accepted_indices);
checks = repmat(blankRecordCheck(),1,nrecord);
certifiedCount = acceptedCount;
thresholdProvenance = "embedded_config";
for k = 1:acceptedCount
    [checks(k),hasEmbeddedConfig] = certifyRecord(records(k),cfg,k);
    if ~hasEmbeddedConfig
        thresholdProvenance = "caller_declared_legacy";
    end
    if ~checks(k).accepted
        certifiedCount = k-1;
        break
    end
end
for k = acceptedCount+1:nrecord
    checks(k).record_index = k;
    checks(k).accepted = false;
    checks(k).reasons = "trace_record_not_accepted";
end
if certifiedCount < acceptedCount
    for k = certifiedCount+2:acceptedCount
        checks(k).record_index = k;
        checks(k).accepted = false;
        checks(k).reasons = "not_emitted_after_certificate_blocker";
    end
end

vertices = repmat(blankVertex(),1,certifiedCount);
for k = 1:certifiedCount
    record = records(k);
    vertexId = makeVertexId(cfg.vertex_id_prefix,k);
    margins = eventMargins(record,cfg);
    certificate = struct( ...
        'schema',cfg.certificate_schema, ...
        'residual_inf',record.info.residual_inf, ...
        'residual_tolerance',cfg.residual_tolerance, ...
        'audit_accepted',logical(record.info.audit.accepted), ...
        'audit_payload',record.info.audit, ...
        'domain_ok',true, ...
        'event_margins',margins);
    vertices(k) = struct( ...
        'id',vertexId,'h',record.h, ...
        'Sigma',record.returned_state.Sigma(:), ...
        'K0s',record.returned_state.K0s, ...
        'm',record.node_meta.m, ...
        'source_schema',string(trace.schema), ...
        'source_id',cfg.source_id, ...
        'certificate',certificate);
end

segment = repmat(blankSegment(),1,0);
edgeChecks = repmat(blankEdgeCheck(),1,max(certifiedCount-1,0));
if certifiedCount >= 2
    adjacency = repmat(blankAdjacency(),1,certifiedCount-1);
    for k = 1:certifiedCount-1
        target = records(k+1);
        [eventCertificate,eventStatus] = findEventEvidence( ...
            eventEvidence,k,k+1,cfg.source_id);
        if eventCertificate.event_bracket_ok
            validateEventEndpointBounds( ...
                eventCertificate.payload,records(k),target,cfg,invalidId);
        end
        predictorOk = isfinite(target.predictor_distance) && ...
            target.predictor_distance <= trace.spec.predictor_tube_max;
        sourceRecordId = eventCertificate.source_record_id;
        payload = struct( ...
            'trace_schema',string(trace.schema), ...
            'trace_source_id',cfg.source_id, ...
            'from_record_index',k, ...
            'to_record_index',k+1, ...
            'predictor_kind',string(target.predictor_kind), ...
            'event_certificate',eventCertificate.payload);
        adjacency(k) = struct( ...
            'schema',cfg.certificate_schema, ...
            'from_id',vertices(k).id, ...
            'to_id',vertices(k+1).id, ...
            'local_continuity_ok',logical(target.path_accepted), ...
            'predictor_distance',target.predictor_distance, ...
            'predictor_tube_ok',predictorOk, ...
            'tangent_required',false, ...
            'tangent_line_error',NaN, ...
            'tangent_line_ok',true, ...
            'event_bracket_ok',eventCertificate.event_bracket_ok, ...
            'source_record_id',sourceRecordId, ...
            'evidence_payload',payload, ...
            'same_h',false);
        edgeChecks(k) = struct( ...
            'from_record_index',k,'to_record_index',k+1, ...
            'event_evidence_status',eventStatus, ...
            'event_bracket_ok',eventCertificate.event_bracket_ok);
    end
    termination = makeTermination( ...
        trace,checks,certifiedCount,acceptedCount,cfg);
    segment = struct( ...
        'id',cfg.segment_id, ...
        'vertex_ids',reshape(string({vertices.id}),[],1), ...
        'source_schema',string(trace.schema), ...
        'source_id',cfg.source_id, ...
        'adjacency',adjacency, ...
        'termination',termination, ...
        'monotone_h',true);
end

missingEventCount = nnz(arrayfun( ...
    @(item) ~item.event_bracket_ok,edgeChecks));
status = "ready_for_graph_assembly";
detail = sprintf('%d vertices and %d adjacencies translated', ...
    certifiedCount,max(certifiedCount-1,0));
if certifiedCount < acceptedCount
    status = "certificate_blocked";
    detail = sprintf( ...
        'record %d failed the declared vertex certificate', ...
        certifiedCount+1);
elseif certifiedCount < 2
    status = "insufficient_vertices";
    detail = sprintf('%d certified vertices cannot form a segment', ...
        certifiedCount);
elseif missingEventCount > 0
    status = "event_evidence_incomplete";
    detail = sprintf( ...
        '%d of %d adjacencies lack a passing signed-event certificate', ...
        missingEventCount,certifiedCount-1);
end
report = struct( ...
    'schema','invzp_fixed_h_trace_graph_inputs/v1', ...
    'status',char(status),'status_detail',detail, ...
    'spec_version',cfg.version,'trace_schema',string(trace.schema), ...
    'source_id',cfg.source_id, ...
    'trace_accepted_count',acceptedCount, ...
    'certified_vertex_count',certifiedCount, ...
    'adjacency_count',max(certifiedCount-1,0), ...
    'missing_event_certificate_count',missingEventCount, ...
    'threshold_provenance',char(thresholdProvenance), ...
    'declared_thresholds',struct( ...
        'residual_tolerance',cfg.residual_tolerance, ...
        'audit_tolerance',cfg.audit_tolerance, ...
        'pole_margin_min',cfg.pole_margin_min, ...
        'mean_margin_min',cfg.mean_margin_min), ...
    'record_checks',checks,'edge_checks',edgeChecks, ...
    'complete_candidate_claim',false);
end

function [trace,cfg] = validateInputs(trace,spec,invalidId)
if ~isstruct(trace) || ~isscalar(trace)
    fail(invalidId,'trace must be a scalar struct.');
end
requiredTrace = {'schema','status','status_detail','spec','records', ...
    'accepted_indices','h_values'};
requireFields(trace,requiredTrace,'trace',invalidId);
if stringScalar(trace.schema,'trace.schema',invalidId) ~= ...
        "invzp_fixed_h_sequence/v1"
    fail(invalidId, ...
        'trace must use schema invzp_fixed_h_sequence/v1.');
end
if ~isstruct(trace.records)
    fail(invalidId,'trace.records must be a struct array.');
end
nrecord = numel(trace.records);
if ~isnumeric(trace.h_values) || ~isreal(trace.h_values) || ...
        ~isvector(trace.h_values) || numel(trace.h_values) ~= nrecord || ...
        any(~isfinite(trace.h_values),'all')
    fail(invalidId, ...
        'trace.h_values must be one finite real value per record.');
end
h = reshape(trace.h_values,1,[]);
if nrecord > 1 && ~(all(diff(h) > 0) || all(diff(h) < 0))
    fail(invalidId,'trace.h_values must be strictly monotone.');
end
if nrecord > 0
    recordH = arrayfun(@(item)item.h,trace.records);
    if ~isequal(recordH,h)
        fail(invalidId, ...
            'trace record fields must exactly match trace.h_values.');
    end
end
if ~isnumeric(trace.accepted_indices) || ...
        ~isvector(trace.accepted_indices) || ...
        any(~isfinite(trace.accepted_indices),'all')
    fail(invalidId,'trace.accepted_indices must be a finite index vector.');
end
acceptedIndices = reshape(trace.accepted_indices,1,[]);
if ~isequal(acceptedIndices,1:numel(acceptedIndices))
    fail(invalidId, ...
        'A fixed-h trace must contain one contiguous accepted prefix.');
end
for k = 1:nrecord
    requireFields(trace.records(k), ...
        {'index','h','status','predictor_kind','predictor_distance', ...
        'node_meta','returned_state','info','fixed_h_accepted', ...
        'path_accepted','reason'}, ...
        sprintf('trace.records(%d)',k),invalidId);
    if trace.records(k).index ~= k
        fail(invalidId,'trace record indices must be consecutive.');
    end
    stringScalar(trace.records(k).status, ...
        sprintf('trace.records(%d).status',k),invalidId);
    logicalScalar(trace.records(k).fixed_h_accepted, ...
        sprintf('trace.records(%d).fixed_h_accepted',k),invalidId);
    shouldBeAccepted = k <= numel(acceptedIndices);
    if logicalScalar(trace.records(k).path_accepted, ...
            sprintf('trace.records(%d).path_accepted',k),invalidId) ...
            ~= shouldBeAccepted
        fail(invalidId, ...
            'trace.accepted_indices disagree with path_accepted flags.');
    end
end
if stringScalar(trace.status,'trace.status',invalidId) == "ok" && ...
        numel(acceptedIndices) ~= nrecord
    fail(invalidId, ...
        'trace.status=ok requires every submitted record to be accepted.');
end
if ~isstruct(trace.spec) || ~isscalar(trace.spec) || ...
        ~isfield(trace.spec,'predictor_tube_max')
    fail(invalidId,'trace.spec.predictor_tube_max is required.');
end
positive(trace.spec.predictor_tube_max, ...
    'trace.spec.predictor_tube_max',invalidId);

if ~isstruct(spec) || ~isscalar(spec)
    fail(invalidId,'spec must be a scalar struct.');
end
requiredSpec = {'version','certificate_schema','source_id', ...
    'vertex_id_prefix','segment_id','residual_tolerance', ...
    'audit_tolerance', ...
    'pole_margin_min','mean_margin_min','h_domain', ...
    'required_edge_event_margins', ...
    'allowed_event_certificate_methods', ...
    'require_embedded_config'};
requireFields(spec,requiredSpec,'spec',invalidId);
cfg = struct( ...
    'version',stringScalar(spec.version,'spec.version',invalidId), ...
    'certificate_schema',stringScalar( ...
        spec.certificate_schema,'spec.certificate_schema',invalidId), ...
    'source_id',stringScalar(spec.source_id,'spec.source_id',invalidId), ...
    'vertex_id_prefix',stringScalar( ...
        spec.vertex_id_prefix,'spec.vertex_id_prefix',invalidId), ...
    'segment_id',stringScalar( ...
        spec.segment_id,'spec.segment_id',invalidId), ...
    'residual_tolerance',positive( ...
        spec.residual_tolerance,'spec.residual_tolerance',invalidId), ...
    'audit_tolerance',positive( ...
        spec.audit_tolerance,'spec.audit_tolerance',invalidId), ...
    'pole_margin_min',positive( ...
        spec.pole_margin_min,'spec.pole_margin_min',invalidId), ...
    'mean_margin_min',positive( ...
        spec.mean_margin_min,'spec.mean_margin_min',invalidId), ...
    'h_domain',finiteDomain(spec.h_domain,'spec.h_domain',invalidId), ...
    'required_edge_event_margins',stringVector( ...
        spec.required_edge_event_margins, ...
        'spec.required_edge_event_margins',false,invalidId), ...
    'allowed_event_certificate_methods',stringVector( ...
        spec.allowed_event_certificate_methods, ...
        'spec.allowed_event_certificate_methods',true,invalidId), ...
    'require_embedded_config',logicalScalar( ...
        spec.require_embedded_config, ...
        'spec.require_embedded_config',invalidId));
if numel(unique(cfg.required_edge_event_margins)) ~= ...
        numel(cfg.required_edge_event_margins)
    fail(invalidId, ...
        'spec.required_edge_event_margins must be unique.');
end
for k = 1:numel(cfg.required_edge_event_margins)
    if ~isvarname(char(cfg.required_edge_event_margins(k)))
        fail(invalidId, ...
            'spec.required_edge_event_margins must be field names.');
    elseif ~ismember(cfg.required_edge_event_margins(k), ...
            ["h_lower","h_upper","pole","mean"])
        fail(invalidId, ...
            'Unsupported edge-event margin "%s".', ...
            cfg.required_edge_event_margins(k));
    end
end
if numel(unique(cfg.allowed_event_certificate_methods)) ~= ...
        numel(cfg.allowed_event_certificate_methods)
    fail(invalidId, ...
        'spec.allowed_event_certificate_methods must be unique.');
end
end

function [check,hasEmbeddedConfig] = certifyRecord(record,cfg,index)
check = blankRecordCheck();
check.record_index = index;
reasons = strings(0,1);
if string(record.status) ~= "accepted" || ...
        ~record.fixed_h_accepted || ~record.path_accepted
    reasons(end+1) = "trace_acceptance_missing";
end
if ~isstruct(record.node_meta) || ~isscalar(record.node_meta) || ...
        ~all(isfield(record.node_meta,{'status','m'})) || ...
        string(record.node_meta.status) ~= "ok" || ...
        ~finiteRealScalar(record.node_meta.m)
    reasons(end+1) = "node_domain_or_moment_invalid";
end
if ~isstruct(record.returned_state) || ...
        ~all(isfield(record.returned_state,{'Sigma','K0s'})) || ...
        ~finiteRealVector(record.returned_state.Sigma) || ...
        ~finiteRealScalar(record.returned_state.K0s)
    reasons(end+1) = "returned_state_invalid";
end
if ~isstruct(record.info) || ~isscalar(record.info) || ...
        ~all(isfield(record.info, ...
        {'accepted','residual_inf','pole_margin','mean_margin','audit'}))
    reasons(end+1) = "solver_info_invalid";
else
    if ~isequal(record.info.accepted,true) || ...
            ~finiteRealScalar(record.info.residual_inf) || ...
            record.info.residual_inf >= cfg.residual_tolerance
        reasons(end+1) = "strict_residual_gate_failed";
    end
    if ~finiteRealScalar(record.info.pole_margin) || ...
            record.info.pole_margin <= cfg.pole_margin_min
        reasons(end+1) = "pole_margin_gate_failed";
    end
    if ~finiteRealScalar(record.info.mean_margin) || ...
            record.info.mean_margin <= cfg.mean_margin_min
        reasons(end+1) = "mean_margin_gate_failed";
    end
    if ~isstruct(record.info.audit) || ...
            ~isscalar(record.info.audit) || ...
            ~isfield(record.info.audit,'accepted') || ...
            ~isequal(record.info.audit.accepted,true)
        reasons(end+1) = "A_D_audit_gate_failed";
    end
end
if ~finiteRealScalar(record.h) || ...
        record.h < cfg.h_domain(1) || record.h > cfg.h_domain(2)
    reasons(end+1) = "h_domain_gate_failed";
end

hasEmbeddedConfig = isstruct(record.info) && ...
    isfield(record.info,'config') && ...
    isstruct(record.info.config) && isscalar(record.info.config);
if hasEmbeddedConfig
    embedded = record.info.config;
    required = {'schema','tol_outer','residual_trigger','pole_margin_min', ...
        'mean_margin_min'};
    if ~all(isfield(embedded,required)) || ...
            string(embedded.schema) ~= ...
            "invz_ordered_node_newton_config/v1" || ...
            ~isequal(embedded.tol_outer,cfg.audit_tolerance) || ...
            ~isequal(embedded.residual_trigger,cfg.residual_tolerance) || ...
            ~isequal(embedded.pole_margin_min,cfg.pole_margin_min) || ...
            ~isequal(embedded.mean_margin_min,cfg.mean_margin_min)
        reasons(end+1) = "embedded_threshold_mismatch";
    end
elseif cfg.require_embedded_config
    reasons(end+1) = "embedded_threshold_provenance_missing";
end
check.accepted = isempty(reasons);
check.reasons = reasons;
end

function margins = eventMargins(record,cfg)
margins = struct( ...
    'h_lower',record.h-cfg.h_domain(1), ...
    'h_upper',cfg.h_domain(2)-record.h, ...
    'pole',record.info.pole_margin-cfg.pole_margin_min, ...
    'mean',record.info.mean_margin-cfg.mean_margin_min);
end

function normalized = normalizeEventEvidence(evidence,cfg,nrecord,invalidId)
if ~isstruct(evidence)
    fail(invalidId,'eventEvidence must be a struct array.');
end
normalized = repmat(blankEventEvidence(),1,numel(evidence));
pairs = zeros(numel(evidence),2);
required = {'schema','from_record_index','to_record_index', ...
    'event_bracket_ok','source_record_id','payload'};
for k = 1:numel(evidence)
    requireFields(evidence(k),required, ...
        sprintf('eventEvidence(%d)',k),invalidId);
    schema = stringScalar( ...
        evidence(k).schema,'eventEvidence.schema',invalidId);
    if schema ~= cfg.certificate_schema
        fail(invalidId, ...
            'eventEvidence schema must match spec.certificate_schema.');
    end
    first = positiveInteger(evidence(k).from_record_index, ...
        'eventEvidence.from_record_index',invalidId);
    second = positiveInteger(evidence(k).to_record_index, ...
        'eventEvidence.to_record_index',invalidId);
    if second ~= first+1 || second > nrecord
        fail(invalidId, ...
            'eventEvidence must identify consecutive trace records.');
    end
    ok = logicalScalar(evidence(k).event_bracket_ok, ...
        'eventEvidence.event_bracket_ok',invalidId);
    sourceRecordId = stringScalar( ...
        evidence(k).source_record_id, ...
        'eventEvidence.source_record_id',invalidId);
    if sourceRecordId ~= makeEventId(cfg.source_id,first,second)
        fail(invalidId, ...
            'eventEvidence.source_record_id is not bound to its source pair.');
    end
    if ~isstruct(evidence(k).payload) || ~isscalar(evidence(k).payload)
        fail(invalidId,'eventEvidence.payload must be a scalar struct.');
    elseif ok
        validatePassingEventPayload( ...
            evidence(k).payload,cfg,first,second,invalidId);
    end
    normalized(k) = struct( ...
        'schema',schema,'from_record_index',first, ...
        'to_record_index',second,'event_bracket_ok',ok, ...
        'source_record_id',sourceRecordId, ...
        'payload',evidence(k).payload);
    pairs(k,:) = [first second];
end
if ~isempty(pairs) && size(unique(pairs,'rows'),1) ~= size(pairs,1)
    fail(invalidId,'eventEvidence record pairs must be unique.');
end
end

function validatePassingEventPayload(payload,cfg,first,second,invalidId)
required = {'schema','method','source_id','from_record_index', ...
    'to_record_index','margin_names','lower_bounds','proof'};
requireFields(payload,required,'eventEvidence.payload',invalidId);
if stringScalar(payload.schema, ...
        'eventEvidence.payload.schema',invalidId) ~= ...
        "invzp_signed_event_edge/v1"
    fail(invalidId, ...
        'Passing event evidence must use invzp_signed_event_edge/v1.');
end
method = stringScalar( ...
    payload.method,'eventEvidence.payload.method',invalidId);
if ~ismember(method,cfg.allowed_event_certificate_methods)
    fail(invalidId, ...
        'Event certificate method "%s" is not preregistered.',method);
end
if stringScalar(payload.source_id, ...
        'eventEvidence.payload.source_id',invalidId) ~= cfg.source_id
    fail(invalidId, ...
        'Event certificate source_id does not match spec.source_id.');
end
if positiveInteger(payload.from_record_index, ...
        'eventEvidence.payload.from_record_index',invalidId) ~= first || ...
        positiveInteger(payload.to_record_index, ...
        'eventEvidence.payload.to_record_index',invalidId) ~= second
    fail(invalidId, ...
        'Event certificate payload is not bound to its record pair.');
end
names = stringVector(payload.margin_names, ...
    'eventEvidence.payload.margin_names',false,invalidId);
if ~isequal(names(:),cfg.required_edge_event_margins(:))
    fail(invalidId, ...
        'Event certificate margins must exactly match the preregistration.');
end
bounds = payload.lower_bounds;
if ~isnumeric(bounds) || ~isreal(bounds) || ~isvector(bounds) || ...
        numel(bounds) ~= numel(names) || ...
        any(~isfinite(bounds),'all') || any(bounds <= 0)
    fail(invalidId, ...
        'Event certificate lower_bounds must be one positive value per margin.');
end
if ~isstruct(payload.proof) || ~isscalar(payload.proof) || ...
        isempty(fieldnames(payload.proof))
    fail(invalidId, ...
        'A passing event certificate requires a nonempty proof payload.');
end
end

function validateEventEndpointBounds(payload,first,second,cfg,invalidId)
firstMargins = eventMargins(first,cfg);
secondMargins = eventMargins(second,cfg);
names = reshape(string(payload.margin_names),[],1);
bounds = payload.lower_bounds(:);
for k = 1:numel(names)
    name = char(names(k));
    if ~isfield(firstMargins,name) || ~isfield(secondMargins,name)
        fail(invalidId, ...
            'Event certificate margin "%s" is unavailable.',name);
    end
    endpointMinimum = min(firstMargins.(name),secondMargins.(name));
    if bounds(k) > endpointMinimum
        fail(invalidId, ...
            ['Event certificate lower bound for "%s" exceeds a stored ', ...
            'endpoint margin.'],name);
    end
end
end

function [certificate,status] = findEventEvidence(evidence,first,second,sourceId)
certificate = blankEventEvidence();
certificate.schema = "";
certificate.from_record_index = first;
certificate.to_record_index = second;
certificate.event_bracket_ok = false;
certificate.source_record_id = makeRecordId(sourceId,second);
certificate.payload = struct('status','missing_signed_event_certificate');
status = "missing";
if isempty(evidence)
    return
end
match = [evidence.from_record_index] == first & ...
    [evidence.to_record_index] == second;
if any(match)
    certificate = evidence(find(match,1));
    if certificate.event_bracket_ok
        status = "accepted";
    else
        status = "rejected";
    end
end
end

function termination = makeTermination( ...
        trace,checks,certifiedCount,acceptedCount,cfg)
if certifiedCount < acceptedCount
    failedIndex = certifiedCount+1;
    status = "certificate_blocked";
    reason = strjoin(checks(failedIndex).reasons,'; ');
    sourceRecordId = makeRecordId(cfg.source_id,failedIndex);
    resolved = false;
elseif string(trace.status) == "ok"
    status = "schedule_complete";
    reason = "";
    sourceRecordId = makeRecordId(cfg.source_id,numel(trace.records));
    resolved = true;
else
    status = "trace_"+string(trace.status);
    reason = string(trace.status_detail);
    failedIndex = min(acceptedCount+1,numel(trace.records));
    sourceRecordId = makeRecordId(cfg.source_id,failedIndex);
    resolved = false;
end
termination = struct( ...
    'schema',cfg.certificate_schema,'resolved',logical(resolved), ...
    'status',status,'reason',reason, ...
    'source_record_id',sourceRecordId, ...
    'payload',struct( ...
        'trace_status',string(trace.status), ...
        'trace_status_detail',string(trace.status_detail), ...
        'accepted_count',acceptedCount, ...
        'certified_count',certifiedCount));
end

function value = finiteDomain(value,name,invalidId)
if ~isnumeric(value) || ~isreal(value) || ~isequal(size(value),[1 2]) || ...
        any(~isfinite(value),'all') || value(1) >= value(2)
    fail(invalidId,'%s must be a finite increasing [lower upper] row.',name);
end
end

function value = positive(value,name,invalidId)
if ~finiteRealScalar(value) || value <= 0
    fail(invalidId,'%s must be a finite positive scalar.',name);
end
end

function value = positiveInteger(value,name,invalidId)
if ~finiteRealScalar(value) || value < 1 || value ~= floor(value)
    fail(invalidId,'%s must be a positive integer.',name);
end
end

function value = logicalScalar(value,name,invalidId)
if ~islogical(value) || ~isscalar(value)
    fail(invalidId,'%s must be a scalar logical.',name);
end
end

function value = stringScalar(value,name,invalidId)
if ischar(value) && isrow(value)
    value = string(value);
elseif isstring(value) && isscalar(value) && ~ismissing(value)
    value = string(value);
else
    fail(invalidId,'%s must be a nonmissing text scalar.',name);
end
if strlength(value) == 0
    fail(invalidId,'%s must not be empty.',name);
end
end

function values = stringVector(value,name,allowEmpty,invalidId)
if ischar(value)
    if ~isrow(value)
        fail(invalidId,'%s must be a text vector.',name);
    end
    values = string(value);
elseif isstring(value) && isvector(value) && ...
        ~any(ismissing(value),'all')
    values = value(:);
else
    fail(invalidId,'%s must be a nonmissing text vector.',name);
end
if ~allowEmpty && isempty(values)
    fail(invalidId,'%s must not be empty.',name);
elseif any(strlength(values) == 0)
    fail(invalidId,'%s entries must not be empty.',name);
end
end

function requireFields(value,names,label,invalidId)
for k = 1:numel(names)
    if ~isfield(value,names{k})
        fail(invalidId,'%s.%s is required.',label,names{k});
    end
end
end

function tf = finiteRealScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value);
end

function tf = finiteRealVector(value)
tf = isnumeric(value) && isreal(value) && isvector(value) && ...
    ~isempty(value) && all(isfinite(value),'all');
end

function id = makeVertexId(prefix,index)
id = prefix+"-"+compose("%06d",index);
end

function id = makeRecordId(sourceId,index)
id = sourceId+"#record-"+compose("%06d",index);
end

function id = makeEventId(sourceId,first,second)
id = sourceId+"#event-"+compose("%06d",first)+"-"+compose("%06d",second);
end

function item = blankVertex()
item = struct('id',"",'h',NaN,'Sigma',zeros(0,1),'K0s',NaN, ...
    'm',NaN,'source_schema',"",'source_id',"",'certificate',struct());
end

function item = blankSegment()
item = struct('id',"",'vertex_ids',strings(0,1), ...
    'source_schema',"",'source_id',"", ...
    'adjacency',repmat(blankAdjacency(),1,0), ...
    'termination',struct(),'monotone_h',false);
end

function item = blankAdjacency()
item = struct('schema',"",'from_id',"",'to_id',"", ...
    'local_continuity_ok',false,'predictor_distance',NaN, ...
    'predictor_tube_ok',false,'tangent_required',false, ...
    'tangent_line_error',NaN,'tangent_line_ok',false, ...
    'event_bracket_ok',false,'source_record_id',"", ...
    'evidence_payload',struct(),'same_h',false);
end

function item = blankEventEvidence()
item = struct('schema',"",'from_record_index',0, ...
    'to_record_index',0,'event_bracket_ok',false, ...
    'source_record_id',"",'payload',struct());
end

function item = blankRecordCheck()
item = struct('record_index',0,'accepted',false, ...
    'reasons',strings(0,1));
end

function item = blankEdgeCheck()
item = struct('from_record_index',0,'to_record_index',0, ...
    'event_evidence_status',"",'event_bracket_ok',false);
end

function fail(identifier,message,varargin)
error(identifier,message,varargin{:});
end
