function result = invzp_approximation_production_validation(reuse_checkpoint)
%INVZP_APPROXIMATION_PRODUCTION_VALIDATION End-to-end opt-in ensemble check.
% Exercise the map at representative low and high fields, retain uncertainty
% for every exported susceptibility quantity, and re-run a strict-default
% oracle after the approximation implementation.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'), ...
    fullfile(repo,'invz_projected','tests'));

F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
C = load(fullfile(here,'wp6_approximation_census.mat'));
fields = C.result.fields.';
factors = C.result.area_factors;
w = [0.001;0.003;0.006];
solve_opts = struct('mix_outer',0.25,'max_outer',1000,'nH',129, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component');
opts = struct('Jnu',F.J,'info',F.info,'parallel',true,'verbose',false, ...
    'eta',5e-5,'solve_opts',solve_opts);
if nargin < 1, reuse_checkpoint = false; end
checkpoint_path = fullfile(here, ...
    'wp6_approximation_production_checkpoint.mat');
if reuse_checkpoint
    Q = load(checkpoint_path);
    assert(isequal(Q.fields,fields) && isequal(Q.factors,factors) && ...
        isequal(Q.w,w),'Saved production checkpoint configuration changed.');
    S = Q.S;
else
    S = invz_spectra_map(invz_ion(),C.result.T,fields,w,opts);
    save(checkpoint_path,'S','fields','factors','w','-v7.3');
end
E = S.approximation_ensemble;

i02 = find(abs(fields-0.2) <= 1e-12,1);
i05 = find(abs(fields-0.5) <= 1e-12,1);
all_members_ordered = all(E.phase == 1,1);
all_frequency_complete = all(E.chiz_complete,1);
production_covered = all_members_ordered & all_frequency_complete;
hmf_factor_ordering = all(diff(E.hmf(:,production_covered),1,1) < 0,1);

coarse_central = nan(size(fields));
for ib = 1:numel(fields)
    coarse_central(ib) = C.result.records(ib).members(2).coarse_hmf;
end
central_hmf_delta = abs(S.hmf-coarse_central);
coarse_comparable = isfinite(coarse_central) & isfinite(S.hmf);

assert(strcmp(S.hmf_integral_mode,'missing_area_ensemble') && ...
    S.production_approximation && S.approximation_only && ~S.visual_only);
assert(all(E.phase(:,i02) == 1) && E.phase_consistent(i02), ...
    'The 129-node 0.2 T component must cover every member.');
assert(all(E.phase(:,i05) == 0) && ~E.phase_consistent(i05), ...
    'The 129-node 0.5 T profile must remain component-masked.');
assert(~production_covered(i05) && ...
    all(production_covered(setdiff(1:numel(fields),i05))), ...
    'The production-resolution coverage partition changed.');
assert(all(hmf_factor_ordering), ...
    'Increasing the positive missing area must move the selected root downward.');
assert(max(central_hmf_delta(coarse_comparable)) < 2e-3, ...
    'Refined central roots disagree materially with the pre-wiring census.');
assert(all(E.phase_consistent(production_covered)));

% Strict-default oracle after implementation.  Match the retained 1 T census
% profile exactly and require the same node_failed/NaN verdict.
i1 = find(abs(fields-1) <= 1e-12,1);
strict_opts = C.result.options;
strict = invz_solve_point_ordered(invz_ion(),C.result.T,1,F.J,strict_opts);
reference = C.result.records(i1).profile;
strict_profile_match = isequaln(strict.hmf_prof.hgrid,reference.hgrid) && ...
    isequaln(strict.hmf_prof.r,reference.r) && ...
    isequaln(strict.hmf_prof.m,reference.m) && ...
    isequal(strict.hmf_prof.node_conv,reference.node_conv) && ...
    isequal(strict.hmf_prof.static_status,reference.static_status);
assert(isnan(strict.hmf) && strcmp(strict.hmf_status,'node_failed') && ...
    strcmp(strict.hmf_prof.integral_mode,'full_profile') && ...
    ~strict.production_approximation && ~strict.approximation_only && ...
    strict_profile_match, ...
    'Strict default changed after adding the approximation mode.');

unit = test_invzp_missing_area_integral();
result = struct('T',C.result.T,'fields',fields,'w',w, ...
    'area_factors',factors,'map',S, ...
    'covered_fields',fields(production_covered), ...
    'masked_fields',fields(~production_covered), ...
    'all_members_ordered',all_members_ordered, ...
    'all_frequency_complete',all_frequency_complete, ...
    'hmf_factor_ordering',hmf_factor_ordering, ...
    'central_hmf_delta_from_census',central_hmf_delta, ...
    'strict_default_profile_match',strict_profile_match, ...
    'strict_default_status',string(strict.hmf_status), ...
    'unit_test',unit, ...
    'interpretation',['The 129-node opt-in ensemble propagates missing-area ' ...
    'spread through the full real-axis susceptibility at 11/12 fields. The ' ...
    'coarse 33-node census missed the 0.2 T terminal component; independent ' ...
    '129/257 checks agree there. Conversely, 0.5 T has no terminal component ' ...
    'at 129 or 257 nodes and remains masked. An option-free strict solve is ' ...
    'bitwise equal to the retained pre-wiring profile oracle.']);
save(fullfile(here,'wp6_approximation_production_validation.mat'), ...
    'result','-v7.3');

fprintf(['production validation: covered %d/%d, all-member ordered %d, ' ...
    'all-frequency complete %d, strict profile match %d\n'], ...
    nnz(production_covered),numel(fields), ...
    all(all_members_ordered(production_covered)), ...
    all(all_frequency_complete(production_covered)),strict_profile_match);
for ib = 1:numel(fields)
    fprintf(['Bx %.3g phase [%d %d %d] hmf [%.8g %.8g %.8g] ' ...
        'central delta %.3g\n'],fields(ib),E.phase(:,ib), ...
        E.hmf(:,ib),central_hmf_delta(ib));
end
end
