function result = invzp_branch_area_ensemble_validation()
%INVZP_BRANCH_AREA_ENSEMBLE_VALIDATION Cross-check area and branch choices.
% Combine the strict-profile area census with independently continued exact
% sheets.  At 1 T, test whether any declared missing-area member reaches an
% equation-(45) root before the return sheet terminates at its uniform mass
% boundary.  This distinguishes a usable high-h Picard-attracting component
% from a locally admissible but production-incomplete return sheet.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
outer = fullfile(repo,'docs','diagnostics','invzp_outer_wp2');
C = load(fullfile(here,'wp6_approximation_census.mat'));
P = load(fullfile(outer,'wp2_local_field_potential_extension.mat'));
census = C.result;
sheet = P.result;
factors = census.area_factors;

edge_h = sheet.hgrid(1);
edge_r = sheet.r_low(1);
area_scale = edge_h*edge_r;
integral_low = cumtrapz(sheet.hgrid,sheet.r_low);
integral_high = cumtrapz(sheet.hgrid,sheet.r_high);
member = repmat(empty_member(),numel(factors),1);
for k = 1:numel(factors)
    area = factors(k)*area_scale;
    flow = area+integral_low-sheet.Jsup*sheet.moment;
    fhigh = area+integral_high-sheet.Jsup*sheet.moment;
    low_bracket = last_bracket(flow);
    high_bracket = last_bracket(fhigh);
    member(k) = struct('factor',factors(k),'area',area, ...
        'low_sheet_bracket',low_bracket, ...
        'return_sheet_bracket',high_bracket, ...
        'low_sheet_terminal_residual',flow(end), ...
        'return_sheet_terminal_residual',fhigh(end), ...
        'return_sheet_root_before_boundary',all(isfinite(high_bracket)));
end

two_root_mask = arrayfun(@(x)x.branch.multiplicity == 2,census.records);
one_root_mask = arrayfun(@(x)x.branch.multiplicity == 1,census.records);
area_coverage = arrayfun(@(x)all([x.members.bracketed]),census.records);
two_root_area_coverage = all(area_coverage(two_root_mask));
one_root_area_coverage = all(area_coverage(one_root_mask));
return_sheet_has_root = any([member.return_sheet_root_before_boundary]);

assert(two_root_area_coverage && one_root_area_coverage, ...
    'Declared area members must cover every independently labeled branch case.');
assert(~return_sheet_has_root, ...
    'The 1 T return sheet unexpectedly reached an ensemble root before its boundary.');
assert(all([member.return_sheet_terminal_residual] < 0));

result = struct('T',census.T,'Bx_sheet_test',sheet.Bx, ...
    'area_factors',factors,'fold_edge_h',edge_h,'fold_edge_r',edge_r, ...
    'fold_area_scale',area_scale,'members',member, ...
    'two_root_fields',census.fields(two_root_mask), ...
    'one_root_finite_search_fields',census.fields(one_root_mask), ...
    'two_root_area_coverage',two_root_area_coverage, ...
    'one_root_area_coverage',one_root_area_coverage, ...
    'return_sheet_has_root_before_boundary',return_sheet_has_root, ...
    'production_branch_assumption', ...
    "picard_attracting_contiguous_high_h_component", ...
    'interpretation',['The area ensemble brackets roots on the complete ' ...
    'certified high-h component at every covered census field. At 1 T the ' ...
    'exact return sheet remains negative for every member and terminates ' ...
    'at its uniform boundary before any equation-(45) root. An approximate ' ...
    'production solve can therefore use only the explicitly declared ' ...
    'Picard-attracting high-h component; it cannot silently switch to the ' ...
    'conditionally favored return sheet.']);
save(fullfile(here,'wp6_branch_area_ensemble_validation.mat'), ...
    'result','-v7');

fprintf(['branch/area validation: two-root fields %d, one-root controls %d, ' ...
    'return-sheet roots before boundary %d\n'],nnz(two_root_mask), ...
    nnz(one_root_mask),return_sheet_has_root);
for k = 1:numel(member)
    fprintf(['factor %.2f: fold-sheet terminal F low/high %.9g %.9g; ' ...
        'return bracket %d\n'],member(k).factor, ...
        member(k).low_sheet_terminal_residual, ...
        member(k).return_sheet_terminal_residual, ...
        member(k).return_sheet_root_before_boundary);
end
end

function bracket = last_bracket(f)
idx = find(f(1:end-1) < 0 & f(2:end) >= 0,1,'last');
if isempty(idx)
    bracket = [NaN NaN];
else
    bracket = [idx idx+1];
end
end

function m = empty_member()
m = struct('factor',NaN,'area',NaN,'low_sheet_bracket',[NaN NaN], ...
    'return_sheet_bracket',[NaN NaN], ...
    'low_sheet_terminal_residual',NaN, ...
    'return_sheet_terminal_residual',NaN, ...
    'return_sheet_root_before_boundary',false);
end
