function result = invzp_highfield_boundary_retry_contract_audit()
%INVZP_HIGHFIELD_BOUNDARY_RETRY_CONTRACT_AUDIT Audit the 4.68 T candidate.
% Diagnostic only.  Reconstruct the current 101-grid target directly from
% two independently accepted lower-field states, at 129 and 257 profile
% nodes, then compare the real-axis response.  No recovered target is reused
% as a seed and no production option is changed.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
C = invz_const();
T = 0.1;
J = F.J;
J0eff = F.info.Jcc0;
Jxx0 = F.info.Jaa0;
target_B = 4.68;
source_B = [4.50 4.59];
nH_values = [129 257];
area_factors = [0.75 1 1.5];
w_GHz = (0:0.01:6).';
w_meV = w_GHz*C.Gh2mV;
eta = 5e-5;
Jshape = 0;
if isfield(F.info,'Jshape_cc'), Jshape = F.info.Jshape_cc; end

[source_grid,resolution_grid] = ndgrid(source_B,nH_values);
source_points = cell(size(source_grid));
parfor k = 1:numel(source_points)
    source_points{k} = invz_solve_point_ordered(ion,T,source_grid(k),J, ...
        make_opts(J0eff,Jxx0,resolution_grid(k)));
end
assert(all(cellfun(@accepted,source_points),'all'), ...
    'Both lower-field sources must be independently accepted at each nH.');

target_points = cell(size(source_points));
parfor k = 1:numel(target_points)
    opts = make_opts(J0eff,Jxx0,resolution_grid(k));
    opts.hmf_profile_state_seed = state_seed(source_points{k});
    opts.hmf_profile_sweep_direction = 'descending';
    target_points{k} = invz_solve_point_ordered( ...
        ion,T,target_B,J,opts);
end

spectra = cell(size(target_points));
for k = 1:numel(target_points)
    p = target_points{k};
    if ~accepted(p), continue; end
    copts = struct('Jsel',J0eff,'eta',eta,'Jxx0',Jxx0, ...
        'Jshape',Jshape,'hyp',true,'si',p.si);
    out = invz_chi_realaxis(ion,T,target_B,p,w_meV,copts);
    spectra{k} = imag(out.chi_cc_q(1,:)).';
end

records = repmat(empty_record(),numel(target_points),1);
for k = 1:numel(target_points)
    records(k) = summarize(source_grid(k),resolution_grid(k), ...
        target_points{k},spectra{k},w_GHz,J,J0eff,area_factors);
end
summary = struct2table(records);

seed_comparison = repmat(empty_comparison(),numel(nH_values),1);
for in = 1:numel(nH_values)
    seed_comparison(in) = compare_pair(nH_values(in),"seed", ...
        target_points{1,in},target_points{2,in}, ...
        spectra{1,in},spectra{2,in},w_GHz);
end
seed_comparison = struct2table(seed_comparison);

resolution_comparison = repmat(empty_comparison(),numel(source_B),1);
for is = 1:numel(source_B)
    resolution_comparison(is) = compare_pair(source_B(is),"resolution", ...
        target_points{is,1},target_points{is,2}, ...
        spectra{is,1},spectra{is,2},w_GHz);
end
resolution_comparison = struct2table(resolution_comparison);

pm_production = invz_solve_point(ion,T,target_B,J,struct('J0eff',J0eff, ...
    'Jxx0',Jxx0,'mix_outer',0.35,'max_outer',2000));
pm_production_gate = pm_production.converged && ...
    isfinite(pm_production.crit) && pm_production.crit < 0;
pm_independent = invz_solve_point(ion,T,target_B,J,struct('J0eff',J0eff, ...
    'Jxx0',Jxx0,'mix_outer',0.25,'max_outer',1000));
pm_independent_gate = pm_independent.converged && ...
    isfinite(pm_independent.crit) && pm_independent.crit < 0;
all_targets_accepted = all(summary.converged);
all_spectra_finite = all(summary.spectrum_finite);
factor_one_supported = all(summary.factor_1_supported);
source_agreement_pass = all(seed_comparison.both_converged) && ...
    all(seed_comparison.hmf_delta < 1e-6) && ...
    all(seed_comparison.Sigma_delta < 1e-6) && ...
    all(seed_comparison.component_edge_delta < 1e-9);

result = struct('T',T,'target_B',target_B,'source_B',source_B, ...
    'nH_values',nH_values,'area_factors',area_factors, ...
    'frequency_GHz',w_GHz,'eta_meV',eta,'summary',summary, ...
    'spectra',{spectra}, ...
    'seed_comparison',seed_comparison, ...
    'resolution_comparison',resolution_comparison, ...
    'pm_production_converged',pm_production.converged, ...
    'pm_production_mass',pm_production.crit, ...
    'pm_production_negative_mass_gate',pm_production_gate, ...
    'pm_independent_converged',pm_independent.converged, ...
    'pm_independent_mass',pm_independent.crit, ...
    'pm_independent_negative_mass_gate',pm_independent_gate, ...
    'all_targets_accepted',all_targets_accepted, ...
    'all_spectra_finite',all_spectra_finite, ...
    'factor_one_supported',factor_one_supported, ...
    'source_agreement_pass',source_agreement_pass, ...
    'candidate_contract_pass',pm_production_gate && all_targets_accepted && ...
        all_spectra_finite && factor_one_supported && source_agreement_pass, ...
    'candidate_contract_pass_with_independent_pm', ...
        pm_independent_gate && all_targets_accepted && all_spectra_finite && ...
        factor_one_supported && source_agreement_pass, ...
    'production_changed',false, ...
    'interpretation',['The candidate contract applies only to the central ' ...
    'factor-one member at 4.68 T. Other area members remain independently ' ...
    'reported and may leave the ensemble interval incomplete.']);
save(fullfile(here,'wp6_highfield_boundary_retry_contract_audit.mat'), ...
    'result','-v7');

disp(summary(:,{'source_B','nH','status','converged','hmf','D_uni', ...
    'Fprime','final_resid','support_lo','support_hi', ...
    'factor_075_supported','factor_1_supported','factor_15_supported', ...
    'spectrum_finite','spectrum_max','peak_GHz','spectrum_integral'}));
disp(seed_comparison);
disp(resolution_comparison);
fprintf(['PM production converged %d, independent mass %.12g; ' ...
    'contract pass %d / independent-PM pass %d\n'], ...
    pm_production.converged,pm_independent.crit, ...
    result.candidate_contract_pass, ...
    result.candidate_contract_pass_with_independent_pm);
end

function opts = make_opts(J0eff,Jxx0,nH)
opts = struct('J0eff',J0eff,'Jxx0',Jxx0,'mix_outer',0.35, ...
    'max_outer',2000,'nH',nH, ...
    'hmf_integral_mode','missing_area_approx', ...
    'hmf_missing_area_factor',1, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component');
end

function tf = accepted(point)
tf = point.converged && point.is_ordered && isfinite(point.hmf);
end

function seed = state_seed(point)
seed = struct('Sigma',point.Sigma,'lambda',point.lambda,'K0',point.K(1));
end

function out = summarize(source_B,nH,point,spectrum,w_GHz,J,J0eff,factors)
out = empty_record();
out.source_B = source_B;
out.nH = nH;
out.status = string(point.hmf_status);
out.converged = accepted(point);
out.hmf = point.hmf;
out.D_uni = point.D_uni;
out.final_resid = point.final_resid;
if ~isempty(spectrum)
    out.spectrum_finite = all(isfinite(spectrum));
    out.spectrum_max = max(spectrum);
    out.peak_GHz = invz_peak_energy(spectrum,w_GHz,0);
    out.spectrum_integral = trapz(w_GHz,spectrum);
end
p = point.hmf_prof;
if isfield(p,'missing_area_integral') && ...
        p.missing_area_integral.node_count >= 2
    m = p.missing_area_integral;
    ix = m.selected_indices(:).';
    upper_integral = cumtrapz(p.hgrid(ix),p.r(ix));
    required_factor = (J0eff*p.m(ix)-upper_integral)/ ...
        (m.component_edge*m.edge_r);
    out.component_edge = m.component_edge;
    out.support_lo = min(required_factor);
    out.support_hi = max(required_factor);
    supported = factors >= out.support_lo & factors <= out.support_hi;
    out.factor_075_supported = supported(1);
    out.factor_1_supported = supported(2);
    out.factor_15_supported = supported(3);
end
if ~(out.converged && isfinite(p.r_star) && ...
        isfinite(p.Gstat_star) && isfinite(point.K(1)))
    return;
end
Gtilde = p.Gstat_star/(1-point.K(1)*p.Gstat_star);
out.Fprime = p.r_star*(1+J0eff*Gtilde);
out.supremum_mass = 1+J0eff*Gtilde;
out.min_mesh_x_mass = min(1+J(:)*Gtilde);
out.min_mesh_medium_mass = min(1+(J(:)-point.K(1))*p.Gstat_star);
end

function out = compare_pair(label,comparison,p1,p2,s1,s2,w_GHz)
out = empty_comparison();
out.label = label;
out.comparison = comparison;
out.both_converged = accepted(p1) && accepted(p2);
if ~out.both_converged || isempty(s1) || isempty(s2), return; end
out.hmf_delta = abs(p1.hmf-p2.hmf);
out.hmf_relative = out.hmf_delta/max(abs([p1.hmf p2.hmf]));
out.Sigma_delta = max(abs(p1.Sigma-p2.Sigma));
out.D_uni_delta = abs(p1.D_uni-p2.D_uni);
out.D_uni_relative = out.D_uni_delta/max(abs([p1.D_uni p2.D_uni]));
out.component_edge_delta = abs( ...
    p1.hmf_prof.missing_area_integral.component_edge- ...
    p2.hmf_prof.missing_area_integral.component_edge);
out.spectrum_max_abs_delta = max(abs(s1-s2));
out.spectrum_relative_delta = out.spectrum_max_abs_delta/ ...
    max(max(abs([s1(:);s2(:)])),realmin);
peak = invz_peak_energy([s1(:) s2(:)],w_GHz,0);
out.peak_delta_GHz = abs(diff(peak));
integral = [trapz(w_GHz,s1) trapz(w_GHz,s2)];
out.spectrum_integral_delta = abs(diff(integral));
out.spectrum_integral_relative = out.spectrum_integral_delta/ ...
    max(max(abs(integral)),realmin);
end

function out = empty_record()
out = struct('source_B',NaN,'nH',NaN,'status',"",'converged',false, ...
    'hmf',NaN,'D_uni',NaN,'Fprime',NaN,'final_resid',NaN, ...
    'component_edge',NaN,'support_lo',NaN,'support_hi',NaN, ...
    'factor_075_supported',false,'factor_1_supported',false, ...
    'factor_15_supported',false,'supremum_mass',NaN, ...
    'min_mesh_x_mass',NaN,'min_mesh_medium_mass',NaN, ...
    'spectrum_finite',false,'spectrum_max',NaN,'peak_GHz',NaN, ...
    'spectrum_integral',NaN);
end

function out = empty_comparison()
out = struct('label',NaN,'comparison',"",'both_converged',false, ...
    'hmf_delta',NaN,'hmf_relative',NaN,'Sigma_delta',NaN, ...
    'D_uni_delta',NaN,'D_uni_relative',NaN, ...
    'component_edge_delta',NaN,'spectrum_max_abs_delta',NaN, ...
    'spectrum_relative_delta',NaN,'peak_delta_GHz',NaN, ...
    'spectrum_integral_delta',NaN,'spectrum_integral_relative',NaN);
end
