function result = invzp_ordered_boundary_retry_smoke()
%INVZP_ORDERED_BOUNDARY_RETRY_SMOKE Production-map 4.68 T retry contract.
% The central missing-area member must be recovered directly from the two
% untouched lower ordered fields.  Unsupported members remain masked and the
% accepted PM field must never be retried.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));

ion = invz_ion();
T = 0.1;
fields = [4.50 4.59 4.68 4.77];
w = [0.001;0.003;0.006];
factors = [0.75 1 1.5];
solve_opts = struct('mix_outer',0.35,'max_outer',2000,'nH',129, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.35, ...
    'hmf_ordered_boundary_retry',true, ...
    'hmf_ordered_boundary_retry_max_span',0.20, ...
    'hmf_ordered_boundary_retry_min_D_uni',1e-3, ...
    'hmf_ordered_boundary_retry_min_Fprime',1e-3);
map_opts = struct('Jnu',F.J,'info',F.info,'parallel',true, ...
    'verbose',false,'eta',5e-3,'solve_opts',solve_opts);

S = invz_spectra_map(ion,T,fields,w,map_opts);
E = S.approximation_ensemble;
central = E.central_index;
target = find(fields == 4.68,1);
pm_index = find(fields == 4.77,1);
B = E.ordered_boundary_retry;

assert(isequal(E.phase(central,:),[1 1 1 2]), ...
    'The central factor must be ordered through 4.68 T and PM at 4.77 T.');
assert(B.attempted(central,target) && B.used(central,target) && ...
    B.status(central,target) == "used", ...
    'The central 4.68 T member did not pass the boundary retry.');
assert(max(abs(squeeze(B.source_fields(central,target,:)).'-[4.50 4.59])) ...
    < 8*eps, ...
    'The retry did not use the two frozen lower ordered fields.');
assert(B.pm_converged(central,target) && B.pm_mass(central,target) < 0, ...
    'The independently converged negative-PM-mass gate did not pass.');
assert(B.hmf_delta(central,target) < 1e-6 && ...
    B.Sigma_delta(central,target) < 1e-6 && ...
    B.component_edge_delta(central,target) < 1e-9 && ...
    B.D_uni_min(central,target) >= 1e-3 && ...
    B.Fprime_min(central,target) >= 1e-3, ...
    'The central target did not pass agreement and stability margins.');
assert(all(isfinite(E.chiz(:,target,central))), ...
    'The recovered central real-axis response is not finite.');
assert(~any(B.attempted(:,pm_index)) && ~any(B.used(:,pm_index)) && ...
    all(E.phase(:,pm_index) == 2), ...
    'A cold paramagnetic point must never be retried.');
assert(~any(B.used([1 3],target)), ...
    'Unsupported noncentral members must remain independently incomplete.');

result = struct('T',T,'fields',fields,'w',w,'factors',factors, ...
    'map',S,'interpretation',['Only the central 4.68 T member satisfies ' ...
    'the two-lower-source, independent-PM, agreement, and stability gates. ' ...
    'The area ensemble therefore reports an ordered central spectrum with ' ...
    'an honestly incomplete sensitivity interval.']);
save(fullfile(here,'wp6_ordered_boundary_retry_smoke.mat'),'result','-v7.3');
disp(array2table(E.phase,'VariableNames', ...
    {'B_450T','B_459T','B_468T','B_477T'}, ...
    'RowNames',compose('factor_%g',factors)));
disp(B.status);
end
