function result = invzp_approximation_census()
%INVZP_APPROXIMATION_CENSUS Census before any approximation production mode.
% Evaluate the unchanged strict ordered profile, isolate only its terminal
% contiguous certified component, and determine which explicit missing areas
% can place an equation-(45) root on that component.  The three shape factors
% correspond to continuous linear completions on [0,h_e]:
%
%   r(0)/r(h_e) = 0.5, 1, 2  ->  A/[h_e r(h_e)] = 0.75, 1, 1.5.
%
% They are a sensitivity ensemble, not probabilities or a thermodynamic
% derivation.  Saved exact-root audits provide independent branch labels.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));

fixture_path = fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat');
F = load(fixture_path);
ion = invz_ion();
T = 0.1;
fields = [0.2 0.3 0.4 0.5 0.6 0.8 1.0 1.2 2.5 2.7 2.9 3.0].';
area_factors = [0.75 1 1.5];
endpoint_ratios = 2*area_factors-1;
opts = struct('J0eff',F.info.Jcc0,'Jxx0',F.info.Jaa0, ...
    'mix_outer',0.25,'max_outer',1000,'nH',33);

branch = branch_evidence(repo,fields);
records = repmat(empty_record(numel(area_factors)),numel(fields),1);
for ib = 1:numel(fields)
    Bx = fields(ib);
    pt = invz_solve_point_ordered(ion,T,Bx,F.J,opts);
    p = pt.hmf_prof;
    certified = p.node_conv & isfinite(p.r) & isfinite(p.m);
    [~,component] = invz_missing_area_integral( ...
        p.hgrid,p.r,certified,1);
    members = repmat(empty_member(),numel(area_factors),1);
    area_scale = NaN;
    area_required_range = [NaN NaN];
    factor_support = [NaN NaN];
    if component.node_count >= 2
        ix = component.selected_indices(:).';
        area_scale = component.component_edge*component.edge_r;
        certified_integral = cumtrapz(p.hgrid(ix),p.r(ix));
        area_required = F.info.Jcc0*p.m(ix)-certified_integral;
        area_required_range = [min(area_required) max(area_required)];
        factor_support = area_required_range/area_scale;
        for ia = 1:numel(area_factors)
            area = area_factors(ia)*area_scale;
            [h0,meta] = invz_missing_area_integral( ...
                p.hgrid,p.r,certified,area);
            residual = h0-F.info.Jcc0*p.m;
            pair = meta.selected_mask(1:end-1) & ...
                meta.selected_mask(2:end) & residual(1:end-1) < 0 & ...
                residual(2:end) >= 0;
            bracket = find(pair,1,'last');
            if isempty(bracket)
                members(ia) = struct('factor',area_factors(ia), ...
                    'origin_edge_ratio',endpoint_ratios(ia),'area',area, ...
                    'bracketed',false,'bracket_indices',[NaN NaN], ...
                    'coarse_hmf',NaN,'coarse_moment',NaN);
            else
                t = -residual(bracket)/ ...
                    (residual(bracket+1)-residual(bracket));
                hmf = p.hgrid(bracket)+t* ...
                    (p.hgrid(bracket+1)-p.hgrid(bracket));
                moment = p.m(bracket)+t* ...
                    (p.m(bracket+1)-p.m(bracket));
                members(ia) = struct('factor',area_factors(ia), ...
                    'origin_edge_ratio',endpoint_ratios(ia),'area',area, ...
                    'bracketed',true, ...
                    'bracket_indices',[bracket bracket+1], ...
                    'coarse_hmf',hmf,'coarse_moment',moment);
            end
        end
    end
    records(ib) = struct('Bx',Bx,'strict_status',string(p.status), ...
        'strict_hmf',pt.hmf,'component',component, ...
        'area_scale',area_scale, ...
        'area_required_range',area_required_range, ...
        'factor_support',factor_support,'members',members, ...
        'branch',branch(ib),'profile',compact_profile(p));
    fprintf(['census Bx %.3g strict %s nodes %d h_e %.8g ' ...
        'factor support [%.5g %.5g] brackets %d/%d branch %s\n'], ...
        Bx,p.status,component.node_count,component.component_edge, ...
        factor_support(1),factor_support(2),sum([members.bracketed]), ...
        numel(members),branch(ib).label);
end

B = fields;
strict_status = string({records.strict_status}).';
component_nodes = arrayfun(@(x)x.component.node_count,records);
component_edge = arrayfun(@(x)x.component.component_edge,records);
edge_r = arrayfun(@(x)x.component.edge_r,records);
area_scale = [records.area_scale].';
factor_min = arrayfun(@(x)x.factor_support(1),records);
factor_max = arrayfun(@(x)x.factor_support(2),records);
ensemble_bracket_count = arrayfun(@(x)sum([x.members.bracketed]),records);
branch_multiplicity = [branch.multiplicity].';
branch_label = string({branch.label}).';
summary = table(B,strict_status,component_nodes,component_edge,edge_r, ...
    area_scale,factor_min,factor_max,ensemble_bracket_count, ...
    branch_multiplicity,branch_label);

strict_default_unchanged = all(isnan([records.strict_hmf])) && ...
    all(strict_status == "node_failed");
covered = component_nodes >= 2;
ensemble_coverage = ensemble_bracket_count == numel(area_factors);
assert(strict_default_unchanged, ...
    'The census must not turn a strict masked result into an accepted root.');
assert(~covered(fields == 0.2), ...
    'The 0.2 T coverage failure is a required regression case.');
assert(all(ensemble_coverage(covered)), ...
    'Every retained component must bracket all declared ensemble members.');
assert(all(arrayfun(@(x)x.component.interior_bridge_count, ...
    records(covered)) == 0));

result = struct('T',T,'fields',fields,'area_factors',area_factors, ...
    'origin_edge_ratios',endpoint_ratios,'options',opts, ...
    'records',records,'summary',summary, ...
    'strict_default_unchanged',strict_default_unchanged, ...
    'component_coverage',covered, ...
    'ensemble_coverage',ensemble_coverage, ...
    'fixture',fixture_path, ...
    'interpretation',['The area factors parameterize three explicit ' ...
    'continuous positive linear completions below the certified edge. ' ...
    'They measure sensitivity and do not select equilibrium. Exact branch ' ...
    'multiplicity labels are imported only at independently audited fields.']);
save(fullfile(here,'wp6_approximation_census.mat'),'result','-v7');
disp(summary);
end

function out = compact_profile(p)
out = struct('hgrid',p.hgrid,'r',p.r,'m',p.m,'node_conv',p.node_conv, ...
    'static_status',p.static_status,'D_uni',p.D_uni, ...
    'predictor_static_status',p.predictor_static_status);
end

function branch = branch_evidence(repo,fields)
outer = fullfile(repo,'docs','diagnostics','invzp_outer_wp2');
L = load(fullfile(outer,'wp2_lowfield_02_branch_extension.mat'));
C = load(fullfile(outer,'wp2_multifield_crossfield_continuation.mat'));
H = load(fullfile(outer,'wp2_highfield_exact_section_audit.mat'));
branch = repmat(struct('multiplicity',NaN,'label',"not_audited_here", ...
    'source',""),numel(fields),1);
for ib = 1:numel(fields)
    Bx = fields(ib);
    il = find(abs([L.result.summary.Bx]-Bx) <= 1e-12,1);
    if ~isempty(il)
        if L.result.summary(il).reached
            branch(ib) = struct('multiplicity',2, ...
                'label',"two_exact_roots",'source',string(L.result.source_crossfield));
        else
            branch(ib) = struct('multiplicity',0, ...
                'label',"no_continued_root_on_extrapolated_section", ...
                'source',string(L.result.source_crossfield));
        end
    end
    ic = find(abs([C.result.anchor_summary.Bx]-Bx) <= 1e-12,1);
    if ~isempty(ic) && C.result.anchor_summary(ic).reached
        branch(ib) = struct('multiplicity',2, ...
            'label',"two_exact_roots",'source',string(C.result.source));
    end
    ih = find(abs([H.result.audits.Bx]-Bx) <= 1e-12,1);
    if ~isempty(ih)
        branch(ib) = struct('multiplicity',1, ...
            'label',"one_root_found_finite_search", ...
            'source',string(H.result.source));
    end
end
end

function r = empty_record(nmember)
r = struct('Bx',NaN,'strict_status',"",'strict_hmf',NaN, ...
    'component',struct(),'area_scale',NaN, ...
    'area_required_range',[NaN NaN],'factor_support',[NaN NaN], ...
    'members',repmat(empty_member(),nmember,1),'branch',struct(), ...
    'profile',struct());
end

function m = empty_member()
m = struct('factor',NaN,'origin_edge_ratio',NaN,'area',NaN, ...
    'bracketed',false,'bracket_indices',[NaN NaN], ...
    'coarse_hmf',NaN,'coarse_moment',NaN);
end
