function result = invzp_adjacent_field_seed_audit()
%INVZP_ADJACENT_FIELD_SEED_AUDIT Test field-neighbour state continuation.
% The target retains every production gate.  Only the initial full ordered
% state and profile sweep direction change; seed proximity is never an
% acceptance condition.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
J = F.J;
J0eff = F.info.Jcc0;
Jxx0 = F.info.Jaa0;
ion = invz_ion();
T = 0.1;
source_fields = [0.27 0.54];
target_field = 0.45;
nH = 129;
area_factors = [0.75 1 1.5];
[source_B,area_factor] = ndgrid(source_fields,area_factors);
base = struct('J0eff',J0eff,'Jxx0',Jxx0, ...
    'mix_outer',0.25,'max_outer',1000,'nH',nH, ...
    'hmf_integral_mode','missing_area_approx', ...
    'hmf_missing_area_factor',1, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component');

sources = cell(size(source_B));
parfor k = 1:numel(source_B)
    opts = base;
    opts.hmf_missing_area_factor = area_factor(k);
    sources{k} = invz_solve_point_ordered( ...
        ion,T,source_B(k),J,opts);
end
assert(all(cellfun(@(p)p.converged,sources),'all'), ...
    'Every adjacent-field seed source must be accepted first.');

targets = cell(size(source_B));
parfor k = 1:numel(source_B)
    opts = base;
    opts.hmf_missing_area_factor = area_factor(k);
    p = sources{k};
    opts.hmf_profile_state_seed = struct( ...
        'Sigma',p.Sigma,'lambda',p.lambda,'K0',p.K(1));
    opts.hmf_profile_sweep_direction = 'descending';
    targets{k} = invz_solve_point_ordered( ...
        ion,T,target_field,J,opts);
end

records = repmat(struct('source_B',NaN,'area_factor',NaN,'source_hmf',NaN, ...
    'target_status',"",'target_converged',false,'target_hmf',NaN, ...
    'component_nodes',0,'component_edge',NaN, ...
    'profile_seeded',false,'sweep_direction',""), ...
    numel(source_B),1);
for k = 1:numel(source_B)
    p = targets{k};
    m = p.hmf_prof.missing_area_integral;
    records(k) = struct('source_B',source_B(k), ...
        'area_factor',area_factor(k), ...
        'source_hmf',sources{k}.hmf, ...
        'target_status',string(p.hmf_status), ...
        'target_converged',p.converged,'target_hmf',p.hmf, ...
        'component_nodes',m.node_count,'component_edge',m.component_edge, ...
        'profile_seeded',p.hmf_prof.profile_state_seeded, ...
        'sweep_direction',string(p.hmf_prof.profile_sweep_direction));
end

agreement = repmat(struct('area_factor',NaN,'both_converged',false, ...
    'hmf_delta',NaN,'Sigma_delta',NaN,'component_edge_delta',NaN, ...
    'accepted',false),numel(area_factors),1);
for j = 1:numel(area_factors)
    lo = targets{1,j};
    hi = targets{2,j};
    hmf_delta = abs(lo.hmf-hi.hmf);
    Sigma_delta = max(abs(lo.Sigma-hi.Sigma));
    edge_delta = abs(lo.hmf_prof.missing_area_integral.component_edge- ...
        hi.hmf_prof.missing_area_integral.component_edge);
    both = lo.converged && hi.converged;
    agreement(j) = struct('area_factor',area_factors(j), ...
        'both_converged',both,'hmf_delta',hmf_delta, ...
        'Sigma_delta',Sigma_delta,'component_edge_delta',edge_delta, ...
        'accepted',both && hmf_delta < 1e-6 && Sigma_delta < 1e-6 && ...
        edge_delta < 1e-10);
end

result = struct('T',T,'nH',nH,'source_fields',source_fields, ...
    'target_field',target_field,'area_factors',area_factors, ...
    'records',records,'agreement',agreement,'sources',{sources}, ...
    'targets',{targets},'interpretation',['Adjacent-field warm starts alter ' ...
    'only the numerical continuation path. A recovered state is usable only ' ...
    'if the unchanged component, root, static, and final residual gates pass.']);
save(fullfile(here,'wp6_adjacent_field_seed_audit.mat'),'result','-v7');
disp(struct2table(records));
disp(struct2table(agreement));
end
