function result = invzp_adjacent_retry_map_smoke()
%INVZP_ADJACENT_RETRY_MAP_SMOKE Production-map smoke test at 129 nodes.
% The two cold-pass low-field masks must be recovered independently from
% the same frozen accepted neighbors for every missing-area ensemble member.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));

ion = invz_ion();
T = 0.1;
fields = [0.27 0.36 0.45 0.54];
w = [0.001; 0.003; 0.006];
factors = [0.75 1 1.5];
solve_opts = struct('mix_outer',0.25,'max_outer',1000,'nH',129, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.30);
map_opts = struct('Jnu',F.J,'info',F.info,'parallel',true, ...
    'verbose',false,'eta',5e-3,'solve_opts',solve_opts);

S = invz_spectra_map(ion,T,fields,w,map_opts);
E = S.approximation_ensemble;
target = ismember(fields,[0.36 0.45]);
source = ~target;
assert(all(E.phase == 1,'all'), ...
    'Every ensemble member must be ordered after the adjacent-field retry.');
assert(all(E.phase_consistent), ...
    'The recovered phase labels must agree across missing-area factors.');
assert(all(E.chiz_complete,'all'), ...
    'The recovered susceptibility ensemble must be complete.');
assert(all(E.adjacent_retry.attempted(:,target),'all') && ...
    all(E.adjacent_retry.used(:,target),'all'), ...
    'Both target fields must be attempted and recovered for every factor.');
assert(~any(E.adjacent_retry.attempted(:,source),'all') && ...
    ~any(E.adjacent_retry.used(:,source),'all'), ...
    'Accepted cold-pass source fields must not be retried.');
expected_sources = repmat(reshape([0.27 0.54],1,1,2), ...
    numel(factors),nnz(target),1);
assert(max(abs(E.adjacent_retry.source_fields(:,target,:) - ...
    expected_sources),[],'all') < 8*eps, ...
    'Every retry must use the frozen 0.27 T and 0.54 T source states.');
assert(max(E.adjacent_retry.hmf_delta(:,target),[],'all') < 1e-6 && ...
    max(E.adjacent_retry.Sigma_delta(:,target),[],'all') < 1e-6 && ...
    max(E.adjacent_retry.component_edge_delta(:,target),[],'all') < 1e-9, ...
    'Independently seeded retry states must satisfy the agreement gates.');

result = struct('T',T,'fields',fields,'w',w,'factors',factors, ...
    'map',S,'interpretation',['At 129 profile nodes, 0.36 T and 0.45 T ' ...
    'are admitted only after independent left/right warm starts agree; the ' ...
    'accepted 0.27 T and 0.54 T cold-pass states remain unchanged.']);
save(fullfile(here,'wp6_adjacent_retry_map_smoke.mat'),'result','-v7');
disp(table(fields.',S.phase.',all(E.phase == 1,1).', ...
    any(E.adjacent_retry.used,1).', ...
    'VariableNames',{'B_T','central_phase','all_members_ordered','retry_used'}));
end
