function result = invzp_zero_field_ensemble_validation()
%INVZP_ZERO_FIELD_ENSEMBLE_VALIDATION End-to-end exact-zero approximation.
% Exercise every declared missing-area member and the real-axis response on a
% short B->0+ ladder. Strict full_profile remains masked at exactly zero.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
C = invz_const();
T = 0.1;
fields = [0 1e-6 1e-4 0.01 0.09];
factors = [0.75 1 1.5];
w_GHz = (0:0.01:6).';
w = w_GHz*C.Gh2mV;
solve_opts = struct('mix_outer',0.35,'max_outer',2000,'nH',129, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.35);
map_opts = struct('Jnu',F.J,'info',F.info,'parallel',true, ...
    'verbose',false,'eta',5e-5,'solve_opts',solve_opts);
S = invz_spectra_map(ion,T,fields,w,map_opts);
E = S.approximation_ensemble;

i0 = 1;
i1 = 2;
phase_complete = all(E.phase == 1,1);
spectrum_complete = all(E.chiz_complete,1);
zero_spectrum_delta = squeeze(max(abs( ...
    E.chiz(:,i0,:)-E.chiz(:,i1,:)),[],1));
zero_hmf_delta = abs(E.hmf(:,i0)-E.hmf(:,i1));
zero_sigma_delta = abs(E.Sigma0(:,i0)-E.Sigma0(:,i1));
hmf_factor_ordering = all(diff(E.hmf(:,phase_complete),1,1) < 0,1);

strict_opts = struct('J0eff',F.info.Jcc0,'Jxx0',F.info.Jaa0, ...
    'mix_outer',0.35,'max_outer',2000,'nH',33);
strict = invz_solve_point_ordered(ion,T,0,F.J,strict_opts);

assert(all(phase_complete) && all(spectrum_complete), ...
    'Every exact-zero ladder member must export a finite ordered spectrum.');
assert(all(hmf_factor_ordering), ...
    'Increasing missing area must move every selected root downward.');
assert(all(zero_hmf_delta < 1e-8) && all(zero_sigma_delta < 1e-8) && ...
    all(zero_spectrum_delta < 1e-10), ...
    'The exact-zero ensemble is not continuous to 1e-6 T.');
assert(~any(E.adjacent_retry.used(:,i0)) && ...
    ~any(E.adjacent_retry.attempted(:,i0)), ...
    'Exact zero must not be supplied by an adjacent-field retry.');
assert(~strict.converged && isnan(strict.hmf) && ...
    strcmp(strict.hmf_status,'node_failed') && ...
    strict.hmf_prof.predictor_static_status == "twolevel_domain_invalid", ...
    'The option-free strict exact-zero solve must remain fail-closed.');

peak_censored = isnan(E.Epeak(:,i0));
result = struct('T',T,'fields',fields,'factors',factors, ...
    'w_meV',w,'w_GHz',w_GHz,'map',S, ...
    'phase_complete',phase_complete, ...
    'spectrum_complete',spectrum_complete, ...
    'zero_hmf_delta_from_1e_6T',zero_hmf_delta, ...
    'zero_Sigma0_delta_from_1e_6T',zero_sigma_delta, ...
    'zero_spectrum_max_abs_delta_from_1e_6T',zero_spectrum_delta, ...
    'zero_peak_censored',peak_censored, ...
    'zero_peak_status',"no_interior_peak_in_0_to_6_GHz_window", ...
    'strict_status',string(strict.hmf_status), ...
    'strict_predictor_status',strict.hmf_prof.predictor_static_status, ...
    'production_approximation_only',true);
save(fullfile(here,'wp6_zero_field_ensemble_validation.mat'), ...
    'result','-v7.3');
fprintf(['zero-field ensemble: phase complete %d, spectra complete %d, ' ...
    'max |Delta hmf| %.3g, max |Delta chi| %.3g, strict %s\n'], ...
    all(phase_complete),all(spectrum_complete),max(zero_hmf_delta), ...
    max(zero_spectrum_delta),strict.hmf_status);
disp(table(factors(:),E.hmf(:,i0),E.Sigma0(:,i0),E.D_ord(:,i0), ...
    E.Epeak(:,i0),peak_censored, ...
    'VariableNames',{'factor','hmf','Sigma0','D_uni','peak_meV', ...
    'peak_censored'}));
end
