function result = invzp_adjacent_retry_map_smoke()
%INVZP_ADJACENT_RETRY_MAP_SMOKE Production-map smoke test at 129 nodes.
% The exact bare-MF ceiling makes the factor-one 0.36 T point converge cold;
% its 0.45 T point must still recover independently from the same frozen
% accepted neighbors. Sensitivity members may either converge on the cold
% pass or satisfy the same retry gate.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));

ion = invz_ion();
T = 0.1;
fields = [0.27 0.36 0.45 0.54];
w = [0.001; 0.003; 0.006];
factors = [0.75 1 1.5];
solve_opts = struct('mix_outer',0.25,'max_outer',1000,'nH',129, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.30);
map_opts = struct('Jnu',F.J,'info',F.info,'parallel',true, ...
    'verbose',false,'eta',5e-3,'solve_opts',solve_opts);

S = invz_spectra_map(ion,T,fields,w,map_opts);
E = S.approximation_ensemble;
target = ismember(fields,[0.36 0.45]);
source = ~target;
assert(all(E.phase == 1,'all'), ...
    'Every ensemble member must be ordered after the adjacent-field retry.');
assert(all(E.phase_consistent), ...
    'The recovered phase labels must agree across missing-area factors.');
assert(all(E.chiz_complete,'all'), ...
    'The recovered susceptibility ensemble must be complete.');
central = E.central_index;
assert(isequal(E.adjacent_retry.attempted(central,target),[false true]) && ...
    isequal(E.adjacent_retry.used(central,target),[false true]), ...
    ['The factor-one member must converge cold at 0.36 T and recover ' ...
     '0.45 T through the adjacent retry.']);
assert(isequal(E.adjacent_retry.attempted(:,target), ...
    E.adjacent_retry.used(:,target)), ...
    'Every attempted sensitivity-member retry must be recovered.');
assert(~any(E.adjacent_retry.attempted(:,source),'all') && ...
    ~any(E.adjacent_retry.used(:,source),'all'), ...
    'Accepted cold-pass source fields must not be retried.');
targetIndex = find(target);
centralSources = reshape(E.adjacent_retry.source_fields(central,targetIndex(2),:),1,2);
assert(max(abs(centralSources-[0.36 0.54])) < 8*eps, ...
    'Factor-one 0.45 T must use the frozen 0.36 T and 0.54 T sources.');
for member = 1:numel(factors)
    for k = targetIndex
        if E.adjacent_retry.attempted(member,k)
            sources = reshape( ...
                E.adjacent_retry.source_fields(member,k,:),1,2);
            assert(sources(1) < fields(k) && fields(k) < sources(2) && ...
                sources(2)-sources(1) <= 0.30+8*eps, ...
                'Every attempted retry must use nearby bracketing sources.');
        end
    end
end
assert(max(E.adjacent_retry.hmf_delta(:,target),[],'all','omitnan') < 1e-6 && ...
    max(E.adjacent_retry.Sigma_delta(:,target),[],'all','omitnan') < 1e-6 && ...
    max(E.adjacent_retry.component_edge_delta(:,target),[],'all','omitnan') < 1e-9, ...
    'Independently seeded retry states must satisfy the agreement gates.');

result = struct('T',T,'fields',fields,'w',w,'factors',factors, ...
    'map',S,'interpretation',['At 129 profile nodes, factor-one 0.36 T ' ...
    'converges cold while 0.45 T is admitted only after independent ' ...
    'left/right warm starts agree. A sensitivity member may also converge ' ...
    'cold. Every retry source is an immutable cold accepted state.']);
save(fullfile(here,'wp6_adjacent_retry_map_smoke.mat'),'result','-v7');
disp(table(fields.',S.phase.',all(E.phase == 1,1).', ...
    any(E.adjacent_retry.used,1).', ...
    'VariableNames',{'B_T','central_phase','all_members_ordered','retry_used'}));
end
