function result = invzp_zero_field_resolution_audit()
%INVZP_ZERO_FIELD_RESOLUTION_AUDIT Compare 129/257 exact-zero ensembles.
% The missing-area spread and profile-node systematic remain separate.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
base_path = fullfile(here,'wp6_zero_field_ensemble_validation.mat');
Q = load(base_path);
R129 = Q.result;
assert(isequal(R129.fields,[0 1e-6 1e-4 0.01 0.09]) && ...
    isequal(R129.factors,[0.75 1 1.5]), ...
    'The retained 129-node zero-field ensemble configuration changed.');

F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
factors = R129.factors;
solve_opts = struct('mix_outer',0.35,'max_outer',2000,'nH',257, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.35);
map_opts = struct('Jnu',F.J,'info',F.info,'parallel',true, ...
    'verbose',false,'eta',5e-5, ...
    'solve_opts',solve_opts);
S257 = invz_spectra_map(ion,R129.T,0,R129.w_meV,map_opts);
E129 = R129.map.approximation_ensemble;
E257 = S257.approximation_ensemble;

hmf_delta = abs(E257.hmf(:,1)-E129.hmf(:,1));
Sigma0_delta = abs(E257.Sigma0(:,1)-E129.Sigma0(:,1));
D_uni_delta = abs(E257.D_ord(:,1)-E129.D_ord(:,1));
edge_delta = abs(E257.component_edge(:,1)-E129.component_edge(:,1));
spectrum_delta = squeeze(max(abs( ...
    E257.chiz(:,1,:)-E129.chiz(:,1,:)),[],1));

assert(all(E257.phase(:,1) == 1) && E257.phase_consistent(1) && ...
    E257.chiz_complete(1), ...
    'Every 257-node exact-zero member must export a finite ordered spectrum.');
assert(all(hmf_delta < 2e-4) && all(Sigma0_delta < 1e-6) && ...
    all(D_uni_delta < 1e-6) && all(spectrum_delta < 1e-8), ...
    'The exact-zero 129/257 profile systematic exceeds its declared gate.');

result = struct('T',R129.T,'factors',factors, ...
    'nH_values',[129 257],'map_257',S257, ...
    'hmf_delta',hmf_delta,'Sigma0_delta',Sigma0_delta, ...
    'D_uni_delta',D_uni_delta,'component_edge_delta',edge_delta, ...
    'spectrum_max_abs_delta',spectrum_delta, ...
    'base_129_artifact',base_path, ...
    'interpretation',['The node-resolution systematic is retained ' ...
    'separately from the missing-area member spread.']);
save(fullfile(here,'wp6_zero_field_resolution_audit.mat'), ...
    'result','-v7.3');
disp(table(factors(:),E129.hmf(:,1),E257.hmf(:,1),hmf_delta, ...
    Sigma0_delta,D_uni_delta,edge_delta,spectrum_delta, ...
    'VariableNames',{'factor','hmf_129','hmf_257','hmf_delta', ...
    'Sigma0_delta','D_uni_delta','edge_delta','spectrum_max_abs_delta'}));
end
