function result = invzp_adjacent_retry_highfield_smoke()
%INVZP_ADJACENT_RETRY_HIGHFIELD_SMOKE Check that retry cannot bridge Bc.
% At 4.68 T there is no accepted ordered source above the target; the
% adjacent-field policy must therefore leave the cold-pass mask unchanged.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));

ion = invz_ion();
T = 0.1;
fields = [4.59 4.68 4.77];
w = [0.001; 0.003; 0.006];
factors = [0.75 1 1.5];
solve_opts = struct('mix_outer',0.25,'max_outer',1000,'nH',129, ...
    'hmf_integral_mode','missing_area_ensemble', ...
    'hmf_missing_area_factors',factors, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.30);
map_opts = struct('Jnu',F.J,'info',F.info,'parallel',true, ...
    'verbose',false,'eta',5e-3,'solve_opts',solve_opts);

S = invz_spectra_map(ion,T,fields,w,map_opts);
E = S.approximation_ensemble;
expected_phase = [0 0 2; 1 0 2; 0 0 2];
assert(isequal(E.phase,expected_phase), ...
    'The high-field cold-pass phase matrix changed unexpectedly.');
assert(~any(E.adjacent_retry.attempted,'all') && ...
    ~any(E.adjacent_retry.used,'all'), ...
    'A high-field retry must not be attempted without ordered sources on both sides.');
assert(all(isnan(E.chiz(:,fields == 4.68,:)),'all'), ...
    'The unsupported 4.68 T ensemble column must remain masked.');

result = struct('T',T,'fields',fields,'w',w,'factors',factors, ...
    'map',S,'interpretation',['The two-sided adjacent-field policy cannot ' ...
    'bridge the ordered/PM boundary. The 4.68 T mask remains visible, and ' ...
    'the 4.77 T point remains paramagnetic for every area factor.']);
save(fullfile(here,'wp6_adjacent_retry_highfield_smoke.mat'),'result','-v7');
disp(array2table(E.phase,'VariableNames', ...
    {'B_459T','B_468T','B_477T'},'RowNames',compose('factor_%g',factors)));
end
