function fx = invz_ewald_fixtures()
%INVZ_EWALD_FIXTURES Frozen deterministic Ewald test fixtures (Step-4 Task 3).
%   fx = INVZ_EWALD_FIXTURES() returns the exact frozen samples of
%   docs/invzp_ewald_prereg.md sec 3 ("Frozen deterministic samples"),
%   consumed by every later Gate-A/B/C task test. Plain fixture function (NOT
%   a test; runtests on tests/ is non-recursive and does not collect it --
%   the invz_odd_anchors.m precedent). Every cardinality/uniqueness the
%   prereg fixes is asserted here (fail fast) so a malformed sample cannot
%   silently reduce downstream test coverage.
%
% FIELDS
%   q_int          [3,3]   the three frozen generic reduced wavevectors.
%   delta_q        scalar  candidate-boundary probe offset, 2^-40.
%   QA             [30,3]  Gamma + q_int(3) + face(6) + edge(12) + corner(8).
%   Kset           [8,3]   frozen reciprocal translations.
%   origin_shift   [1,3]   common fractional-origin shift.
%   bravais_shifts {1,2}   representative per-basis Bravais shifts.
%   hess_x         [200,3] screened-Hessian sample vectors (exact frozen RNG
%                          order; see below).
%   shell_fixture  struct  explicit two-site small-shell sign/phase fixture.
%   alpha0         scalar  sqrt(pi)/abs(det(invz_ion().a))^(1/3), computed
%                          LIVE -- never the displayed rounded 0.268431.
%
% The 200 Hessian sample vectors are generated by, in this EXACT order:
%   rng(20260724,'twister'); U=randn(200,3); row-normalize U;
%   p=randperm(200)'; r=exp(linspace(log(0.4),log(6),200))'; x=U.*r(p);
% i.e. 200 random unit directions (row-normalized randn draws) independently
% reshuffled (via the permutation p) onto a deterministic log-spaced radius
% ladder from 0.4 to 6 Angstrom.

% ---- frozen generic reduced-coordinate wavevectors (prereg sec 3) -----------
fx.q_int = [ 0.137   0.291   0.453
            -0.311   0.173  -0.227
             0.25    0       0.1  ];
assert_rows_unique(fx.q_int, 3, 'fx.q_int');

% ---- candidate-boundary probe scalar + the two boundary values -------------
fx.delta_q = 2^-40;
lo = -0.5;
hi = 0.5 - fx.delta_q;

% ---- corner probes: all 8 combinations of {lo, hi} per axis -----------------
[c1, c2, c3] = ndgrid([lo hi], [lo hi], [lo hi]);
corners = [c1(:) c2(:) c3(:)];
assert_rows_unique(corners, 8, 'corner probes');

% ---- face probes: fix one axis in turn to a boundary value; the other two --
% components equal 0.137 and 0.291 respectively (ascending remaining-axis
% order: the lower-index remaining axis gets 0.137, the higher gets 0.291).
face = zeros(6, 3);
row = 0;
for axis = 1:3
    others = setdiff(1:3, axis);   % ascending order, e.g. axis=2 -> [1 3]
    for val = [lo hi]
        row = row + 1;
        v = zeros(1,3);
        v(axis)      = val;
        v(others(1)) = 0.137;
        v(others(2)) = 0.291;
        face(row,:) = v;
    end
end
assert_rows_unique(face, 6, 'face probes');

% ---- edge probes: one free axis at 0.173; the other two independently at --
% {lo, hi} (all 4 combinations), for each of the 3 choices of free axis.
edge = zeros(12, 3);
row = 0;
for axis = 1:3
    others = setdiff(1:3, axis);
    for v2 = [lo hi]
        for v3 = [lo hi]
            row = row + 1;
            v = zeros(1,3);
            v(axis)      = 0.173;
            v(others(1)) = v2;
            v(others(2)) = v3;
            edge(row,:) = v;
        end
    end
end
assert_rows_unique(edge, 12, 'edge probes');

% ---- Q_A = Gamma + q_int + face + edge + corner -----------------------------
fx.QA = [0 0 0; fx.q_int; face; edge; corners];
assert_rows_unique(fx.QA, 30, 'fx.QA');

% ---- eight frozen reciprocal translations -----------------------------------
fx.Kset = [ 1  0  0
           -1  0  0
            0  1  0
            0 -1  0
            0  0  1
            0  0 -1
            1 -2  3
           -2  1 -1];
assert_rows_unique(fx.Kset, 8, 'fx.Kset');

% ---- common fractional-origin shift -----------------------------------------
fx.origin_shift = [0.137 -0.211 0.089];

% ---- representative per-basis Bravais shifts --------------------------------
fx.bravais_shifts = {[1 0 0], [0 -1 1]};

% ---- 200 deterministic screened-Hessian sample vectors (EXACT frozen order) -
rng(20260724, 'twister');
U = randn(200, 3);
U = U ./ vecnorm(U, 2, 2);          % row-normalize to unit directions
p = randperm(200)';
r = exp(linspace(log(0.4), log(6), 200))';
fx.hess_x = U .* r(p);
assert_rows_unique(fx.hess_x, 200, 'fx.hess_x');
assert(all(isfinite(fx.hess_x(:))), 'invz_ewald_fixtures: hess_x must be finite.');
assert(all(vecnorm(fx.hess_x, 2, 2) > 0), 'invz_ewald_fixtures: hess_x must have |x|>0 everywhere.');

% ---- explicit two-site small-shell sign/phase fixture -----------------------
fx.shell_fixture = struct( ...
    'a',     diag([3.1 4.2 5.3]), ...
    'tau',   [0 0 0; 0.23 0.31 0.17], ...
    'alpha', 0.27, ...
    'r_cut', 18.0, ...
    'q',     [0.17 -0.23 0.29]);
assert(isequal(size(fx.shell_fixture.a), [3 3]) && all(isfinite(fx.shell_fixture.a(:))), ...
    'invz_ewald_fixtures: shell_fixture.a must be a finite [3,3] matrix.');
assert(isequal(size(fx.shell_fixture.tau), [2 3]) && all(isfinite(fx.shell_fixture.tau(:))), ...
    'invz_ewald_fixtures: shell_fixture.tau must be a finite [2,3] matrix.');
assert(isscalar(fx.shell_fixture.alpha) && fx.shell_fixture.alpha > 0, ...
    'invz_ewald_fixtures: shell_fixture.alpha must be a positive scalar.');
assert(isscalar(fx.shell_fixture.r_cut) && fx.shell_fixture.r_cut > 0, ...
    'invz_ewald_fixtures: shell_fixture.r_cut must be a positive scalar.');
assert(isequal(size(fx.shell_fixture.q), [1 3]) && all(isfinite(fx.shell_fixture.q)), ...
    'invz_ewald_fixtures: shell_fixture.q must be a finite [1,3] row.');

% ---- live alpha0 (NEVER the rounded displayed 0.268431) ---------------------
fx.alpha0 = sqrt(pi)/abs(det(invz_ion().a))^(1/3);
assert(isscalar(fx.alpha0) && isfinite(fx.alpha0) && fx.alpha0 > 0, ...
    'invz_ewald_fixtures: alpha0 must be a finite positive scalar.');
end

% =====================================================================
function assert_rows_unique(Mtx, n, label)
% Fail fast on any cardinality or duplicate-row defect in a frozen sample.
assert(size(Mtx,1) == n && size(Mtx,2) == 3, ...
    'invz_ewald_fixtures: %s must be [%d,3] (got [%d,%d]).', label, n, size(Mtx,1), size(Mtx,2));
assert(all(isfinite(Mtx(:))), 'invz_ewald_fixtures: %s must be finite.', label);
nu = size(unique(Mtx, 'rows'), 1);
assert(nu == n, 'invz_ewald_fixtures: %s rows must be unique (got %d unique of %d).', label, nu, n);
end
