function result = test_invzp_local_descending_continuity()
%TEST_INVZP_LOCAL_DESCENDING_CONTINUITY Regress the 3.95667 -> 3.98 T jump.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root,fullfile(root,'invz_common'),fullfile(root,'invz_projected'));
F = load(fullfile(root,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
T = 0.31;
fields = [3.956666666666667 3.98 4.003333333333333];
w = (0.18:2e-4:0.205).';
solveOpts = struct('mix_outer',0.3,'max_outer',2000, ...
    'hmf_integral_mode','missing_area_approx', ...
    'hmf_missing_area_factor',1,'nH',129, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_profile_sweep_direction','descending_local');
opts = struct('Jnu',F.J,'info',F.info,'hyp',true,'eta',1e-3, ...
    'parallel',false,'verbose',false,'peak_wmin',0.18, ...
    'peak_mode','strongest','solve_opts',solveOpts);
S = invz_spectra_map(ion,T,fields,w,opts);

% At exactly zero transverse field the low-edge refinement carrier is
% singular, but the independently certified target-field high-h carrier must
% recover the same established ordered solution without changing sweep mode.
zeroOpts = solveOpts;
zeroOpts.J0eff = F.info.Jcc0;
zeroOpts.Jxx0 = F.info.Jaa0;
zeroOpts.hyp = true;
zeroOpts.mix_outer = 0.35;
zero = invz_solve_point_ordered(ion,0.1,0,F.J,zeroOpts);
zeroNear = invz_solve_point_ordered(ion,0.1,1e-6,F.J,zeroOpts);

expectedHmf = [0.00603605086193 0.00496425832928 0.00352969470584];
expectedPeak = [0.195199373624 0.193574616534 0.192073275426];
assert(isequal(S.phase,[1 1 1]) && all(isfinite(S.chiz),'all'), ...
    'The target-local electro-nuclear map must contain no masked point.');
assert(max(abs(S.hmf-expectedHmf)) < 5e-10, ...
    'The target-local ordered roots changed unexpectedly.');
assert(all(diff(S.hmf) < 0) && all(diff(S.moment) < 0) && ...
    all(diff(S.component_edge) < 0), ...
    'The ordered state and certified component must vary monotonically.');
assert(max(abs(S.Epeak-expectedPeak)) < 2e-6 && ...
    all(diff(S.Epeak) < 0) && max(abs(diff(S.Epeak))) < 2e-3, ...
    'The electronic branch must remain smooth across 3.95667 -> 3.98 T.');
assert(zero.converged && zero.is_ordered && ...
    abs(zero.hmf-0.0381008806693) < 5e-10 && ...
    zero.hmf_prof.refinement_fallback_used && ...
    zero.hmf_prof.refinement_fallback_kind == "target_high_node", ...
    'The target-local production route must retain the exact-zero solution.');
assert(zeroNear.converged && ...
    abs(zeroNear.hmf-zero.hmf) < 1e-8 && ...
    abs(zeroNear.Sigma0-zero.Sigma0) < 1e-8 && ...
    abs(zeroNear.m0-zero.m0) < 1e-8, ...
    'The target-local exact-zero state must be continuous to 1e-6 T.');

result = struct('fields',fields,'hmf',S.hmf,'moment',S.moment, ...
    'component_edge',S.component_edge,'Epeak',S.Epeak, ...
    'zero_hmf',zero.hmf);
fprintf(['test_invzp_local_descending_continuity: adjacent peak steps ' ...
    '%.6g / %.6g meV\n'],diff(S.Epeak));
end
