function result = test_invzp_seeded_refinement_carrier()
%TEST_INVZP_SEEDED_REFINEMENT_CARRIER Regress the 4.00333 T retry mask.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root,fullfile(root,'invz_common'),fullfile(root,'invz_projected'));
F = load(fullfile(root,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
T = 0.31;
fields = [3.933333333333333 3.956666666666667 ...
    4.003333333333333 4.376666666666667];
w = [0; 5e-4; 1e-3];
solveOpts = struct('mix_outer',0.3,'max_outer',2000, ...
    'hmf_integral_mode','missing_area_approx', ...
    'hmf_missing_area_factor',1,'nH',129, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component', ...
    'hmf_adjacent_retry',true,'hmf_adjacent_retry_max_span',0.35, ...
    'hmf_ordered_boundary_retry',true, ...
    'hmf_ordered_boundary_retry_max_span',0.20, ...
    'hmf_ordered_boundary_retry_min_D_uni',1e-3, ...
    'hmf_ordered_boundary_retry_min_Fprime',1e-3);
opts = struct('Jnu',F.J,'info',F.info,'hyp',true,'eta',1e-3, ...
    'parallel',false,'verbose',false,'solve_opts',solveOpts);
S = invz_spectra_map(ion,T,fields,w,opts);

target = 3;
assert(isequal(S.phase,[1 1 1 2]), ...
    'The focused electro-nuclear map must contain no masked phase.');
assert(S.ordered_boundary_retry.attempted(target) && ...
    S.ordered_boundary_retry.used(target) && ...
    S.ordered_boundary_retry.status(target) == "used", ...
    'The two-source boundary retry must recover 4.00333 T.');
assert(all(isfinite(S.chiz(:,target))) && ...
    abs(S.hmf(target)-0.00347743309681) < 1e-10 && ...
    abs(S.moment(target)-0.594033372513) < 1e-9, ...
    'The recovered target spectrum/state changed unexpectedly.');
assert(S.D_ord(target) > 1e-3 && ...
    S.ordered_boundary_retry.Fprime_min(target) > 1e-3 && ...
    S.ordered_boundary_retry.hmf_delta(target) < 1e-6 && ...
    S.ordered_boundary_retry.Sigma_delta(target) < 1e-6, ...
    'The recovered point must pass the unchanged stability/agreement gates.');

result = struct('field',fields(target),'hmf',S.hmf(target), ...
    'moment',S.moment(target),'D_uni',S.D_ord(target), ...
    'Fprime_min',S.ordered_boundary_retry.Fprime_min(target), ...
    'Sigma_delta',S.ordered_boundary_retry.Sigma_delta(target));
fprintf(['test_invzp_seeded_refinement_carrier: recovered %.8f T, ' ...
    'hmf %.10g meV, D_uni %.6g\n'], ...
    result.field,result.hmf,result.D_uni);
end
