function results = test_invzp_filtered_profile_integral()
%TEST_INVZP_FILTERED_PROFILE_INTEGRAL Exact contract of visual node filtering.
here = fileparts(mfilename('fullpath'));
projected = fileparts(here);
repo = fileparts(projected);
addpath(projected,fullfile(repo,'invz_common'),repo);

h = [0.1 0.2 0.4 0.8 1.0];
r = [2 3 4 Inf 6];
accepted = [true false true true true];
[h0, out] = invz_filtered_profile_integral(h,r,accepted,10);

expected = [0.6 NaN 1.5 NaN 4.5];
finite_err = max(abs(h0(isfinite(expected))-expected(isfinite(expected))));
nan_ok = isequal(isnan(h0),isnan(expected));
meta_ok = isequal(out.used_indices,[1;3;5]) && ...
    out.node_count == 3 && out.omitted_node_count == 2 && ...
    out.ineligible_node_count == 1 && ...
    out.nonfinite_eligible_node_count == 1 && ...
    out.bridge_panel_count == 2 && ...
    out.bridged_missing_node_count == 2 && ...
    isequal(out.bridge_missing_node_count,[1;1]) && ...
    abs(out.bridged_width_total-0.9) < 1e-15 && ...
    abs(out.max_bridge_width-0.6) < 1e-15 && ...
    out.lower_omitted_width == 0 && ...
    abs(out.lower_bridge_width-0.1) < 1e-15 && ...
    out.anchor == "external_h0_r" && out.anchor_r == 10 && out.visual_only;

[h0c, outc] = invz_filtered_profile_integral(h.',r.',accepted.',10);
orientation_ok = iscolumn(h0c) && isequaln(h0c,h0.') && ...
    isequal(outc.used_mask,accepted.' & isfinite(r.'));

[empty_h0, empty_out] = invz_filtered_profile_integral( ...
    h,r,false(size(h)),10);
empty_ok = all(isnan(empty_h0)) && empty_out.node_count == 0 && ...
    isnan(empty_out.first_retained_h) && ...
    empty_out.lower_omitted_width == 0 && ...
    isnan(empty_out.lower_bridge_width) && ...
    empty_out.bridge_panel_count == 0;

if finite_err > 1e-14 || ~nan_ok || ~meta_ok || ~orientation_ok || ~empty_ok
    error('invz:testFilteredProfileIntegral', ...
        ['filtered profile contract failed: finite_err=%.3g, nan=%d, ' ...
         'meta=%d, orientation=%d, empty=%d'], ...
        finite_err,nan_ok,meta_ok,orientation_ok,empty_ok);
end

results = struct('finite_error',finite_err,'nan_mask_ok',nan_ok, ...
    'metadata_ok',meta_ok,'orientation_ok',orientation_ok, ...
    'empty_case_ok',empty_ok,'example',out);
fprintf(['test_invzp_filtered_profile_integral: eligible/ineligible/nonfinite ' ...
    'filtering and %d bridge panels passed\n'],out.bridge_panel_count);
end
