function results = test_invzp_missing_area_integral()
%TEST_INVZP_MISSING_AREA_INTEGRAL Exact controlled-component contract.
here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(here));
addpath(fullfile(repo,'invz_common'));

h = [0.1 0.2 0.4 0.8 1.0];
r = [2 3 4 5 6];
certified = [true false true true true];
[h0, out] = invz_missing_area_integral(h,r,certified,2);
expected = [NaN NaN 2 3.8 4.9];
finite_error = max(abs(h0(isfinite(expected))-expected(isfinite(expected))));
mask_ok = isequal(isnan(h0),isnan(expected));
meta_ok = isequal(out.selected_indices,[3;4;5]) && ...
    out.node_count == 3 && out.edge_index == 3 && ...
    out.component_edge == 0.4 && out.edge_r == 4 && ...
    out.missing_area == 2 && out.interior_bridge_count == 0 && ...
    ~out.uses_uncertified_nodes && out.certified_below_edge_count == 1 && ...
    out.unresolved_below_edge_count == 1 && out.approximation_only;

[h0c, outc] = invz_missing_area_integral( ...
    h.',r.',certified.',2);
orientation_ok = iscolumn(h0c) && ...
    isequal(isnan(h0c),isnan(expected.')) && ...
    max(abs(h0c(isfinite(h0c))-expected(isfinite(expected)).')) < 1e-14 && ...
    iscolumn(outc.selected_mask);

[empty_h0, empty_out] = invz_missing_area_integral( ...
    h,r,[true true true true false],2);
empty_ok = all(isnan(empty_h0)) && empty_out.node_count == 0 && ...
    isnan(empty_out.component_edge) && isempty(empty_out.selected_indices);

negative_rejected = false;
try
    invz_missing_area_integral(h,r,certified,-eps);
catch err
    negative_rejected = strcmp(err.identifier,'invz:missingAreaIntegral');
end

if finite_error > 1e-14 || ~mask_ok || ~meta_ok || ...
        ~orientation_ok || ~empty_ok || ~negative_rejected
    error('invz:testMissingAreaIntegral', ...
        ['missing-area contract failed: error=%.3g mask=%d meta=%d ' ...
         'orientation=%d empty=%d negative=%d'],finite_error,mask_ok, ...
        meta_ok,orientation_ok,empty_ok,negative_rejected);
end

results = struct('finite_error',finite_error,'mask_ok',mask_ok, ...
    'metadata_ok',meta_ok,'orientation_ok',orientation_ok, ...
    'empty_case_ok',empty_ok,'negative_rejected',negative_rejected);
fprintf(['test_invzp_missing_area_integral: contiguous certified suffix, ' ...
    'explicit area, and no-bridge contract passed\n']);
end
