function result = test_invzp_zero_field_failclosed()
%TEST_INVZP_ZERO_FIELD_FAILCLOSED Reject singular nodes without losing a valid suffix.
here = fileparts(mfilename('fullpath'));
projected = fileparts(here);
repo = fileparts(projected);
addpath(repo,fullfile(repo,'invz_common'),projected);
F = load(fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
T = 0.1;

invalid = invz_twolevel_ordered(ion,T,0,0, ...
    struct('Jxx0',F.info.Jaa0,'domain_policy','return'));
assert(~invalid.valid && invalid.Delta < 1e-4, ...
    'The exact-zero predictor must remain outside the two-level domain.');

opts = struct('J0eff',F.info.Jcc0,'Jxx0',F.info.Jaa0, ...
    'mix_outer',0.35,'max_outer',2000,'nH',33, ...
    'hmf_integral_mode','missing_area_approx', ...
    'hmf_missing_area_factor',1, ...
    'hmf_approx_branch', ...
    'picard_attracting_contiguous_high_h_component');
point = invz_solve_point_ordered(ion,T,0,F.J,opts);
p = point.hmf_prof;
assert(point.converged && point.is_ordered && isfinite(point.hmf), ...
    'The exact-zero approximation must retain a certified terminal component.');
assert(~p.predictor_converged && ...
    p.predictor_static_status == "twolevel_domain_invalid", ...
    'The singular predictor must be explicitly rejected, not evaluated.');
assert(p.missing_area_integral.node_count >= 2, ...
    'A certified positive-h suffix must remain available.');
assert(point.tl.Delta >= 1e-4 && point.D_uni > 0 && ...
    point.final_resid < 1e-8, ...
    'The exported state must be inside the ordinary vertex and physical domains.');

[wn,~,beta] = invz_matsubara(T,40);
g = real(invz_g(point.tl,1i*wn));
sigma_small = invz_sigma_ordered( ...
    point.tl,point.lambda,point.K,g,beta);
tl_zero = point.tl;
tl_zero.M2 = 0;
sigma_zero = invz_sigma_ordered( ...
    tl_zero,point.lambda,point.K,g,beta);
sigma_limit_error = max(abs(sigma_small.Sigma-sigma_zero.Sigma));
assert(all(isfinite(sigma_zero.Sigma)) && sigma_limit_error < 1e-12, ...
    'The exact M2=0 Matsubara limit must be finite and continuous.');

w = linspace(0,0.025,101).';
copts = struct('Jsel',F.info.Jcc0,'eta',5e-5, ...
    'Jxx0',F.info.Jaa0,'hyp',true,'si',point.si);
real_small = invz_chi_realaxis(ion,T,0,point,w,copts);
point_zero = point;
point_zero.tl = tl_zero;
real_zero = invz_chi_realaxis(ion,T,0,point_zero,w,copts);
realaxis_limit_error = max(abs( ...
    real_small.chi_cc_q(:)-real_zero.chi_cc_q(:)));
assert(all(isfinite(real_zero.chi_cc_q),'all') && ...
    realaxis_limit_error < 1e-12, ...
    'The exact M2=0 real-axis limit must be finite and continuous.');

result = struct('Delta_predictor',invalid.Delta,'hmf',point.hmf, ...
    'Delta_final',point.tl.Delta,'D_uni',point.D_uni, ...
    'final_resid',point.final_resid, ...
    'component_nodes',p.missing_area_integral.node_count, ...
    'component_edge',p.missing_area_integral.component_edge, ...
    'invalid_profile_nodes',nnz(p.static_status == "twolevel_domain_invalid"), ...
    'sigma_M2_zero_error',sigma_limit_error, ...
    'realaxis_M2_zero_error',realaxis_limit_error);
fprintf(['test_invzp_zero_field_failclosed: hmf %.9g meV, ' ...
    'final Delta %.9g meV, invalid low-h nodes %d\n'], ...
    result.hmf,result.Delta_final,result.invalid_profile_nodes);
end
