function results = test_invzp_bare_mf_state()
%TEST_INVZP_BARE_MF_STATE Regress the near-critical bracketed bare-MF solve.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root, fullfile(root,'invz_common'), fullfile(root,'invz_projected'));

ion = invz_ion();
T = 0.1;
J0eff = 0.0064216618094169392;
Jxx0 = 0.003511833120752956;

% This production-grid field is only 0.2446 mT below the bare-MF critical
% point. The former 1200-step ordered Picard probe stopped at a residual of
% 6.71e-7 meV; the bracketed solve must recover the nonzero root directly.
[ordered, phaseOrdered, massOrdered, dout] = ...
    invz_bare_mf_state(ion,T,4.95,J0eff,Jxx0,true);
assert(phaseOrdered == 1 && massOrdered < 0, ...
    '4.95 T must lie on the bare-MF ordered side.');
assert(ordered.mf_converged && isfinite(ordered.bare_mf_residual), ...
    'The 4.95 T fixed-hz single-ion state must converge.');
assert(abs(dout.root-0.000301094086364) < 1e-9, ...
    'The 4.95 T nonzero bare-MF root changed.');
assert(abs(dout.root_residual) < 1e-10, ...
    'The 4.95 T bare-MF root residual exceeds its gate.');
assert(dout.method == "bracketed_nonzero_root", ...
    'The ordered side must use the bracketed nonzero-root method.');

[pm, phasePm, massPm, dp] = ...
    invz_bare_mf_state(ion,T,5.04,J0eff,Jxx0,true);
assert(phasePm == 2 && massPm > 0 && pm.mf_converged, ...
    '5.04 T must select the converged bare-MF paramagnet.');
assert(dp.method == "pm_mass" && isnan(dp.root), ...
    'The PM side must not attempt a nonzero ordered root.');

[~, phaseZero, massZero, dz] = ...
    invz_bare_mf_state(ion,T,4.95,0,Jxx0,true);
assert(phaseZero == 2 && massZero == 1 && dz.method == "pm_mass", ...
    'Zero longitudinal coupling must preserve the PM-only API contract.');

results = struct('field_ordered',4.95,'mass_ordered',massOrdered, ...
    'root_ordered',dout.root,'root_residual',dout.root_residual, ...
    'field_pm',5.04,'mass_pm',massPm);
fprintf('test_invzp_bare_mf_state: ordered root %.12g meV; PM mass %.6g\n', ...
    dout.root,massPm);
end
