function result = test_invzp_reduced_residual()
%TEST_INVZP_REDUCED_RESIDUAL Equivalence checks for the exact 4D diagnostic.
repo = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(repo,fullfile(repo,'invz_common'),fullfile(repo,'invz_projected'));
fixture = fullfile(repo,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat');
F = load(fixture);

healthy = healthy_fixture_check(F);
accepted = accepted_low_field_check(F);

fprintf(['pre-assert: 4T ||R|| %.9g, dK %.9g, dSigma %.9g; ' ...
    '1T initial ||R|| %.9g, dK %.9g, dSigma %.9g, root ||R|| %.9g\n'], ...
    healthy.reduced_residual_norm,healthy.dynamic_K_error, ...
    healthy.dynamic_Sigma_error,accepted.initial_reduced_residual_norm, ...
    accepted.dynamic_K_error,accepted.dynamic_Sigma_error, ...
    accepted.reduced_root_residual_norm);
assert(healthy.dynamic_K_error < 1e-9);
assert(healthy.dynamic_Sigma_error < 1e-10);
assert(healthy.reduced_residual_norm < 2e-5);
assert(accepted.picard_converged);
assert(accepted.dynamic_K_error < 1e-9);
assert(accepted.dynamic_Sigma_error < 1e-10);
assert(accepted.reduced_root_residual_norm < 1e-10);
assert(accepted.outer_map_at_reduced_root < 1e-8);
assert(accepted.dynamic_max_root_count == 1);
assert(accepted.dynamic_unresolved_frequencies == 0);

result = struct('healthy_4T',healthy,'accepted_1T',accepted, ...
    'fixture',fixture);
fprintf(['reduced residual: 4T ||R||inf %.3g, dK %.3g; ' ...
    '1T root ||R||inf %.3g, outer-map residual %.3g\n'], ...
    healthy.reduced_residual_norm,healthy.dynamic_K_error, ...
    accepted.reduced_root_residual_norm, ...
    accepted.outer_map_at_reduced_root);
end

function out = healthy_fixture_check(F)
T = F.provenance.T;
[wn,wts,beta] = invz_matsubara(T,40);
ctx = make_hybrid_context(F.pt.si,F.pt.tl,T,wn,wts,beta,F);
q = invz_ordered_reduced_residual( ...
    [F.pt.lambda(:);static_x(F.pt,ctx)],ctx, ...
    struct('Jsup',F.info.Jcc0));
sigref = invz_sigma_ordered(ctx.tl,F.pt.lambda(:),q.K,ctx.g,ctx.beta);
out = struct('status',string(q.status), ...
    'reduced_residual_norm',q.residual_norm, ...
    'dynamic_K_error',max(abs(q.K(2:end)-F.pt.K(2:end))), ...
    'dynamic_Sigma_error',max(abs(q.Sigma-sigref.Sigma)), ...
    'fixture_state_Sigma_error',max(abs(q.Sigma-F.pt.Sigma)), ...
    'dynamic_max_root_count',max(q.dynamic.root_count(2:end)), ...
    'dynamic_unresolved_frequencies', ...
        sum(q.dynamic.fallback_unresolved(2:end)));
end

function out = accepted_low_field_check(F)
T = F.provenance.T;
Bx = 1;
h = 0.00624162310965;
ion = invz_ion();
[wn,wts,beta] = invz_matsubara(T,40);
si = invz_single_ion(ion,T,[Bx 0 0], ...
    struct('hyp',true,'Jxx0',F.info.Jaa0,'hz_fixed',h));
tl = invz_twolevel_ordered(ion,T,Bx,h,struct('Jxx0',F.info.Jaa0));
ctx = make_hybrid_context(si,tl,T,wn,wts,beta,F);
mapopts = struct('emt_static', ...
    struct('Jsup',F.info.Jcc0,'warn',false));
mapfun = @(s) invz_ordered_outer_map(s,ctx,mapopts);
probe = invz_outer_picard_diagnostic(mapfun,zeros(size(wn)), ...
    struct('mix',0.5,'tol',1e-10,'maxit',400));
assert(probe.converged);
outer = mapfun(probe.Sigma);
qx = invz_ordered_reduced_residual( ...
    [outer.lambda(:);outer.static.Gtil0],ctx, ...
    struct('Jsup',F.info.Jcc0));

fsopts = optimoptions('fsolve','Display','off', ...
    'FunctionTolerance',1e-20,'StepTolerance',1e-12, ...
    'OptimalityTolerance',1e-12,'MaxIterations',50, ...
    'MaxFunctionEvaluations',400);
[y,~,exitflag,output] = fsolve( ...
    @(v) invz_ordered_reduced_vector(v,ctx, ...
    struct('Jsup',F.info.Jcc0)),qx.y,fsopts);
root = invz_ordered_reduced_residual( ...
    y,ctx,struct('Jsup',F.info.Jcc0));
outer_at_root = mapfun(root.Sigma);

out = struct('picard_converged',probe.converged, ...
    'picard_iterations',probe.iterations, ...
    'initial_reduced_residual_norm',qx.residual_norm, ...
    'dynamic_K_error',max(abs(qx.K(2:end)-outer.K(2:end))), ...
    'dynamic_Sigma_error',max(abs(qx.Sigma-outer.Sigma_map)), ...
    'fsolve_exitflag',exitflag,'fsolve_output',output, ...
    'reduced_root_y',y,'reduced_root_residual_norm',root.residual_norm, ...
    'root_admissible',root.trial_admissible, ...
    'outer_map_at_reduced_root',outer_at_root.residual_norm, ...
    'dynamic_max_derivative',max(root.dynamic.derivative(2:end)), ...
    'dynamic_max_bound',max(root.dynamic.derivative_bound(2:end)), ...
    'dynamic_max_root_count',max(root.dynamic.root_count(2:end)), ...
    'dynamic_unresolved_frequencies', ...
        sum(root.dynamic.fallback_unresolved(2:end)));
end

function x = static_x(pt,ctx)
[~,go] = invz_gstat_ordered(ctx.tl,pt.lambda(1:2),pt.K(1), ...
    pt.Sigma(1),ctx.beta,ctx.G0inel0,ctx.G0el0, ...
    struct('stable_form',true));
x = go.Gtil0;
end

function ctx = make_hybrid_context(si,tl,T,wn,wts,beta,F)
c0 = invz_chi0z(si,T,1i*wn,struct('elastic',true));
G0 = -real(squeeze(c0(3,3,:)));
c0i = invz_chi0z(si,T,1i*wn(1),struct('elastic',false));
G0i = -real(c0i(3,3,1));
X = real(c0(:,:,1));
feedback = X(3,1)*(F.info.Jaa0/(1-F.info.Jaa0*X(1,1)))*X(1,3);
G0e = -(X(3,3)+feedback)-G0i;
g = real(invz_g(tl,1i*wn));
ctx = struct('G0',G0,'g',g,'tl',tl,'wts',wts,'beta',beta, ...
    'Jnu_flat',F.J,'J0eff',F.info.Jcc0, ...
    'G0inel0',G0i,'G0el0',G0e);
end
