function result = test_invzp_nohyp_linearized_handoff()
%TEST_INVZP_NOHYP_LINEARIZED_HANDOFF Regress the electronic-only soft branch.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(root,fullfile(root,'invz_common'),fullfile(root,'invz_projected'));
F = load(fullfile(root,'docs','diagnostics','invzp_static_wp1', ...
    'legacy_4T_fixture.mat'));
ion = invz_ion();
T = 0.31;
fields = [3.32 3.33 3.334 3.3348 3.335 3.34];
w = (0:5e-5:0.04).';
solveOpts = struct('mix_outer',0.3,'max_outer',2000, ...
    'ordered_state_mode','linearized_pm_handoff', ...
    'hmf_linearized_window',[3.0 3.7], ...
    'hmf_linearized_fieldstep',0.05, ...
    'hmf_linearized_critical_tol',1e-7);
opts = struct('Jnu',F.J,'info',F.info,'hyp',false,'eta',5e-5, ...
    'parallel',false,'verbose',false,'peak_wmin',0, ...
    'peak_mode','lowest_local','solve_opts',solveOpts);
S = invz_spectra_map(ion,T,fields,w,opts);

assert(isequal(S.phase,[1 1 1 1 2 2]), ...
    'The electronic-only map must hand off ordered -> PM without a coarse-grid mask.');
assert(all(diff(S.moment(1:4)) < 0) && S.moment(4) < 0.05, ...
    'The ordered moment must decrease toward zero at the projected boundary.');
assert(all(isfinite(S.Epeak)) && all(diff(S.Epeak(1:4)) < 0) && ...
    all(diff(S.Epeak(5:6)) > 0) && max(S.Epeak(4:5)) < 2e-3, ...
    'The lowest electronic pole must soften continuously through the handoff.');
assert(all(isfinite(S.chiz),'all'), ...
    'No susceptibility column may be lost on the coarse boundary grid.');
assert(abs(S.linearized_pm_handoff.boundary_field-3.3348853) < 5e-6, ...
    'The warm-refined projected critical field changed unexpectedly.');
assert(abs(S.linearized_pm_handoff.J0z_mf-0.005603681) < 5e-9, ...
    'The boundary-linearized modified coupling changed unexpectedly.');

% Three-argument callers retain the historical strongest-peak result exactly.
synthetic = [0 1 3 1 0; 0 2 1 4 0].';
grid = (0:4).';
assert(isequaln(invz_peak_energy(synthetic,grid,0), ...
    invz_peak_energy(synthetic,grid,0,'strongest')), ...
    'The default peak picker must remain bitwise identical to strongest mode.');
assert(invz_peak_energy(synthetic(:,2),grid,0,'lowest_local') < ...
    invz_peak_energy(synthetic(:,2),grid,0,'strongest'), ...
    'lowest_local must select the lower soft-mode peak in a multi-peak column.');

% The approximation cannot leak into the electro-nuclear calculation.
hypOpts = opts;
hypOpts.hyp = true;
threw = false;
try
    invz_spectra_map(ion,T,fields(1),w(1:3),hypOpts);
catch err
    threw = strcmp(err.identifier,'invz:hmfLinearizedHyperfine');
end
assert(threw, ...
    'The boundary-linearized route must reject hyp=true before solving.');

result = struct('boundary_field',S.linearized_pm_handoff.boundary_field, ...
    'J0z_mf',S.linearized_pm_handoff.J0z_mf, ...
    'phase',S.phase,'moment',S.moment,'Epeak',S.Epeak);
fprintf(['test_invzp_nohyp_linearized_handoff: Bc %.9f T, ' ...
    'last ordered/first PM peaks %.6g / %.6g meV\n'], ...
    result.boundary_field,S.Epeak(4),S.Epeak(5));
end
